docker-mailserver/docker-mailserver

postfix/accounts.cf, postfix/redirects.cf, postfix/virtual, start-mailserver.sh
#10 Separate virtuals and accounts.
=> Accounts and virtual conf split

start-mailserver.sh
=> forward only domains should be added to vhosts

Dockerfile
- cleanup lists /var/lib/apt/lists/*
For a smaller image
=> added rm -rf /var/lib/apt/lists/*

Dockerfile, Makefile, start-mailserver.sh, test/auth/pop3-auth.txt, test/test.sh
Add pop3 support with optional flag as per #54 
Note:
self-signed certificates won't work with gmail since they don't support them anymore
=> Add pop3 support

Dockerfile, README.md, postfix/default-opendmarc, postfix/main.cf, postfix/opendmarc.conf, start-mailserver.sh
=>  - added DMARC (opendmarc) support with basic setup

Makefile, README.md, test/test.sh
Also added a `clean` command in `Makefile`.
=> Added tests and simplified some of them

start-mailserver.sh, test/test.sh
Create default imap folders for Trash, Drafts and Sent.
=> Default imap folders

Makefile, start-mailserver.sh, test/tests.bats
Implements  #113 
Fail2ban config has been updated accordingly.
Added also a check before copying spamassassin rule file.
=> All email-related services now logs in /var/log/mail/

start-mailserver.sh
Checks existince of cert, chain and privkey.pem.
Concats these files to combined.pem and adds a linebreak after each file
if there were none. This commit doesn't change the LE created .pem
files, so no unlinking on the host should happen (see
https://github.com/tomav/docker-mailserver/pull/111)
=> check .pem existence and concat to combined.pem with added eol

start-mailserver.sh
See also Issue #125 
Patches for @Reldeis PR #118
=> Fix bug when combining certs for Letsencrypt.

target/start-mailserver.sh
Fixes error from logrotate when fail2ban is disabled (failure
when reloading the service).
=> Fixes paths for SSL setup, spamassassin and postfix addon config.

target/start-mailserver.sh
=> Fix a problem in the reload function of spamassassin cron.daily script.

README.md
Just fixing the biggest issues this project faces- white space issues.
Vim yells at me every time I open the readme, so I though I would share my fixes.
=> V2 readme formatting

.gitignore, README.md, config/spamassassin-rules.cf, docker-compose.yml.dist, target/start-mailserver.sh
Refactored documentation and Wiki
Moved docker-compose.yml.dist to version 2 with data volume container
Renamed DMS_SSL to SSL_TYPE
Refactored start-mailserver to avoid DKIM errors
=> Refactored documentation and Wiki

test/tests.bats
Removed hardcoded image name in tests.
Tests have not been changed, BTW.
Possible problem: locally the current v2 version fails CI tests, so I don't know if even this branch will build correctly on Travis. 
Anyway I've not changed the tests. Let see.
=> Changed few docker commands used in tests:

Dockerfile, Makefile, README.md, target/start-mailserver.sh, test/tests.bats
... ENABLE_MANAGE_SIEVE has been set.
Adapted README and updated tests.
The functionality has successfully been tested using the Sieve
Thunderbird plugin.
Fixes #167
=> Configure dovecot's managesieve plugin when the environment variable

target/postfix/main.cf
Fixed #197 removing SORBS from RBL
=> Removed SORBS from RBL

.gitignore, config/fail2ban-jail.cf, target/start-mailserver.sh, test/config/fail2ban-jail.cf, test/tests.bats
#200 
Now it's possible to change configurations for fail2ban in config/ directory, too.
=> added ability to overwrite jail.conf

target/start-mailserver.sh
Adding two simple echo statements verifying when `ENABLE_FAIL2BAN` or `ENABLE_MANAGESIEVE` are set.
=> Startup logging

Makefile, target/start-mailserver.sh, test/tests.bats
This pull request is in response to #216.
This PR only selectively disabled either clamav, spamassassin, or amavis.
I am not sure if the config files needs to be touched at all.
=> selective service disable

Dockerfile, Makefile, README.md, config/fetchmail.cf, target/fetchmail/fetchmailrc, target/start-mailserver.sh, test/config/fetchmail.cf, test/tests.bats
To retrieve emails from external mail accounts.
=> Implement fetchmail (#260)

target/start-mailserver.sh
ses often connection timeout that used 25 port, therefore I  add a choosesable env
=> add AWS_SES_PORT env

setup.sh, test/tests.bats
Add subcommands 'debug show-mail-logs', 'inspect', 'login'. Add option
'-c' to specify the name of the running container. Add option '-i' to
specify the image name.
=> Improve and extend setup.sh

target/start-mailserver.sh
=> missing with relayhost

README.md
Fenced code blocks support YAML syntax highlighting.
=> Add syntax highlighting for YAML code snippets.

Dockerfile, docker-compose.elk.yml.dist, elk/01-mailserver.conf, elk/02-beats-input.conf, elk/10-syslog.conf, elk/Dockerfile, elk/amavis.grok, target/filebeat.yml.tmpl, target/start-mailserver.sh
=> add ELK support

Dockerfile, target/dovecot/10-master.conf, target/dovecot/20-lmtp.conf, target/postfix/main.cf, target/postfix/master.cf, test/tests.bats
=> make Postfix -> Dovecot delivery over LMTP

target/start-mailserver.sh
To make it easier to extend and maintain the logics of initialization of the mailserver and it's components i restructured the whole script into small junks/functions. 
**Let me explain the logics here:**
We have 5 steps to bring the mailserver up (they are running after one another) :
1. Check: these are functions to check the configuration sanity of the setup
2. Setup: here happens the main configuration initialization. 
3. Fix: within this section we place proper fixes for problems that may occur (like permissions of the maildirs)
4. Misc: within this section we can place functions that needs to be run before starting the daemons (like saving the container state)
5. Start: within this section all daemon processes getting started
I also made a simple registration logic, for …
=> Restructure start-mailserver.sh #338

.travis.yml
=> Added travis_wait in config to increase build time to 20min

Makefile, target/start-mailserver.sh, test/tests.bats
=> Disables clamav config in amavis when DISABLE_CLAMAV=1. 

README.md, target/start-mailserver.sh
=> ONE_DIR documentation

.editorconfig, test/tests.bats
This PR adds [.editorconfig rules](http://editorconfig.org) to standardize some code style aspects of project.
=> Add .editorconfig rules

target/opendkim/opendkim.conf
=> Amazon SES Manual DKIM Signing #470

Makefile, test/config/dovecot.cf, test/config/postfix-main.cf, test/email-templates/existing-alias-recipient-delimiter.txt, test/tests.bats
Adds integration test for extension address delivery.
This is relevant to #442 issue and proves that extension address delivery works as expected.
=> Integration test for extension address delivery

target/postgrey/postgrey, target/start-mailserver.sh, test/tests.bats
fixes postgrey not being able to bind to its port
Issue: #569
=> fixed postgrey inet parameter

CONTRIBUTING.md
Mention that you have to manually initialize and update submodules, otherwise you find out after a very long wait.
=> Mention submodule dependency

Dockerfile, Makefile, target/fail2ban/jail.conf, test/tests.bats
Another try at upgrading to 16.04, as tests work from clean builds just fine locally.
Forked from #532.
=> Upgrade to 16.04

target/postfix/master.cf, target/start-mailserver.sh, test/tests.bats
This should fix most of 2.3 issues reported in #545 & #586
=> This should fix most of 2.3 issues reported in #545 & #586

Dockerfile, Makefile, target/dovecot/90-sieve.conf, target/postfix/master.cf, target/start-mailserver.sh, test/config/postfix-master.cf, test/config/sieve-pipe/pipe_to_tmp, test/config/user2@otherdomain.tld.dovecot.sieve, test/email-templates/sieve-pipe.txt, test/tests.bats
Support for modifying Postfix' master.cf, using the  syntax, in postfix-master.cf
Fixes issue-594
=> Support for modifying Postfix' master.cf

Makefile, README.md, target/start-mailserver.sh, test/tests.bats
Ref: #589
Environment variable to change the amavis tag `sa_spam_subject_tag` outside the container .
=> Environment variable for amavis subject tag

target/start-mailserver.sh
=> Fixed #649 Postgrey re-startup by removing pid file

Dockerfile
Removed the initial duplicate apt-get update / apt-get upgrade and merged a couple of RUN commands together. This should result in less layers and a smaller image because the apt cache is cleared properly now (the first apt-get update / upgrade stored the caches/lists into a layer).
=> Dockerfile cleanup

.travis.yml
This could fix the problem that clamav is not able to update in docker build
=> using travis_retry for image building

Dockerfile, test/tests.bats
=> Expand the decoders for amavis

Dockerfile, Makefile, target/postfix/ldap-domains.cf, target/start-mailserver.sh, test/docker-openldap/bootstrap/ldif/03_user-email-other-primary-domain.ldif, test/docker-openldap/bootstrap/ldif/04_user-email-different-uid.ldif, test/tests.bats
=> Also search on the domain name for the virtual domain name in the ldap

Dockerfile
See #686
This should fix the amavis issue.
=> Fix the hook that restarts the amavis server and causes it to detach

target/start-mailserver.sh
This improves security because each installation has it own generated
dhparams file. See ticket #530 for more details.
=> Generate a new dhparams file if one_dir is set. (Resolves: #530)

README.md
=> Update readme of the fetchmail interval variable

target/start-mailserver.sh
=> Fix spamassassin directory typo (Closes: #739)

target/opendkim/opendkim.conf
Added List-ID and List-Unsubscribe omitted headers for DKIM verification.
=> Changed omitted headers for DKIM with mailtrain

setup.sh
=> added config-path option to setup.sh script

Dockerfile
=> Generate new DH param weekly instead of daily

README.md, target/postsrsd-wrapper.sh
Initial draft fix for issue #842: Make SRS_EXCLUDE_DOMAINS a configurable option
=> Add environment variable to allow for customizing SRS_EXCLUDE_DOMAINS

target/start-mailserver.sh
As in #843 I have removed the check for Let's encrypts cert.pem
=> Removed unneeded check for Let's encrypt cert.pem

target/bin/delalias, test/tests.bats
closes #909
tests succeed on my setup
=> fixed delalias, added additional tests

test/config/dovecot-lmtp/userdb
Got deleted somewhere.. :man_shrugging:
=> userdb got lost, I found it.

.env.dist
Some lines in .env are not properly commented out
=> Fix uncommented lines in .env file

Dockerfile
=> Issue #925, fixes 'duplicate log entry for /var/log/mail/mail.log'

target/start-mailserver.sh
=> fix for #932

README.md, target/bin/addmailuser, test/tests.bats
=> Ensure that the account contains a @

target/start-mailserver.sh
=> Fix missing quotes in env export (#1007)

README.md
=> Adds docker image update to restart section in README

Dockerfile, target/start-mailserver.sh
Remove freshclam job when clamav is off, run job as clamav user when on.
=> Fix 1198 freshclam

.gitmodules
The repo of bats that is currently bundled has been unmaintained for quite a while, this pr replaces the unmaintained version with an updated fork.
=> update bats to latest version

Dockerfile, README.md, docker-compose.elk.yml.dist, docker-compose.yml.dist, target/bin/report-pflogsumm-yesterday, target/start-mailserver.sh
Added support for running pflogsumm with cron for Yesterday while keeping backwards compatibility. Also added support for logwatch reports.
=> Fix #1093, pflogsumm and logwatch

target/start-mailserver.sh
Fixed mistake in `start_mailserver.sh` that caused recipient to be 0 or 1.
=> Fix report_recipient bugs

.travis.yml, test/mail_privacy.bats, test/test-files/email-templates/send-privacy-email.txt
Fix issue #1292 
Email body updated `test/test-files/email-templates/send-privacy-email.txt`
ClamAV and SpamAssassin disabled during this test (not relevant for this test)
=> [Test] "remove privacy details of the sender" misbehavior

.editorconfig
Replaces https://github.com/tomav/docker-mailserver/pull/1229
=> update editorconfig to make code more consistent

README.md, env-mailserver.dist, target/bin/delmailuser, target/start-mailserver.sh, test/mail_with_mdbox.bats, test/mail_with_sdbox.bats
Add a new option `DOVECOT_MAILBOX_FORMAT`to set Dovecot `mail_location` accordingly.
Issue #1313
=> New option DOVECOT_MAILBOX_FORMAT

target/bin/report-pflogsumm-yesterday
Remove irritating mail sent by cron.
=> Changed wrong set options in pflogsumm cron job

target/start-mailserver.sh
Fix #801 by simply touching the file if it doesn't exist.
@Tecnativa TT20505
=> Avoid infinite failure log in Amavis with SMTP_ONLY=1

README.md, target/start-mailserver.sh
This is the requested minimised PR based on the current master. This replaces #1119
=> activate SA shortcircuit features via env, fixes #1118 (again)

Dockerfile, README.md, target/start-mailserver.sh
remove not needed log files after build
=> remove not needed log files after build

README.md, env-mailserver.dist
=> README, env file: Warn about open relay configuration

Dockerfile
Fix for https://github.com/tomav/docker-mailserver/issues/1465
=> rsyslog logrotate warning fixed

README.md, target/start-mailserver.sh, test/mail_quotas_disabled.bats
Allow user to disable dovecot quota.
=> Feature quota optional

env-mailserver.dist
SPAMASSASSIN_SPAM_TO_INBOX=1 default for new user
=> SPAMASSASSIN_SPAM_TO_INBOX=1 default for new user

Makefile, target/bin/generate-dkim-config, target/bin/listalias, target/bin/listmailuser, target/check-for-changes.sh, target/start-mailserver.sh, test/config/postfix-master.cf, test/config/postfix-regexp.cf, test/config/postfix-virtual.cf
fix https://github.com/tomav/docker-mailserver/issues/1487
=> support comments in .cf files

test/mail_postfix_inet.bats
add test postfix inet
closes https://github.com/tomav/docker-mailserver/issues/1504
=> test postfix inet

README.md
Just a small addition for the docs.
=> hint: keyword _SCORE_ for SA_SPAM_SUBJECT

target/bin/addalias, target/bin/delalias, target/bin/listalias
Fix for https://github.com/tomav/docker-mailserver/issues/1563
=> addalias: check if two arguments are given

Dockerfile
=> Dovecot community repo info removed

CONTRIBUTING.md, target/check-for-changes.sh, target/helper_functions.sh, target/postsrsd-wrapper.sh, target/start-mailserver.sh
This is again just refactoring - adjusting, among others, what was said in polarathene/docker-mailserver#1 in the end.
=> streamlined all scripts adhering to CONTRIBUTING.md

config/user-patches.sh.dist
Comment added about modifying the supervisord configuration. See https://github.com/tomav/docker-mailserver/issues/1608
=> Comments updated

Dockerfile
Remove write access to group and others to Amavis configuration files
Fix: #1446
=> Remove write access to group and others to Amavis configuration files

README.md, target/start-mailserver.sh
I accidentally removed a branch and closed #1651. This is the same PR (without the unwanted commits for another change in another PR).
=> Documentation and Script Updates trying to fix #1647

test/test_helper/common.bash
=> Use correct filename

Makefile
Fixes #1685. This was forgotten in my last PR.
=> Correting Makefle - Fixing #1685

Dockerfile, target/dovecot/dovecot-purge.cron, target/start-mailserver.sh
Related to feature request #1697
=> Add purge cron job for Dovecot dbox format

target/postfix/main.cf, target/scripts/start-mailserver.sh
Fixes #1437
@jirislav What's your take now?:)
@casperklein just a formality, I requested a review again
=> FIX: Postfix configuration in `start-mailserver.sh` for regex

target/postfix/main.cf, target/scripts/start-mailserver.sh, test/mail_with_postgrey.bats
=> removing bl.spamcop.net for 8.0.1

README.md
This was just an outdated piece of example in the README.md
=> doc: fix service name now mailserver

README.md, target/scripts/start-mailserver.sh
=> correct application of the new SUPERVISOR_LOGLEVEL variable

.github/pull_request_template.md, CONTRIBUTING.md
There are a lot of PRs on this repository where the author provides code changes without any or only little information about the motivation and context. This PR will introduce a PR template according to the [github docs](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) as we already use for issues. My hope is that contributors will more likely use this template to provide the information and insights others need to understand the changes.
=> Add PR template

target/scripts/start-mailserver.sh
=> Follow up, style enhancement

.dockerignore
At the moment, there are lots of files in the build context, that are not necessary (basically all files that are not in the `target` directory). 
For each file/directory there should be an exception.
Instead of the "ignore the listed files/directory" approach in `.dockerignore`, I'll propose the opposite.
We should ignore all files/directorys by default, but add those explicitly who should be used in the build context.
```
*       <-- ignore all files/directorys
!target <-- except of those inside the target directory
```
=> New approach for .dockerignore

target/bin/delmailuser, target/scripts/start-mailserver.sh
This PR refactors `delmailuser` to function properly (hopefully).
Fixes #1808 (issue)
=> patching the delmailuser script to function properly (+ refactoring)

Makefile, README.md, setup.sh, target/bin/generate-dkim-config, target/bin/open-dkim, test/default_relay_host.bats, test/open_dkim.bats, test/tests.bats
Complete refactoring of `target/bin/generate-dkim-config` and outsourcing of tests.
Many of the currently present tests need a rewrite. This is indicated in the `open_dkim.bats` file with `# TODO`. @wernerfred or @casperklein I have already spent more time than I have on this. I would need your help here.
**Note**: The `Makefile`'s `test` target is currently only testing the openDKIM config for speed. This will of course be reverted before merging.
=> Provide complete refactoring of openDKIM script

Makefile
=> install_linters improved

target/scripts/check-for-changes.sh, target/scripts/helper-functions.sh, test/mail_ssl_letsencrypt.bats
Fixes what was spoken about in the @docker-mailserver/maintainers team about the `_notify` function. (Currently not locally tested, was in a hurry - CI will show if log output mismatches)
Fixes `_notify` function causing errors.
=> revamping the notify function

.github/ISSUE_TEMPLATE/bug_report.md
Add docker-compose question to issue template.
Fixes # (issue)
=> Add docker-compose question to issue template

Dockerfile, ENVIRONMENT.md, README.md, docs/content/faq.md, mailserver.env, target/scripts/startup/fixes-stack.sh, target/scripts/startup/setup-stack.sh
Fix SpamAssassin spelling/typos
=> Fix SpamAssassin spelling/typos

docs/content/contributing/coding-style.md
=> Fix spacing typo

setup.sh
To make the source more readable, color variables have been added.
=> setup.sh color variables added

.github/workflows/default_on_push.yml, .github/workflows/scheduled_builds.yml
See https://github.com/crazy-max/ghaction-docker-meta/blob/master/UPGRADE.md for upgrade notes
Closes #1882
Manual changes to dependency as upstream had a major release update
=> ci(dependency): update docker-meta action to 2.2.0

.github/workflows/deploy-docs.yml, .github/workflows/pr-docs.yml, docs/mkdocs.yml
Some minor adjustments und new features for the new documentation:
- Use version tag instead of automatic "latest" (latter one leads to different views comparing edge vs 9.1 docs)
- Add bacjk-to-top button
- Add dark theme color switch
Use `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material:7.1.0` **within** the `/docs` directory to preview the changes locally
=> docs: minor adjustments

.github/workflows/deploy-docs.yml, .github/workflows/pr-docs.yml
update mkdocs-material image to version 7.1.1
=> ci(docs): update mkdocs-material image to version 7.1.1

docs/content/config/advanced/full-text-search.md
With just an restart the volume are missing and the follow up command will fail
=> Mailserver needs recreation after adding new volume

docs/content/config/advanced/full-text-search.md
=> small docu enhancements

target/bin/listmailuser, test/tests.bats
Display an enhanced all-in-one **_./setup.sh email list_** with quotas, disk usage and aliases for each user with one single command.
The  **_./setup.sh email list_** command output looks like this : 
```
* bobby.bob@mydomain.com ( 1,9M / ~ )
[ aliases -> postmaster@mydomain.com, bob@mydomain.com ]
* johnny_john@mydomain.com ( 24K / 3G )
[ aliases -> admin@mydomain.com, johnny@mydomain.com ]
```
Implements #1892
=> Enhance setup.sh email list

docs/content/config/pop3.md
=> POP3 warning removed

docker-compose.yml
- Comments added
- ESMTP (implicit TLS) added
=> Comments added

docs/content/faq.md
The old backup script did not cover the configuration and logs.
Related: #1906
=> Backup script improved

docs/content/config/advanced/override-defaults/dovecot.md, docs/content/config/security/mail_crypt.md
Adding docs for mail_crypt
Related: #1904
=> [Documentation] mail_crypt plugin

docs/mkdocs.yml
=> docs: include mail_crypt

.github/workflows/deploy-docs.yml, .github/workflows/pr-docs.yml
update mkdocs-material to v7.1.2
Fixes # (issue)
=> docs(deps): update mkdocs-material to v7.1.2

config/fail2ban-jail.cf
Missing example added. Now all settings that are set in `target/fail2ban/jail.local` are present in `config/fail2ban-jail.cf` as examples for easy modification.
=> Missing example added

docs/content/examples/tutorials/basic-installation.md
=> Link updated

mailserver.env
Missing `ENABLE_QUOTAS` added.
=> ENABLE_QUOTAS added

.github/workflows/deploy-docs.yml, .github/workflows/pr-docs.yml
=> docs(deps): bump mkdocs-material to 7.1.3

.github/workflows/deploy-docs.yml, .github/workflows/pr-docs.yml
bump mkdocs-material to 7.1.4
Fixes # (issue)
=> docs(deps): bump mkdocs-material to 7.1.4

Dockerfile, test/mail_fail2ban.bats
This PR replaces F2B 0.10 with the latest F2B 0.11.2. This is done as Debian 11 has still no ETA. This change is easily revertible. When Debian 11 launches with the latest F2B, this PR can be reverted in a manner of minutes.
Fixes #1810
=> introduce F2B v0.11

.github/workflows/test_merge_requests.yml
ARM platforms added to test action.
If we only test against amd64, later (multiarch) build & publish action can fail.
See:
* https://github.com/docker-mailserver/docker-mailserver/pull/1965
* https://github.com/docker-mailserver/docker-mailserver/runs/2589892407?check_suite_focus=true
=> Add ARM platforms

.github/workflows/test_merge_requests.yml
I tried to add buildx to `test_merge_requests.yml`.
Fixes bad PR #1970 
Closes #1971 (added by @aendeavor)
=> Use buildx in test_merge_requests.yml

.github/workflows/test_merge_requests.yml
=> CI fix for #1972

Dockerfile
Possible arm build fix
Fixes #1965
=> ARM build fix

.github/workflows/default_on_push.yml, .github/workflows/linting.yml, .github/workflows/scheduled_builds.yml
1. The stable branch has been removed from the CI.
2. The scheduled build has been adjusted: stable --> edge.
After this PR is merged, the stable branch can be deleted.
=> Remove stable branch from CI and build edge on schedule

Dockerfile, target/scripts/start-mailserver.sh
This adds a variable to let the container know, which version is running.
Fixes #1946
=> Add version variable

.github/workflows/docs-preview-prepare.yml
Linking to netlify is a requirement for using the sponsored OSS plan
Fixes #
=> fix: add link to netlify

.github/workflows/docs-preview-deploy.yml
add recreate option for comment of doc preview. See https://github.com/docker-mailserver/docker-mailserver/pull/1921#issuecomment-845327147
Ref: https://github.com/marocchino/sticky-pull-request-comment#inputs
Fixes #
=> chore: add recreate option for comment of doc preview

setup.sh
https://github.com/docker-mailserver/docker-mailserver/issues/1982#issuecomment-846296395
Fixes #1982
=> fix email list

.github/dependabot.yml
Removed @radicand as default reviewer due to temporarily retirement.
Added area and priority label
=> chore: remove @radicand and add labels

.github/workflows/docs-preview-prepare.yml, .github/workflows/scripts/docs/build-docs.sh, docs/content/config/advanced/override-defaults/postfix.md, docs/content/config/best-practices/dkim.md, docs/content/config/best-practices/dmarc.md, docs/content/config/best-practices/spf.md, docs/content/examples/uses-cases/forward-only-mailserver-with-ldap-authentication.md
bump mkdocs-material to 7.1.6
Changelog:
Deprecated seealso admonition qualifier
Added Mongolian and updated Chinese translations
Fixed #2429: Version selector not touch-friendly on Android devices
Fixed #2703: Printed 'Initializing search' albeit ready on mobile
=>  docs(deps): bump mkdocs-material to 7.1.6

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.1.7

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.1.8

target/scripts/helper-functions.sh, target/scripts/startup/check-stack.sh, target/scripts/startup/setup-stack.sh
If `CONTAINER_IP` cannot be determined correctly, DMS is not operational.
Fixes #2042
=> Check if CONTAINER_IP could be determined

README.md, docs/content/config/advanced/auth-ldap.md
=> Follow-up #2035

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.1.9

.all-contributorsrc
Fixes this issue https://github.com/docker-mailserver/docker-mailserver/pull/2043#issuecomment-876567411
=> fix: wrong contribution type

.all-contributorsrc
Added the changes a local dev env fixed automatically (wnated to avoid local setup -.-):
```bash
wernerf@BETA:~/Repositories/docker-mailserver$ ./node_modules/.bin/all-contributors check
The JSON data was fixed!
Only absolute URLs are supported
wernerf@BETA:~/Repositories/docker-mailserver$ git diff
diff --git a/.all-contributorsrc b/.all-contributorsrc
index 612a63f..b7aa2df 100644
--- a/.all-contributorsrc
+++ b/.all-contributorsrc
@@ -17,10 +17,11 @@
}
],
"contributorsPerLine": 7,
-  "badgeTemplate": ""
+  "badgeTemplate": "",
"projectName": "docker-mailserver",
"projectOwner": "docker-mailserver",
"repoType": "github",
"repoHost": "https://github.com",
-  "skipCi": false
-}
+  "skipCi": false,
+  "commitConvention": "none"
+}
\ No newline at end of file
```
Fixes …
=> fix: add cli tool fix

.all-contributorsrc
Fixes polarathenes finding and my mistake 🤣   https://github.com/docker-mailserver/docker-mailserver/pull/1826#issuecomment-876786554
=> fix: add missing curly brace

.github/workflows/scripts/docs/build-docs.sh
bump mkdocs-material to 7.1.11
- [] New and existing unit tests pass locally with my changes
=> docs(deps): bump mkdocs-material to 7.1.11

.github/workflows/scripts/docs/build-docs.sh
bump mkdocs-material to 7.2.0
Added new search related features to mkdocs
=> docs(deps): bump mkdocs-material to 7.2.0

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.2.1

CONTRIBUTORS.md
Add a hint that we cannot add every single contributor from the past automatically.
No code changed
=> chore: add note regarding past contributions

docs/content/config/advanced/mail-forwarding/aws-ses.md
AWS SES configuration changed, Instead of just a warning pointing people to the standard relay doc, I've re-written it with some guidance on gathering the right information from AWS and getting the configuration correct.
This doc update was requested as part of the discussion on this issue:
https://github.com/docker-mailserver/docker-mailserver/issues/2091#issuecomment-888841081
(ok, this is just a doc change - most of the checklist is N/A)
=> Update AWS SES configuration doc

docs/content/examples/tutorials/blog-posts.md, docs/mkdocs.yml
=> docs: add blog posts section

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.2.3

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.2.4

target/scripts/startup/setup-stack.sh
=> Fix #2122 - only chmod when needed

docs/content/config/security/fail2ban.md, target/amavis/conf.d/62-improve_privacy_remove_headers
Fixes #2124
Fixes #2120
See: https://pullrequest-2126--dms-doc-previews.netlify.app/config/security/fail2ban/
=> Improve fail2ban docs and fix a typo

docs/content/config/advanced/mail-forwarding/relay-hosts.md, docs/content/config/pop3.md, docs/content/config/setup.sh.md, docs/content/examples/tutorials/basic-installation.md, docs/content/examples/tutorials/mailserver-behind-proxy.md, docs/content/examples/uses-cases/forward-only-mailserver-with-ldap-authentication.md
=> More typo fixes and improve ports example at POP3 docs

docs/content/contributing/documentation.md
I added documentation on how to just make it work to write and preview documentation
Preview: https://pullrequest-2129--dms-doc-previews.netlify.app/contributing/documentation/
=> Write docs on how to write docs

docs/content/examples/tutorials/blog-posts.md
Adds a new blog post that covers setting up docker-mailserver on a VPS, including but not limited to
* Considerations when selecting a VPS
* Initial configuration of docker-mailserver
* DNS setup and verification of settings
* Multiple domains
=> docs: Add a new blog post

README.md
Added changelog hint on update process.
Fixes #
=> Added changelog/version number hint on update process

Makefile, target/bin/addmailuser, target/bin/delmailuser, target/scripts/check-for-changes.sh, target/scripts/postfix-wrapper.sh, test/mail_ssl_letsencrypt.bats, test/mail_with_relays.bats, test/open_dkim.bats
Reverts docker-mailserver/docker-mailserver#2104
Per https://github.com/docker-mailserver/docker-mailserver/issues/2154
=> Revert "check-for-changes: performance improvements + wait for settle"

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.2.6

test/test_helper.bats, test/tests.bats
Just a follow up on #2177 with suggestions from @polarathene.
=> Follow up on PR for fixing tests (mostly styling)

setup.sh, setup.sh.10.2.0
Temporary fix to avoid issues like the linked one below.
PS: Additional to do for the next release: `mv setup.sh.10.2.0 setup.sh`
Fixes #2185
=> Switch to old setup.sh until release

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.2.7

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.2.8

.github/workflows/contributors.yml
This updates the contributors workflow. The current implementation does not work, because the master branch is protected and direct commits are not allowed.
For a pull request, you need a separate branch. This will be called 'contributors-update".
How it works:
1. Delete the previous `contributors-update` branch
2. Create a fresh contributors-update branch
3. Check , if `CONTRIBUTORS.md` needs to be updated
4. Provide a PR if necessary
=> Update contributor workflow

docs/content/contributing/coding-style.md
This aligns the doc with the used `__err` function from `setup.sh`
Depends on #2215
=> Update "error tracing" doc

setup.sh
This adds global colors and improves the `__err` function.
=> Small setup.sh improvements

docs/content/examples/tutorials/basic-installation.md
This is a follow-up to #2206
It is an initial pass and can probably be refined further. The main intention was to re-structure the content and enumerate steps. Besides re-arranging content order, some of it was tweaked or dropped as appropriate.
Due to the noisy PR diff not aligning well, I've split the PR into several commits to resolve the diff boundaries being misaligned. Unlike my other PRs, these have no message content, no changes worth highlighting :)
[Direct preview link - Basic Installation](https://pullrequest-2210--dms-doc-previews.netlify.app/examples/tutorials/basic-installation/).
- Should the default ENVs in the `docker-compose.yml` ENV be removed?
- `ds` and `wsproxy` software referenced has been removed. So has the Moodle software specific content at the end.
<details> …
=> docs: Revise `basic-install.md`

.github/workflows/contributors.yml, .github/workflows/default_on_push.yml, .github/workflows/linting.yml, .github/workflows/scheduled_builds.yml, .github/workflows/test_merge_requests.yml
This PR streamlines the workflow step separation with an empty line.
Fixes #
=> Streamline workflow step seperation

.github/workflows/contributors.yml
This should finally fix the contributors workflow. I've tested it successfully in a test repo.
Fixes #2224
=> Fix contributor workflow

.github/workflows/contributors.yml
To reduce the noise, this changes the scheduled runs from daily to monthly.
Fixes #
=> Run contributors workflow monthly

target/scripts/startup/fixes-stack.sh
As discussed in #2232, this prevents DMS from shutdown and shows an error message instead, when not so fatal errors occurs.
=> Relaxed error handling

mailserver.env
Fix a quote mistake introduced in #2236
Fixes #2236
=> Fix quote mistake made in #2236

.github/workflows/scripts/docs/build-docs.sh
=> docs(deps): bump mkdocs-material to 7.3.5

docs/content/config/security/fail2ban.md
Added information about running Fail2ban in rootless containers.
=> fail2ban.md: add info about running in rootless containers

target/dovecot/auth-passwdfile.inc, target/scripts/helper-functions.sh, target/scripts/startup/setup-stack.sh, test/config/dovecot-lmtp/conf.d/auth-passwdfile.conf.ext, test/config/dovecot-lmtp/conf.d/auth-passwdfile.inc
See https://github.com/docker-mailserver/docker-mailserver/issues/2091#issuecomment-943580324.
Fixes #2091
=> Add aliases to Dovecot's userdb & Adjust the passdb / userdb configuration

.github/ISSUE_TEMPLATE/bug_report.yml
Dropdown isn't appropriate. This was meant to be changed to multi-choice for opt-in.
=> github(fix): Issues form - Use checkboxes for the experience question

target/scripts/startup/setup-stack.sh
Among other things, this improves readability of `print-environment`, by sorting the ENVs.
=> improve: sort environment variables

.github/workflows/close_stale_issues.yml
Configure stale bot to exempt issues when the label `issue/not-stale` is present.
=> Add stale bot exception

.github/workflows/close_stale_issues.yml, .github/workflows/handle_stalled.yml
~~Follow up on #2300. Sorry for the extra work.~~
Revises the workflow for stale issues **and** PRs. One can now add the label `bot/ignore` to issues and PRs to indicate that the stale action should ignore this object. Furthermore, configuration for PRs was added explictly.
=> Revise workflow for stalled objects

.github/workflows/handle_stalled.yml, README.md, target/scripts/startup/setup-stack.sh
This is a housekeeping PR. This PR does not and must not contain changes that affect functionality!
This PR does not block the release of `v10.3.0`. **Feel free to add your own small additions** if you think a section could use a bit of cleanup (nothing big, just small things).
If this is merged before `v10.3.0`, please add the corresponding milestone.
=> Housekeeping

target/scripts/helper-functions.sh, target/scripts/helpers/relay.sh
After a second view on the function, I think this makes more sense.
=> Rename function and adjust comment

.github/workflows/scripts/docs/update-versions-json.sh, docs/content/contributing/coding-style.md, target/bin/addmailuser, target/bin/delquota, target/bin/fail2ban, target/bin/listmailuser, target/bin/setquota, target/scripts/helper-functions.sh, target/scripts/startup/setup-stack.sh, test/mail_fail2ban.bats, test/mail_postscreen.bats, test/security_tls_cipherlists.bats
This PR remove quotes in if-statements, to meet the projects style guidelines 
Fixes #
=> Remove quotes to meet style guidelines 

Dockerfile
Fixes an issue concerning a package missing on Debian 11. This issue may justify `v10.4.1` - please add your opinions on that.
Fixes #2340
=> added `libldap-common` to packages in Dockerfile

test/sedfile.bats
Add tests for the `sedfile` wrapper.
=> Add tests for sedfile wrapper

.github/workflows/scripts/docs/build-docs.sh
bump mkdocs-material to v8.1.7
=> docs(deps): bump mkdocs-material to v8.1.7

target/bin/listmailuser
Partial error message fix for #2379 (see <https://github.com/docker-mailserver/docker-mailserver/issues/2379#issuecomment-1022297429>)
=> Fixed non-number-argument in `listmailuser`

docs/content/config/advanced/maintenance/update-and-cleanup.md
it can get a a hassle -> it can become a hassle
=> Fixed typo in update-and-cleanup.md.

README.md, docs/content/config/security/ssl.md
Follow up on #2383 and update of the `README.md`. Please refer to the commit messages for further information on the "why".
=> `README.md` and Documentation Update

docs/content/config/environment.md, mailserver.env
Better description for `LOGROTATE_INTERVAL`.
Fixes #2462
=> docs: Enhance logrotate description

docs/content/config/security/fail2ban.md
=> docs: Update fail2ban.md

Makefile
=> Makefile: Remove backup/restore of obsolete config directory

docs/content/config/environment.md, docs/content/contributing/coding-style.md, mailserver.env, target/bin/print-environment, target/scripts/helpers/accounts.sh, target/scripts/helpers/aliases.sh, target/scripts/helpers/error.sh, target/scripts/helpers/lock.sh, target/scripts/helpers/log.sh, target/scripts/helpers/relay.sh, target/scripts/helpers/ssl.sh, target/scripts/start-mailserver.sh, target/scripts/startup/check-stack.sh, target/scripts/startup/daemons-stack.sh, target/scripts/startup/fixes-stack.sh, target/scripts/startup/misc-stack.sh, target/scripts/startup/setup-stack.sh, test/mail_changedetector.bats, test/mail_ssl_letsencrypt.bats
This PR introduces a new `_log` function. As a successor to the closed #2486, this PR is still big, but tighter and only brings
1. the new `_log` function
2. updated log levels for most scripts
3. necessary documentation updates
=> scripts: new log

target/scripts/start-mailserver.sh
With `SUPERVISOR_LOGLEVEL=info`, [supervisord is restarted](https://github.com/docker-mailserver/docker-mailserver/blob/d8d4b6a18914298b260d32244eb351d565f7a7d5/target/scripts/startup/setup-stack.sh#L12-L22) on startup to activate the new loglevel. Restarting supervisord, will also restart `start-mailserver.sh`.
This is how it looks like on container start: 
```
[ TASKLOG ]  Welcome to docker-mailserver 10.5.0
[ TASKLOG ]  Initializing setup
[ TASKLOG ]  Checking configuration
[ TASKLOG ]  Configuring mail server
Restarted supervisord
2022-03-20 22:35:19,944 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
2022-03-20 22:35:19,944 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
2022-03-20 22:35:19,944 INFO Set uid to user 0 …
```
=> Restart supervisord early

target/scripts/helpers/error.sh, target/scripts/helpers/log.sh, target/scripts/helpers/utils.sh, target/scripts/startup/setup-stack.sh, target/scripts/update-check.sh
Please see the commit messages. This is a housekeeping PR which includes several small changes.
=> scripts: refactoring & miscellaneous small changes

.github/workflows/scripts/docs/build-docs.sh
https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.8
=> docs(deps): bump mkdocs-material to v8.2.8

target/scripts/startup/setup-stack.sh
=> fix: typo in setup-stack.sh

target/scripts/startup/setup-stack.sh
=> chore: (setup-stack.sh) Fix a small typo

.github/workflows/scripts/docs/build-docs.sh
Update to the latest version of mkdocs material: https://github.com/squidfunk/mkdocs-material/releases
=> docs(deps): bump mkdocs-material to v8.3.5

target/scripts/check-for-changes.sh, test/mail_ssl_letsencrypt.bats
Debug message for starting changedetector has a typo
Fixes #
=> fix: typo in changedetector ready message

test/test_helper/common.bash
=> tests: Fix typo in common.bash

docs/content/config/advanced/kubernetes.md, target/scripts/helpers/dns.sh
See https://github.com/docker-mailserver/docker-mailserver/issues/2094#issuecomment-1194428616
=> docs: update and improve K8s documentation

target/scripts/startup/setup-stack.sh
When waiting on an account to be added to `postfix-accounts.cf`, Dovecot account creation during the startup process had already run.
Startup continued without properly creating the mail account for Dovecot. Methods like `setup email list` (_with `ENABLE_QUOTAS=1`_) would fail. `changedetector` service was required to be triggered to re-create Dovecot users.
- Wrapped the logic for wait + shutdown into a function call.
- Moved `_create_accounts()` to bottom of the setup function.
=> fix: `_create_accounts()` should run after waiting

.github/workflows/linting.yml, test/linting/lint.sh
The new version uses our `log.sh` helper to simplify logging
significantly. Moreover, the script was adjusted to the current style
and the GitHub workflow was streamlined. The workflow is ot providing
the version anymore (which was useless anyway), and has been compacted.
=> scripts: revised linting script

target/scripts/helpers/log.sh
This PR prepares for other PRs that use the newly introduced helper
functions. The `_log` function itself was adjusted a bit to be shorter
and more concise.
Follow up of #2752 taking care of `log.sh`.
=> scripts: improve `helpers/log.sh`

target/postfix/main.cf
As discussed in the below mentioned issue this adds the `reject_unknown_client_hostname` option.
Reference: http://www.postfix.org/postconf.5.html#reject_unknown_client_hostname
Fixes #2650
=> Add `reject_unknown_client_hostname` to main.cf

docs/content/config/advanced/podman.md
=> docs: fix typo in podman.md

.github/workflows/generic_publish.yml, Dockerfile, Makefile, target/scripts/build/packages.sh, target/scripts/helpers/log.sh, test/linting/.hadolint.yaml
Enhances `Dockerfile` by
1. outsourcing packages installation
2. using `COPY --link` for ClamAV anti-virus bytecode
I am not sure whether using `DOCKER_BUILDKIT` is a breaking change. Technically not, because the build process is not taken into account for SemVer, right?
PS: Sorry for the noise in the commit message. Accidentally commit the wrong files first with wrong description.
PPS: Note, this reverts #1965 implicitly. That is okay, since Debian 11 now ships with the latest version of Fail2Ban
=> ci: enhance build process

target/scripts/build/packages.sh
=> #2755 follow up; bring back fail2ban package installation

test/mail_fail2ban.bats
1. Existing tests improved / fixed
2. One new test added
=> ci: fix/improve Fail2Ban tests

CHANGELOG.md, target/scripts/startup/setup-stack.sh
=> Fix: Run Amavis cron job only when Amavis is enabled

.gitignore, CHANGELOG.md, Makefile, test/config/templates/dovecot-masters.cf, test/config/templates/postfix-accounts.cf
Got some inspiration from comments in #2822 and decided to clean up the whole `Makefile`.
=> build: cleaned up Makefile

CHANGELOG.md, target/bin/setup
This PR fixes "unbound variable" errors, like this:
```bash
./setup.sh email
/usr/local/bin/setup: line 113: 2: unbound variable
```
=> setup: fix unbound variable error

CHANGELOG.md, target/scripts/startup/misc-stack.sh
=> Fix: Make fetchmail data persistant

CHANGELOG.md, target/bin/setup
There were some `$2` left, that were not correctly handled when empty.
This PR fixes this and also simplify/streamline the code a bit.
=> Follow up for #2849

CHANGELOG.md, target/bin/addalias, target/bin/adddovecotmasteruser, target/bin/addmailuser, target/bin/addrelayhost, target/bin/addsaslpassword, target/bin/delalias, target/bin/deldovecotmasteruser, target/bin/delmailuser, target/bin/delquota, target/bin/excluderelaydomain, target/bin/open-dkim, target/bin/setquota, target/bin/updatedovecotmasteruser, target/bin/updatemailuser, target/scripts/helpers/utils.sh, test.sh
When parameters are missing (alias destination in that case), this error is shown:
```bash
./setup.sh alias add postmaster@office
/usr/local/bin/setup: line 119: 2: unbound variable
--- UNCHECKED ERROR
- script    = ./setup.sh
- function  = _main
- command   = ${CRI} exec "${USE_TTY}" "${CONTAINER_NAME}" setup "${@}"
- line      = 229
- exit code = 1
This should not have happened. Please file a bug report.
```
This PR solves that, by showing the usage instead.
=> scripts: Improve error handling, when parameters are missing

.github/ISSUE_TEMPLATE/bug_report.yml
There can be differences/known problems between Linux distributions and versions.
This PR adds `OS version` to the issue template.
=> Add OS version to issue template

.github/ISSUE_TEMPLATE/bug_report.yml
Reaction to form feedback given in #2889.
=> improvement: issue form

target/opendmarc/opendmarc.conf
=> Change OpenDMARC policy default to reject

target/scripts/helpers/relay.sh
Signed-off-by: René Plötz <reneploetz@users.noreply.github.com>
Fixes #2964
=> Fix condition for relay hosts when using only a provided file

target/scripts/build/packages.sh
This PR adds the `ping` and `dig` commands to the image, which are useful for debugging.
Fixes #2987
=> Add tools (ping & dig) to the image

docs/content/introduction.md, target/bin/sedfile, test/config/dovecot-lmtp/conf.d/90-quota.conf, test/config/dovecot-lmtp/conf.d/auth-system.conf.ext, test/tests/serial/mail_lmtp_ip.bats, test/tests/serial/test_helper.bats
=> Fix several typos

docs/content/faq.md
Documents the findings from: #2948
https://pullrequest-2949--dms-doc-previews.netlify.app/faq/#how-can-i-delete-all-the-emails-for-a-specific-user
=> docs: FAQ - Add note for `devnull` alias gotcha when using a catchall rule

Makefile
This commit is pulled out of https://github.com/docker-mailserver/docker-mailserver/pull/3012 and is [explained in this PR comment](https://github.com/docker-mailserver/docker-mailserver/pull/2857#discussion_r1013767738):
> it is **not** defined as a target like `ALWAYS_RUN:`, but just as `.PHONY: ALWAYS_RUN` :) This suffices to tell `make` to always run the target.
`.PHONY: ALWAYS_RUN` already exists in the Makefile. This PR just applies it more broadly as decided by @georglauterbach 
---
**NOTE:** From what I have seen in [Makefile docs for `.PHONY`](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) this seems a bit of a different approach?
The targets seem to get appended to the `.PHONY:` target, rather than this usage of prefixing target values with `ALWAYS_RUN`? …
=> chore(Makefile): Ensure targets are always run

test/tests/serial/mail_privacy.bats
Extracts out the test refactoring of `mail_privacy.bats` from https://github.com/docker-mailserver/docker-mailserver/pull/3012
- Author of commit is actually @georglauterbach who requested I extract it from their PR.
- Should not be merged until that referenced PR is as it depends on changes it introduces.
=> tests(refactor): Migrate `mail_privacy.bats` to new format and helpers

test/helper/common.bash, test/test-files/email-templates/smtp-only.txt, test/tests/serial/mail_quotas_disabled.bats, test/tests/serial/mail_smtponly.bats, test/tests/serial/mail_special_use_folders.bats, test/tests/serial/mail_time.bats, test/tests/serial/permit_docker.bats
More rewrites. Note: `mail_smtponly.bats` seems to be really broken. I added TODOs.
=> tests: refactor 4 more tests

.github/workflows/contributors.yml, .github/workflows/docs-preview-deploy.yml, .github/workflows/docs-preview-prepare.yml, .github/workflows/docs-production-deploy.yml, .github/workflows/generic_build.yml, .github/workflows/generic_publish.yml, .github/workflows/generic_test.yml, .github/workflows/handle_stalled.yml, .github/workflows/linting.yml
I updated from Ubuntu 20.04 to Ubuntu 22.04 which should be fairly stable by now. Moreover, I adjusted the `ubuntu-latest` images to also use `ubuntu-22.04`, which is the same for now, but I like uniformity and I think pinning is a good idea.
=> ci: update & streamline GH Actions runner images

docs/content/config/security/rspamd.md, target/rspamd/local.d/milter_headers.conf, target/scripts/startup/misc-stack.sh, target/scripts/startup/setup-stack.sh, test/tests/parallel/set1/spam_virus/rspamd.bats
A small follow-up for things I noticed while getting Rspamd to work today. I should have thought about the permissions issue before, sorry. The disasbled modules were adjusted as well.
I can report though that Rspamd works nicely on my setup now :D
UPDATE: Correction; it works like a charm! It handles DKIM signing now (RSA+ED25519) & DNSBLs properly.
=> rspamd: follow-up of #3016

test/helper/common.bash, test/tests/parallel/set1/spam_virus/amavis.bats, test/tests/serial/mail_pop3.bats, test/tests/serial/mail_with_imap.bats, test/tests/serial/mail_with_relays.bats, test/tests/serial/no_container.bats
Refactors more tests so that they can be run in parallel.
=> tests: refactor POP3, IMAP (actually SASLauthd + RIMAP) & relay

mailserver.env
Fixes https://github.com/docker-mailserver/docker-mailserver/issues/3028#issuecomment-1405206243
=> Better default value for SA_KILL variable

target/postfix/main.cf, target/scripts/startup/setup-stack.sh, test/tests/parallel/set1/spam_virus/amavis.bats
Fixes <https://github.com/docker-mailserver/docker-mailserver/pull/3046#issuecomment-1423718811>
I also added a test that verifies the Amavis configuration when Amavis is enabled and when it is disabled.
=> setup: improve Amavis setup routine

test/helper/sending.bash, test/tests/parallel/set1/dovecot/dovecot_sieve.bats, test/tests/parallel/set1/dovecot/special_use_folders.bats, test/tests/parallel/set1/spam_virus/clamav.bats, test/tests/parallel/set1/spam_virus/disabled_clamav_spamassassin.bats, test/tests/parallel/set1/spam_virus/spam_junk_folder.bats, test/tests/parallel/set3/container_configuration/hostname.bats, test/tests/parallel/set3/mta/lmtp_ip.bats, test/tests/parallel/set3/mta/smtp_delivery.bats, test/tests/parallel/set3/mta/smtponly.bats, test/tests/serial/sedfile.bats
Obvious. Review commit by commit should be easy.
=> ci: refactored `sedfile` & used `_send_mail` where possible

README.md, docs/content/config/security/rspamd.md
Title says it all. See #3003 for (initial) reference. When adjusting this PR, commit immediately :D
=> docs: add docs about Abusix integration into Rspamd

.github/workflows/generic_vulnerability-scan, .github/workflows/generic_vulnerability-scan.yml, .github/workflows/scheduled_builds.yml, SECURITY.md
Title says it all, commits descriptions have proper comments :)
=> ci/docs: add vulnerability scanning workflow & security policy

test/helper/common.bash, test/helper/sending.bash, test/tests/parallel/set1/dovecot/dovecot_sieve.bats, test/tests/parallel/set1/dovecot/mailbox_format_dbox.bats, test/tests/parallel/set1/dovecot/special_use_folders.bats, test/tests/parallel/set1/spam_virus/amavis.bats, test/tests/parallel/set1/spam_virus/clamav.bats, test/tests/parallel/set1/spam_virus/disabled_clamav_spamassassin.bats, test/tests/parallel/set1/spam_virus/fail2ban.bats, test/tests/parallel/set1/spam_virus/postscreen.bats, test/tests/parallel/set1/spam_virus/rspamd.bats, test/tests/parallel/set1/spam_virus/spam_junk_folder.bats, test/tests/parallel/set3/container_configuration/hostname.bats, test/tests/parallel/set3/mta/lmtp_ip.bats, test/tests/parallel/set3/mta/smtp_delivery.bats, test/tests/parallel/set3/mta/smtponly.bats, test/tests/serial/mail_pop3.bats, test/tests/serial/mail_with_imap.bats, test/tests/serial/tests.bats
The function now handles IP, Port and more path names, as well as extra options you can supply to `nc`.
=> tests: improve `_send_email`

docs/content/config/security/rspamd.md
Not a blocker for v12.0.0, but it'd be nice if we can get it in. Since this is a _pure docs_ PR, should be a no-issue.
@polarathene please go ahead and apply your feedback immediately if you want to change something :) I will enable auto-merge, so as soon as you approve, this will be merged.
=> docs: improve Rspamd docs

target/scripts/startup/setup.d/mail_state.sh
Small change: Replace hard-coded path with variable.
=> DRY: Replace path with variable in mail_state.sh

target/scripts/startup/setup.d/mail_state.sh
=> fix: regression introduced in #3153

target/scripts/helpers/accounts.sh, target/scripts/helpers/dns.sh, target/scripts/helpers/error.sh, target/scripts/helpers/ssl.sh, target/scripts/helpers/utils.sh, target/scripts/start-mailserver.sh, target/scripts/startup/check-stack.sh, target/scripts/startup/daemons-stack.sh, target/scripts/startup/setup-stack.sh, target/scripts/startup/setup.d/dovecot.sh, target/scripts/startup/setup.d/networking.sh
`_shutdown` wil now wait for Supervisord by default. Added option to exit immedaitely though. Adjusted panic handlers; made them more coherent and added one more panic type.
Fixes #3140
=> scripts: improve panic helpers

target/scripts/helpers/ssl.sh
Correct self-signed SSL cert error message to report another possibly missing file. This error confused me for a little while.
=> Add SS_CA_CERT to self-signed cert error message

Dockerfile, target/scripts/build/packages.sh, target/scripts/startup/setup.d/mail_state.sh, target/scripts/startup/setup.d/postfix.sh
This PR refactores the SRS setup, while fixing https://github.com/docker-mailserver/docker-mailserver/pull/3144#discussion_r1125664704
=> fix: SRS setup

docs/content/config/best-practices/spf.md
seems like a typo: a ip -> an ip
Fixes #
=> doc: a ip -> an ip

versions.json
Add `latest` to `versions.json` so that `latest` shows up in the version selector in the docs. This is a ancillary PR to a main one automating managing a new `latest` symlink in the docs that points to the latest stable release.
=> ci(docs): Add `latest` version to `versions.json`

docs/content/config/environment.md, target/scripts/startup/variables-stack.sh, test/tests/parallel/set1/spam_virus/amavis.bats
Update forgotten SA_KILL values from #3058.
=> Update SA_KILL values; follow up to  #3058

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/question.yml
Misc spelling fixes and resolved imprecise statements. Shortened the bug report introduction a bit further and added a statement about being precise to all templates.
=> gh/CI: follow-up to #3225

docs/content/usage.md
This is self-explanatory. This PR may be merged at any time.
=> docs: add a note about TLS to "Usage" page

Dockerfile
Tiny change to make fail2ban's log persistent.
=> misc: make Fail2Ban log persistent

.github/ISSUE_TEMPLATE/bug_report.yml
I updated the labels, so I update the issue template as well
=> ci: update `bug_report.yml`

target/scripts/startup/setup.d/dmarc_dkim_spf.sh, target/scripts/startup/setup.d/security/misc.sh
Really minor script enhancements.
=> scripts: misc improvements

docs/content/config/environment.md, docs/content/config/security/rspamd.md, target/scripts/startup/setup.d/security/rspamd.sh
Removes warnigs about Rspamd being WIP / unstable.
Related to #3249
=> Rspamd: remove WIP warnings

docs/content/config/security/fail2ban.md, docs/content/config/security/rspamd.md, docs/content/faq.md, docs/content/usage.md
Also added explanation for what `docker-data/dms/config/` actually is. The links used before pointed to a wrong location in the FAQ.
=> docs: update F2B docs & bind mount links

target/scripts/helpers/utils.sh
See <https://github.com/docker-mailserver/docker-mailserver/pull/3285#issuecomment-1521706729>.
=> scripts: remove unnecessary `return 0` statements

config-examples/fail2ban-jail.cf, docs/content/config/security/fail2ban.md, target/fail2ban/jail.local
See <https://github.com/docker-mailserver/docker-mailserver/issues/3256#issuecomment-1511188760>.
Closes #3256
=> F2B: update F2B after discussion in #3256

.github/workflows/contributors.yml
After monitoring the latest run, it of course failed. I hence invested more time... I hope this change fixes the issue.
=> ci: fixed contributors workflow

docs/content/config/security/rspamd.md
=> docs: update Rspamd docs (small improvement)

docs/content/config/best-practices/dkim_dmarc_spf.md, docs/content/config/environment.md, mailserver.env
=> docs: fix spelling mistakes

target/scripts/startup/setup.d/dmarc_dkim_spf.sh
=> Fix "OpenDMARC"

.github/ISSUE_TEMPLATE/bug_report.yml, docs/content/contributing/issues-and-pull-requests.md
This PR eases using the bug report template. It had indeed become a bit heavy. @polarathene if you have any suggestions, you can apply them immediately without me having a second look. You can then go ahead and merge this straight away :)
=> ci: slim down bug report template

docs/content/usage.md
See title 😎 
BTW: IIRC there was in the docs a link/button, to easily change/contribute to our docs. Is that gone? This time I went to this repo and looked for `usage.md`, which wasn't as comfortable as before.
=> docs: Fix URL

docs/content/contributing/general.md
This PR adds another method of contributing to the docs.
=> docs: Update contributing

.github/workflows/scheduled_builds.yml
Just found that our scheduled build did not suceed for a long time 🤣 This should fix it..
Fixes #
=> ci: fix scheduled build permissions

test/linting/lint.sh, test/tests/parallel/set1/spam_virus/amavis.bats, test/tests/parallel/set1/spam_virus/postgrey_enabled.bats, test/tests/parallel/set1/spam_virus/postscreen.bats, test/tests/parallel/set1/spam_virus/rspamd_dkim.bats, test/tests/parallel/set1/spam_virus/rspamd_full.bats, test/tests/parallel/set3/container_configuration/hostname.bats, test/tests/parallel/set3/container_configuration/process_check_restart.bats, test/tests/parallel/set3/scripts/helper_functions.bats, test/tests/serial/test_helper.bats, test/tests/serial/tests.bats
Make `lint.sh` lint BATS tests again.
=> ci: fix ShellCheck linting for BATS tests

setup.sh, target/bin/delmailuser, target/bin/listalias, target/bin/listdovecotmasteruser, target/bin/listmailuser, target/bin/open-dkim, target/bin/rspamd-dkim, target/scripts/check-for-changes.sh, target/scripts/helpers/accounts.sh, target/scripts/helpers/lock.sh, target/scripts/helpers/postfix.sh, target/scripts/helpers/relay.sh, target/scripts/helpers/utils.sh, target/scripts/startup/setup.d/fetchmail.sh, target/scripts/startup/setup.d/networking.sh, target/scripts/startup/setup.d/postfix.sh, target/scripts/startup/setup.d/security/rspamd.sh, target/scripts/update-check.sh
Change 'while' style from
```bash
while true
do
do_something
done
```
to
```bash
while true; do
do_something
done
```
This new style aligns with the style already used in our tests.
Planned follow up style changes:
- until
=>  Change 'while' style

target/bin/debug-getmail, target/bin/deldovecotmasteruser, target/bin/delmailuser, target/bin/fail2ban, target/bin/getmail-cron, target/scripts/helpers/change-detection.sh, target/scripts/helpers/network.sh, target/scripts/startup/check-stack.sh, target/scripts/startup/daemons-stack.sh, target/scripts/startup/setup-stack.sh, target/scripts/startup/setup.d/dovecot.sh, target/scripts/startup/setup.d/fetchmail.sh, target/scripts/startup/setup.d/getmail.sh, target/scripts/startup/setup.d/ldap.sh, target/scripts/startup/setup.d/mail_state.sh, target/scripts/startup/setup.d/networking.sh, target/scripts/startup/setup.d/security/misc.sh, target/scripts/startup/setup.d/security/rspamd.sh, target/scripts/startup/variables-stack.sh, test/helper/setup.bash, test/helper/tls.bash, test/tests/parallel/set1/spam_virus/fail2ban.bats, test/tests/parallel/set1/spam_virus/rspamd_dkim.bats, test/tests/parallel/set1/spam_virus/rspamd_full.bats, test/tests/parallel/set1/spam_virus/rspamd_partly.bats, test/tests/parallel/set3/container_configuration/process_check_restart.bats
Change 'for' style from
```bash
for i in 1 2 3
do
do_something
done
}
```
to
```bash
for i in 1 2 3; do
do_something
done
```
=> Change 'for' style

Dockerfile, test/linting/lint.sh
=> Bump hadolint/eclint version

Dockerfile, docs/content/config/advanced/mail-sieve.md, docs/content/faq.md, target/scripts/start-mailserver.sh
Review commit by commit.
PS: No, I don't have the time to do this in separate PRs
Fixes #3355 
Fixes #2545
Partly closes #3289
=> misc: remaining v13 todos

Dockerfile
Not sure if this is worth adding any label or milestone for. Minor change that I forgot to submit before the PR for it was merged :sweat_smile:
=> chore: Revise Dockerfile comment on COPY bug

Dockerfile, target/scripts/build/compile.sh, target/scripts/build/packages.sh
compile fts_xapian from src to match dovecot abi version
Fixes #3247
=> Dovecot: compile `fts_xapian` from source to match Dovecot ABI

.github/ISSUE_TEMPLATE/bug_report.yml, docs/content/config/debugging.md
- Compatibility troubleshooting advice taken from: https://github.com/docker-mailserver/docker-mailserver/pull/3244#discussion_r1162337652
- Preliminary Checks section moves two checklist items from bug report template: https://github.com/docker-mailserver/docker-mailserver/pull/3381#discussion_r1212454225
=> docs: Add compatibility section to debugging page

target/bin/rspamd-dkim
fix minor spelling issues in rspamd-dkim
=> fix spelling issues in rspamd-dkim

config-examples/dovecot.cf, docs/content/config/advanced/kubernetes.md, docs/content/config/advanced/mail-fetchmail.md, docs/content/config/advanced/mail-forwarding/aws-ses.md, docs/content/config/advanced/mail-sieve.md, docs/content/config/debugging.md, docs/content/config/environment.md, docs/content/config/security/ssl.md, docs/content/faq.md, docs/content/introduction.md, mailserver.env
=> docs: Fix typos

docs/content/usage.md
Adding internet.nl mail tester to the testing links on the usage page. This testing services gives users in-depth analysis of their mail server, connectivity, DKIM/SPF/DMARC records and DNS.
- [] I have commented my code, particularly in hard-to-understand areas
=> Adding tool to testing links

test/linting/.ecrc.json, test/linting/lint.sh, test/test-files/email-templates/send-privacy-email.txt, test/test-files/ssl/example.test/README.md
The [`2.7.2` release](https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/2.7.2) contains [a bugfix for charset detection](https://github.com/docker-mailserver/docker-mailserver/pull/3566#issuecomment-1747176965), resolving a linting bug affecting our test-files directory.
=> ci: Update `eclint` to `2.7.2`

docs/content/config/debugging.md, docs/content/config/security/rspamd.md
1. I added information on the recently adopted `less` / `nano`
2. I added information about `/var/log/mail/`
I think users sometimes lack the information on where to find our logs and how to work with them. This PR should help clarify the issue even further.
=> docs: improve docs about how to work with logs

.github/workflows/contributors.yml, CONTRIBUTORS.md
With the latest `contributors.yml` workflow, everyone is included in the list of contributors. Hence, we do not need the extra section anymore.
=> contributors: fix spelling & remove dedicated AllContributors section

docs/content/config/debugging.md
=> docs: correct path for logs in docs

docs/content/config/debugging.md
The problem comes up frequently enough in issues. The docs addition provides a link to a recent macOS bug report where I provided the usual suggestions, while the reporter later chimed in with what worked for them 👍
=> docs: Debugging - Add macOS suggestion to use `gRPC FUSE`

docs/content/config/advanced/mail-sieve.md
Caught by @IIIlllIIllIIIll thanks!: https://github.com/docker-mailserver/docker-mailserver/pull/3641#issuecomment-1818183874
=> docs: Dovecot Sieve - Adjust to new path for user home folder

docs/content/config/debugging.md
Previously suggested in Aug 2023: https://github.com/docker-mailserver/docker-mailserver/issues/3482
@georglauterbach is managing the v13 release, so I've set the milestone to v13.1 in case this misses the v13 release window.
---
Presently there is a fairly clear and early mention of this advice in the docs:
https://github.com/docker-mailserver/docker-mailserver/blob/2a716cf4a4e0eec9ec12d99fcc6e9c5e625a63f8/docs/content/usage.md?plain=1#L120-L126
This PR just adds a more verbose variant to explain the problem better and place it in a location users are more likely to land at when troubleshooting (_because who reads docs in full these days?_ 😆 ).
---
List of `--force-recreate` being used / suggested to troubleshoot (_not filtered to when it was the solution_):
- **Discussions:**
- …
=> docs: Debugging - Correctly starting DMS

CHANGELOG.md, target/scripts/build/packages.sh
=> Fix jaq: Download platform specific binary

mailserver.env
=> fix(typo): comment on mailserver.env

target/scripts/startup/check-stack.sh
Improved guidance.
Doesn't seem to warrant noise to the changelog?
=> chore: Revise improper restart message

docs/content/assets/css/customizations.css
Small style change to make the page group titles on the left nav sidebar more prominent.
=> docs: UX Improvement - Better distinguish side nav page categories

.github/workflows/docs-preview-deploy.yml
Follow-up to https://github.com/docker-mailserver/docker-mailserver/pull/3838 thanks to @georglauterbach for spotting the failure https://github.com/docker-mailserver/docker-mailserver/pull/3820#issuecomment-1913186496
=> ci(fix): `docs-preview-deploy.yml` - Use the correct setting names

docs/content/contributing/tests.md, target/postfix/main.cf
Since 47f8d50bebaa0b1f1cb85d45c1d9210d9ce80a49 tests now use the file command, so it is added as a prerequisite in the documentation. (And also fixed a typo in main.cf)
=> docs: Add new local dependency (`file`) for running tests

docs/content/config/best-practices/dkim_dmarc_spf.md
Corrected a minor spelling mistake in the docs.
=> Minor spelling correction

target/bin/rspamd-dkim, target/scripts/helpers/rspamd.sh
=> Rspamd: improve DKIM key generation

CHANGELOG.md, Dockerfile
The previous link https://postgrey.schweikert.ch/pub/postgrey_whitelist_clients was updated in 2022, but it seems that the author updates the repository on Github https://github.com/schweikert/postgrey more frequently.
=> chore: Source Postgrey `whitelist_clients` config from Github

target/bin/open-dkim
=> fix(`setup`): `open-dkim` log for conflicting implementations

CHANGELOG.md, target/scripts/startup/setup.d/security/misc.sh
Follow up to https://github.com/docker-mailserver/docker-mailserver/pull/3907
=> Fail2Ban: Align logrotate count & interval

README.md
=> docs: Update links for account management in `README.md`

CHANGELOG.md, target/scripts/start-mailserver.sh, target/scripts/startup/check-stack.sh, target/scripts/startup/setup-stack.sh
Described [here](https://github.com/docker-mailserver/docker-mailserver/issues/3886#issuecomment-1943416349).
Not covered by this PR:
- Documentation
- Additional test(s)
Fixes #3886
=> Better support regular container restarts

CHANGELOG.md, target/scripts/startup/setup.d/security/misc.sh
Fixes #3569
@georglauterbach Please check the two commits. Which one do you prefer? Related: https://github.com/docker-mailserver/docker-mailserver/issues/3323#issuecomment-1545802746
=>  Enable spamassassin only, when amavis is enabled too.

docs/content/config/advanced/kubernetes.md
=> docs: add note about custom F2B setup with PROXY protocol

docs/content/config/security/rspamd.md, docs/content/faq.md
@polarathene please adjust as you like; I'll enable auto-merge to save myself some time :)
=> docs: add FAQ entry about DNS servers and drop feature request on custom DNS servers for Rspamd

docs/content/config/advanced/auth-ldap.md, docs/content/examples/use-cases/auth-lua.md
=> chore: remove repetitive words

docs/content/config/security/ssl.md
Doc updates related to activity from these interactions:
- https://github.com/docker-mailserver/docker-mailserver/pull/3485 (_Caddy file revisions and warning_)
- https://github.com/docker-mailserver/docker-mailserver/issues/3931#issuecomment-1987382299 (_Removal of Caddy JSON_)
- https://github.com/docker-mailserver/docker-mailserver/issues/3955#issuecomment-2027882633 (_Cert troubleshooting gotcha_)
The diff generated isn't too helpful, especially with the removal of `v2` from Caddy and Traefik headers 😅 (_both have had v2 variants out long enough that this is redundant information now_). Revised the content a bit, notably for Traefik removing internal details on precedence, `SSL_DOMAIN` and `DOMAINNAME` are not ENV the user should be setting.
=> docs: Updates to TLS page (Caddy, testing, etc)

docs/content/config/advanced/mail-getmail.md
=> Update mail-getmail.md : fix website URL

docs/content/config/advanced/kubernetes.md
Added the missing "s" on "submissions", otherwise this error comes up: The Service "mailserver" is invalid: spec.ports[2].name: Duplicate value: "submission"
=> Update typo in kubernetes.md

test/linting/.ecrc.json
Fixes <https://github.com/docker-mailserver/docker-mailserver/actions/runs/9104797245/job/25029285883?pr=4018>
Blocks #4018
Blocks #4019
=> linting: update `.ecrc.json` to exclude `CONTRIBUTORS.md`

docs/content/config/best-practices/dkim_dmarc_spf.md
improve docs about "ENABLE_POLICYD_SPF"
=> docs: Add tip for disabling the default SPF service

CHANGELOG.md, Dockerfile, target/scripts/build/compile.sh
I wanted to get this into v14.0.0 because I want to start using Xapian myself.
**Auto-merge is enabled for this PR!**
=> update: Dovecot FTS Xapian from 1.5.5 to 1.7.12

CHANGELOG.md, target/scripts/helpers/database/manage/postfix-accounts.sh, test/tests/parallel/set3/mta/account_management.bats
This change checks accounts on uppercase letters and performs a transformation so that all accounts only consist of lowercase letters.
**Auto-merge is enabled for this PR!**
Fixes #4011
=> scripts: perform additional checks when updating/adding/deletting accounts

docs/content/config/security/rspamd.md
=> Abusix docs links update.

mailserver.env
Ref: https://github.com/docker-mailserver/docker-mailserver/issues/4048#issuecomment-2152353632
Fixes #4048
=> docs: `mailserver.env` improve description for `SPAM_SUBJECT`

docs/content/examples/tutorials/Dovecot-solr.md, docs/content/examples/tutorials/dovecot-solr.md, docs/mkdocs.yml
Tutorial on using standard apache solr container with dovecot provided solr schema as dovecot fts backend in dms.
ref: https://github.com/docker-mailserver/docker-mailserver/pull/4025
=> docs: Add tutorial for configuring Dovecot FTS with Solr

CHANGELOG.md, target/bin/adddovecotmasteruser, target/bin/addmailuser, target/bin/addsaslpassword, target/bin/updatedovecotmasteruser, target/bin/updatemailuser, target/scripts/helpers/database/manage/postfix-accounts.sh
Fixes: #4071 (typo when entering the password)
=> feat: Add password confirmation

docs/content/config/best-practices/dkim_dmarc_spf.md
A recent discussion about this topic [suggested including a mention about this in our docs](https://github.com/orgs/docker-mailserver/discussions/4068#discussioncomment-9785082).
I'm not 100% sure I'm correct about this advice, so if you know any better please correct me 👍
=> docs: Add info regarding DKIM key rotation and non-expiry

CHANGELOG.md, target/scripts/build/packages.sh
Simple version bump.
This also enables me to use `index()`, which is required by my custom F2B / Kubernetes setup 😆
=> dependency: update `jaq` from `1.3.0` to `1.6.0`

.github/ISSUE_TEMPLATE/feature_request.yml
This change saves me a few clicks for all new dedicated feature request issues.
=> ci: add dedicated feature requests to new project automatically

CHANGELOG.md, test/config/rspamd_full/user-patches.sh, test/tests/parallel/set1/spam_virus/rspamd_full.bats
Updated links and the setting's name for GTube enablement.
Integrated the [Rspamd GTube pattern](https://rspamd.com/doc/other/gtube_patterns.html) for doing nothing.
=> tests(rspamd): Update GTube patterns

docs/content/config/security/rspamd.md
ref: <https://github.com/docker-mailserver/docker-mailserver/issues/4202#issuecomment-2381246320>
=> Rspamd documentation: update Abusix signup link

target/bin/rspamd-dkim
Fixes #4180
No `CHANGELOG.md` entry required.
=> doc: add an example for using the keytype ed25519 when using DKIM & Rspamd

.github/workflows/docs-preview-deploy.yml
=> ci: Revise `docs-preview-deploy.yml`

target/scripts/build/compile.sh
=> chore(compile.sh): Consistent apt-get install command

README.md
This reverts commit 84180f879e5eaaa15930509d4154248c3248d765.
Fixes #4186
ref: #4302
=> revert "fix: fix incorrect link in README.md (#4184)"

docs/content/config/security/rspamd.md
Updates the Rspamd documentation to include an example for ARC.
Fixes #3759
=> docs: add ARC example to Rspamd documentation

CHANGELOG.md, docs/content/config/advanced/mail-getmail.md, target/bin/setup
Add missing "setup debug getmail" command and documentation
Fixes #
=> Add missing "setup debug getmail" command and documentation

CHANGELOG.md, demo-setups/fetchmail-compose.yaml, demo-setups/relay-compose.yaml, docs/content/config/advanced/mail-forwarding/relay-hosts.md, docs/content/config/security/rspamd.md, docs/content/examples/tutorials/dovecot-solr.md, target/scripts/helpers/rspamd.sh
This PR marks the feature freeze phase for the `v15.0.0` release.
The current `:edge` image will be tested and if no bugs get reported, `v15.0.0` will be released. During this testing period, only PRs that do not change functionality will be merged.
**If you want to support us, give the latest `:edge` image a try and report any issues you encounter back to this PR.**
Documentation updates may be merged. **Feature freeze is in place until 1 Mar 2025**.
Fixes #4302
=> release: v15.0.0

mailserver.env
=> docs: Update Dovecot link in `mailserver.env`

CHANGELOG.md, target/scripts/helpers/change-detection.sh
Include `*.conf` files when checking for changes in the Rspamd configuration.
Fixes #4397
=> fix: include all files in change detection of Rspamd

CHANGELOG.md, docs/content/config/environment.md, mailserver.env
Changing his to their
I was unable to figure out what format the CHANGELOG.md file should be in, here is my best guess. There's also no point of contact to the dev team, normally I'd just email a patch...
=> chore: Gender-neutral language

CHANGELOG.md
Given the time for feedback, and the fact that this is only a patch release, I am in favor of merging and releasing this immediately. What do you think @casperklein @polarathene?
=> release: v15.0.1

CHANGELOG.md
This PR marks the release of v15.0.2 which includes the fix for GPG encryption & signing.
=> release: v15.0.2

docs/content/examples/tutorials/dovecot-solr.md
Added some notes for the current release of solr (9.8) and deployment using podman.
=> docs: Dovecot Solr - Add compatibility note

docs/content/config/advanced/full-text-search.md
For readers to be aware of since FTS Xapian is a community contributed feature and our docs don't communicate that limited support from us (_**reference:** [known unresolved support request](https://github.com/docker-mailserver/docker-mailserver/issues/4229#issuecomment-2440710794)_). Motivated by [this interaction](https://github.com/orgs/docker-mailserver/discussions/4461#discussioncomment-13002388).
=> docs(xapian): Add note about config compatibility

target/scripts/startup/setup-stack.sh
Thanks to @smeenz for [spotting the typo](https://github.com/docker-mailserver/docker-mailserver/issues/4479#issue-3078323190) :)
=> chore: Typo fix for debug log

docs/content/config/best-practices/dkim_dmarc_spf.md
=> docs: fix minor typo

CHANGELOG.md, config-examples/fail2ban-jail.cf, docs/content/config/security/fail2ban.md, target/fail2ban/jail.local, test/tests/parallel/set1/spam_virus/fail2ban.bats
Disabled `postfix-sasl` jail and added a note to the documentation.
Fixes #4336
=> chore: disable F2B `postfix-sasl` jail

CHANGELOG.md, Dockerfile, docs/content/config/environment.md, target/scripts/build/packages.sh
This PR removes Pyzor and Razor, which are not actually in use according to #4351. This change also simplifies the build process again.
Fixes #4351
=> chore: Remove Pyzor + Razor packages

CHANGELOG.md, target/scripts/build/compile.sh, target/scripts/build/packages.sh
Updates the `step` CLI, `jaq` and Dovecot Xapian.
=> chore: update externally installed software
