docker-mailserver/docker-mailserver

- start-mailserver.sh
Your domain was in the start-mailserver.sh script, so the domain folder was never created with ENV vars.
> replaced ifusio.com by ${domain}

- start-mailserver.sh
Pop3 certificate path is broken when "letsencrypt mode" is selected.
> fix pop3 certificate path

- start-mailserver.sh
This is to use a non-letsencrypt but CA signed (so non-self-signed) certificate which contains everything, key etc.
> Allowing CA signed custom certificates

- Makefile
- README.md
- start-mailserver.sh
- test/tests.bats
Hi Thomas.
This is kind of an initial exploratory pull request to figure out whether you would be interested in more future pull requests for an SMTP_ONLY option for your the docker-mailserver. I quite like the high integration of all these daemons and would preferably work collaboratively one Dockerfile. However, my use case does not require any courier daemons and therefore, I would prefer them not running at all. 
I hope I have done my homework right and you will accept this clean merging patch. As requested I provided some additional tests.
Cheers,
Marko
> New SMTP_ONLY environment variable to disable all courier daemons

- README.md
- postfix/master.cf
- postfix/opendkim.conf
- start-mailserver.sh
Now you can configure AWS SES as relay for postfix.
> Make the required changes for relay support

- start-mailserver.sh
syslog and mail (postfix?) daemon were not continue to write the logs in the newly created file after rotating the old log file. so after a while fail2ban daemon was watching the new (but empty) file and did not work anymore.
see `ls -l /var/log` and `lsof | grep /var/log` for example.
adding "copytruncate" in the configuration file is probably a common solution.
by the way: i also switched on the file compress feature (.gz) for rotated files.
> fixed log rotate 

- start-mailserver.sh
Some LE tools like simp_le create the cert files with no end-of-line. This change adds an eol if non exists.
If a file does not exist, sed throws an error on STDERR. It might be a good idea to check for file existence first like in the "self-signed" and "custom" case.
This fixes [Issue #110 ](https://github.com/tomav/docker-mailserver/issues/110).
> Add eol to letsencrypt provided files [Issue #110]

- Makefile
- README.md
- start-mailserver.sh
- test/tests.bats
Implement #112
Fail2ban is not enabled by default, now.
* Changed/updated Makefile and integration tests
* Changed some grep expressions in the fail2ban tests
> Add ENABLE_FAIL2BAN environment variable to enable fail2ban service

- Makefile
- start-mailserver.sh
The README lists the environmental variable as `SASL_PASSWORD` while the startup script was actually looking for `SASL_PASSWD`. The script now looks for `SASL_PASSWORD` which is consistent with documentation.
Also changed warning to info, as per discussion in #120.
> Changed $SASL_PASSWD to $SASL_PASSWORD

- start-mailserver.sh
Here is a fix for issue #121 and I went a bit further and added support for custom vmailbox settings (usefull for issue #57).
Now, you can define a `/tmp/postfix/vmailbox` (from within the container) that specifies extra virtual mail boxes. It is describe here: http://www.postfix.org/VIRTUAL_README.html#virtual_mailbox
Custom vmailbox settings are appended to the end of `/etc/postfix/vmailbox`, so after the generated content from `accounts.cf`.
What it allows is the support of routing all the other mail from a domain to a mail box.
For example:
accounts.cf:
```
user@domain.tld|password
contact@domain.tld|password2
```
vmailbox:
`@domain.tld domain.tld/contact/`
In this example, all the mails **other** than `user@domain.tld` and `contact@domain.tld` will be placed in `contact@domain.tld`'s …
> Removed IFS + Added vmailbox config

- test/config/clear.postfix-accounts.cf
- test/config/postfix-accounts.cf
- test/tests.bats
Adapted the user account setup for the test environment to the new v2 approach (encrypted passwords).
Modified integration tests to adapt to dovecot.
Need to be worked out:
- user accounts checks: dir layout under dovecot probably include dynamic filenames.
How can we handle that ?
- fail2ban container cannot ban via iptables if we do not run it with special
privileges.
Please note @tomav : tests involving the use of "nc -w 1" on dovecot services may need a longer timeout, in particular when testing failures as dovecot do not answer immediately (by design? who know!). It may even depends on my busy host.
> V2 CI-tests

- Dockerfile
I noticed the Dockerfile wasn't well written: files have to be removed in the same layer (for example  same RUN) it was added to save on image size.
I therefor merged the apt-get lines.
The result is an image size down to 489.7 MB instead of 559.7 MB (-12,5%). It's not much but it's still something ;-)
> Dockerfile optimization to reduce image size

- target/postfix/main.cf
mail servers using an enhanced client, sender and helo
restriction configuration.
The configuration has been adapted using this blog post:
https://www.webstershome.co.uk/2014/04/07/postfix-blocking-spam-enters-server/
Basically mail servers having invalid configuration (as e.g. sending
from and dynamic IP or a misconfigured hostname) will have their
mails rejected.
Additionnally three RBL servers are used to detect spam sending
IPs: dnsbl.sorbs.net, zen.spamhaus.org and bl.spamcop.net.
The results of a 12h test drive using a 100+ daily spam
mail account (SpamAssasin was always enabled, just counting
delivered mails to inbox not counting what SA detected):
- Before: 34 incoming mails
- Afer change: 6 incoming mails (82% reduction)
Fixes #161.
> Adapted Postfix configuration to block typical spam sending

- Dockerfile
- Makefile
- README.md
- target/postfix/main.cf
- target/postfix/master.cf
- test/config/sieve/dovecot.sieve
- test/email-templates/sieve-spam-folder.txt
- test/tests.bats
The dovecot-sieve plugin is installed and configured to apply sieve
as soon as a .dovecot.sieve file is encountered in the virtual user's
home directory (that is /var/mail/${domain}/${username}/.dovecot.sieve).
Transport has been changed in the postfix configuration to use
Dovecot LDA (see http://wiki.dovecot.org/LDA/Postfix) to actually
enable sieve filtering.
Tests have been added.
Addresses #87.
> Implement basic sieve support using Dovecot.

- Dockerfile
- target/start-mailserver.sh
Changed Dockerfile to include a missing configuration file for dovecot (mailboxes).
Changed info message when no postfix-main.cf are provided for overriding postfix config (was referencing the older file name).
Moved Postfix setup after DKIM/DMARC/SSL setup, near the override postfix setup.
This one in particular is only aesthetic if you look at the order messages are outputted at startup:
> user 'user2' for domain 'otherdomain.tld' with password '********'
> Postfix configurations
> No DKIM key provided. Check the documentation to find how to get your keys.
> Loaded 'config/postfix-main.cf'
I thought that `Postfix configurations` should appear before the `loading of postfix-main.cf` instead of being interleaved by DKIM, SSL etc.
> Sieve filters can now be installed at user setup.

- target/bin/generate-dkim-config
Hi, I used your v2 branch and wasn't able to send mails due
```
Apr 30 11:01:11 mail opendkim[521]: mail._domainkey.zauberstuhl.de: key data is not secure: /tmp can be read or written by other users
Apr 30 11:01:11 mail opendkim[521]: 176E2C07: error loading key 'mail._domainkey.zauberstuhl.de'
```
I followed your tutorial and ran `generate-dkim-config` from the console. Maybe I missed a step but in the KeyTable file there is the path to the temporary file configured after creation.
~~You can avoid this kind of issue by simply running `sed` after the copy step. Even if I missed something that fix could avoid problems in future.~~
great work btw.. Cheers!
> Fix permission issues on wrong dkim path

- README.md
- docker-compose.yml.dist
./opendkim/ local folder shadows ./config/opendkim
on generation of the keyfiles all files get written to ./config/opendkim leaving ./opendkim empty
thus on startup no config for opendkim is loaded
> opendkim folder shadowing

- README.md
- docker-compose.yml.dist
By having two separate `volumes` options, only the last one is used, so they should be merged into one to make sure the `maildata` container is used.
> Merge "volumes" option in docker-compose.yml

- Dockerfile
- Makefile
- README.md
- target/start-mailserver.sh
- test/config/postfix-regexp.cf
- test/email-templates/existing-regexp-alias-external.txt
- test/email-templates/existing-regexp-alias-local.txt
- test/tests.bats
This PR is not intended to be merged as-is, please indicate whether you want all/some/none of it and I can cherry-pick accordingly. It has:
- avoid fixing permissions if they're OK #190
- support regexp alias file
- support outgoing email via AWS SES
I added docs to the README, but I would move that to the wiki.
> Avoid fixing permissions; add regexp alias file, add AWS SES outgoing email support

- config/dovecot.cf
- target/start-mailserver.sh
- test/config/dovecot.cf
- test/tests.bats
Inspired by the `postfix-main.cf` I created a `dovecot.cf` configuration file which is loaded by dovecot as last config file. So additional configurations for dovecot can be easily appended.
> Add a additional configuration file for dovecot

- Makefile
- target/start-mailserver.sh
This PR consolidates all directories with mail state into /var/mail-state, which can then be mounted as a volume. This is to address #191.
This PR is based off the changes in PR 194, please look at the one new commit https://github.com/tomav/docker-mailserver/commit/4ca39f9144f42675257af879c7d49558e5d66f1d for the changes.
If you like this approach, I will add docs to the Wiki. Dunno whether you want this to be in the docker-compose.yaml.dist or not. Also, I changed the tests to use the consolidated directories, but I don't really know how you want to proceed, so this PR is a bit of a WIP 'til I hear back...
> Persist mail state directories

- target/postfix/main.cf
Fixes untrusted TLS connections
See: http://giantdorks.org/alain/fix-for-postfix-untrusted-certificate-tls-error/
Before: `Untrusted TLS connection established to gmail...`
After: `Trusted TLS connection established to gmail...`
> Add paths to CA to postifx

- .gitignore
- target/bin/addmailuser
- target/bin/delmailuser
- target/bin/generate-dkim-config
- test/tests.bats
Several tools expect the presence of certain config files, and fail gracelessly when they are absent.
Both addmailuser and delmailuser assume the existence of the postfix-accounts.cf file, while generate-dkim-config assumes the existence of that file and the postfix-virtual.cf file.
> Handle missing files more gracefully.

- target/bin/addmailuser
- target/bin/delmailuser
- target/bin/generate-dkim-config
The main shell script (start-mailserver.sh) uses two spaces for
indentation. All other shell scripts should use this coding
style.
> Adjust coding style in "bin" scripts

- setup.sh
To setup the mailserver large snippets of shell code had to past in a
console. Instead of:
```
mkdir -p config
touch config/postfix-accounts.cf
docker run --rm \
-e MAIL_USER=user1@domain.tld \
-e MAIL_PASS=mypassword \
-ti tvial/docker-mailserver:latest \
/bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s SHA512-CRYPT -u
$MAIL_USER -p $MAIL_PASS)"' >> config/postfix-accounts.cf
```
you can specify:
```
./setup.sh email add user1@domain.tld mypassword
```
This wrapper script can be easily extended. It uses the scripts already
builtin.
> Add wrapper script for easier setup of the docker-mailserver

- Dockerfile
- setup.sh
- target/bin/listmailuser
- test/tests.bats
This commit adds a script nammed 'listmailuser'. './setup.sh' uses this
this script for its subcommand './setup.sh email list'. A test have
been added too.
> Implement './setup.sh email list'

- target/start-mailserver.sh
- test/tests.bats
The letsencrypt-auto client creates cert.pem, chain.pem, fullchain.pem, and
privkey.pem in its default settings.  The simp_le client creates cert.pem,
fullchain.pem, and key.pem in its default settings.
A check for either privkey.pem or key.pem was added.
The chain.pem file was only used by the letsencrypt code for the creation of
combined.pem, which is not used by either postfix or dovecot.
The code to create a combined.pem file for letsencrypt was removed, as was the
corresponding test.
> Minor tweaks to letsencrypt configuration.

- Dockerfile
- setup.sh
- target/bin/debug-fetchmail
- target/bin/setup-fetchmail
- target/start-mailserver.sh
Fetchmail is now configured by a script called 'setup-fetchmail'.
The script 'debug-fetchmail' is used inside the 'setup.sh' script.
> Improve fetchmail support

- target/start-mailserver.sh
This code was mistakenly not committed, and is required for the feature to work.
Functional tests all pass, and I have additionally tested the container in my production environment using keys generated by simp_le.
> Actually use the key.

- .travis.yml
Most developers implement new docker-mailserver features on feature
branches before they create a pull request. This commit enables Travis
CI testing on all branches except 'donttestme'. Developers now can
'pre-test' their features branches without permanentaly hacking
'.travis.yml'. More testing is good!
> Let Travis CI test on all branches

- target/bin/debug-fetchmail
The option '--check' checks for new mails without actually fetching
or deleting mail. Without '--check' 'debug-fetchmail' throws errors if
the external mail accout has new mails and the smtp daemon is not
running.
> Improve script 'debug-fetchmail'

- Makefile
- README.md
- target/start-mailserver.sh
- test/tests.bats
I needed to directly specify the paths to my SSL certificates to solve getting this running within a Kubernetes cluster where my SSL certificates are managed by kube-lego.
Kubernetes will let me mount the secret volume (which is where the ssl keys are stored) into the container, but the "self signed" and "custom" options really work with that.
This will let you define two additional env variables
SSL_CERT_PATH
SSL_KEY_PATH
Honestly just being able to manually tell what SSL certificates is very handy since obviously not everyone fits in a specific structure. 
Let me know what you think or if there is anything I can improve!
> Add the option of manually specifying paths to SSL certificates

- Dockerfile
For other items (files, directories) that do not require ADD’s tar
auto-extraction capability, you should always use COPY.
docker run --rm -i lukasmartinelli/hadolint < Dockerfile
shows:
/dev/stdin:49 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:50 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:62 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:63 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:77 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:78 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:81 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:82 DL3020 Use COPY instead of ADD for files and folders
/dev/stdin:85 DL3020 Use COPY instead of ADD for files and folders …
> Use COPY instead of ADD in Dockerfile (#301)

- target/start-mailserver.sh
Quick fix for #306 
For now, supplementary ipv4 addresses are not added to mynetwork.
> Fix for multiple IPV4

- Dockerfile
- Makefile
- target/start-mailserver.sh
- test/tests.bats
This PR removes `spamd` process from container because of reasons described in #311.
> Remove unnecessary spamd process

- target/start-mailserver.sh
Many escaped slashes can be avoided by changing the deliminter in sed
replace statements. This increases readability a little bit.
> Avoid many escaped slashes in sed scripts

- Makefile
Remove also all temporary test files. A new test can be started without
reclone the repository.
> Improve 'make clean'

- target/start-mailserver.sh
This reverts commit e5d14fd0bc79c21e89ebc51ce81e9b31cd1f35d0.
172.0.0.0-172.15.255.255 and 172.32.0.0-172.255.255.255 are valid
external IP addresses. Try PERMIT_DOCKER: network instead.
> Revert "Fix for multiple ipv4" (#306 #310)

- elk/10-syslog.conf
This removes syslog data from the message, because timestamp, hostname, program and pid are parsed anyway into their own fields, and postfix-grok-patterns only parses output from postfix (like `^%{POSTFIX_SMTP}$`).
> Fixes #339 (fix for ELK postfix fields)

- Dockerfile
- target/opendkim/default-opendkim
- target/opendkim/opendkim.conf
- target/opendmarc/default-opendmarc
- target/opendmarc/ignore.hosts
- target/opendmarc/opendmarc.conf
- target/postfix/main.cf
- target/postfix/master.cf
- target/start-mailserver.sh
- test/tests.bats
This PR provides some improvements for current milters integration inside container:
1. Upgrades `milter_protocol` from `2` to `6`. It seems that there is no reason to keep it `2`, because all apps that uses it (OpenDKIM, OpenDMARC) already supports `6` with their current versions.
2. Disables OpenDMARC milter for outgoing mails as far as it does no job. [DMARC relies on SPF and DKIM](https://dmarc.org/wiki/FAQ#How_does_DMARC_work.2C_briefly.2C_and_in_non-technical_terms.3F) and there is nothing to do with outgoing messages for it (opposite to OpenDKIM which must sign messages).
3. Disables duplicate milters checking when we receive mail back from AMaViS on `10025` Postfix port. Miltering before sending mail to AMaViS is enough.
4. Sets OpenDKIM and OpenDMARC to listen on more …
> Improve OpenDKIM and OpenDMARC milters integration

- target/start-mailserver.sh
The domainname comand may return `(none)` use instead `hostname -d` to get the domainname
> Use hostname to get domainname

- target/postfix/main.cf
- target/start-mailserver.sh
- test/tests.bats
As far as Postfix setup inside Docker container does not require to re-apply configuration on-fly, and reconfiguration is done with container restarts (which actually stops and starts Postfix) we can use [`texthash:` Postfix lookup format](http://www.postfix.org/DATABASE_README.html#types) instead of `hash:`, which allows us don't mess with pre-`postmap` commands.
Also, I changed a bit handling of such lookup files to make them survive container restarts a bit better. Initially, if we create a container with accounts configuration, then remove all accounts and restart container, those accounts will be in lookup files still. I made them stripped before accounts configuration is applied.
> Use "texthash" Postfix lookup format instead of "hash"

- target/dovecot/10-ssl.conf
Postfix configuration use strong protocols and ciphers, I don't know if there is a good reason for not using them in dovecot.
> use strong tls and ciphers

- target/start-mailserver.sh
Fail2ban doesn't seems to shutdown cleanly and leaves fail2ban.sock file that prevent it from starting after a container restart. That simple check should do the trick.
> Fail2ban fix for restarting container

- target/start-mailserver.sh
The provided default postfix master.cf overwrites the configs for
saslauthd within main.cf. To make saslauthd work, we have to comment or
in this case delete the lines from master.cf to make the given configs
in main.cf work.
> Fix Problem with Saslauthd and Postfix master.cf

- Makefile
- README.md
- docker-compose.yml.dist
- target/start-mailserver.sh
- test/tests.bats
* Removed DISABLE_AMAVIS
* Renamed DISABLE_* to ENABLE_* with 0 as default value. (this must be explicit)
* Added missing tests for ENABLE_*
* Improved readme and docker-compose example
Should fix #256 and #386
This will be released as `tvial/docker-mailserver:2.1`
> BREAKING CHANGES:

- target/bin/addmailuser
- target/bin/delmailuser
- target/bin/listmailuser
- target/bin/updatemailuser
- test/tests.bats
I tried to refactor and improve the mailuser tools (add/del/list and update). Certain user names were not exactly matched by the patterns: e.g. "user@domain" matched also "anotheruser@domain", or "a.user@domain" matched "anuser@domain".
I appreciate your project very much, it is really useful to me! Thank you so much!
> Fix mailuser tools

- Makefile
- target/start-mailserver.sh
- test/auth/sasl-imap-smtp-auth.txt
- test/tests.bats
#443
- Added unit tests to rimap sasl mechanism
- Enabled sasl auth in postfix when rimap mechanism is selected
- Additionally, it seems necessary to start saslauthd with option "-r" ("Combine the realm with the login") in that case
> Fix #443 - RIMAP support

- docker-compose.yml.dist
On Docker Hub, the tag for **v2.1** is labeled **2.1**
> Docker tag fix

- setup.sh
The updatemailuser needs parameters. Without this, the command can not work and fails with:
```
Usage: updatemailuser <user@domain.tld> [password]
no username specified
```
> Fix update in setup.sh

- Makefile
- target/start-mailserver.sh
This PR replaces `$(hostname)` with `$(hostname -f)` result in `start-mailserver.sh` for better container hostname detection.
Related to problem [described here](https://github.com/tomav/docker-mailserver/issues/407#issuecomment-271279511).
> Convert `$(hostname)` usage to `$(hostname -f)`

- elk/Dockerfile
Set transport.host on elasticsearch.yml config file to avoid Bootstrap Checks failure on production environments
> Set transport.host on elasticsearch.yml config file

- target/start-mailserver.sh
Fix "/usr/local/bin/start-mailserver.sh: line 489: [: argument expected"
There are quotes missing around a shell variable. I added some more, too.
[ -z ] is okay, but [ a = b -a -z ] is not.
Signed-off-by: Wolfgang Ocker <weo@reccoware.de>
> Fix #499 (in start-mailserver.sh, argument expected)

- Makefile
- target/start-mailserver.sh
- test/tests.bats
I have noticed that my emails contain the hostname of my docker host when I use the docker option `--net=host` with the env-var `OVERRIDE_HOSTNAME`. That is because postfix, dovecot and opendmarc user the `hostname` command to retrieve the name of host. Until now the hostname was only overwritten for amavis, but these changes will overwrite it for all mentioned services.
> Hostname override fixes for docker option --net=host in conjunction with OVERRIDE_HOSTNAME

- Dockerfile
- target/postfix/main.cf
- target/postfix/master.cf
- test/tests.bats
This adds support support for checking incoming SPF records using `postfix-policyd-spf-python`.
I have also moved the `DEBIAN_FRONTEND` to use the `ENV` command so that it works for all apt-get runs, eliminating apt-get runs complaining about the lack of `TERM`.
Test where executed via `make` and successful.
> Fixes #451 - add incoming mail SPF policy checks

- README.md
- docker-compose.elk.yml.dist
- docker-compose.yml.dist
This PR adds restart: always to the containers in docker-compose.yml for 
auto-restarting them in the event of docker service or host restart.
> Add restart: always

- Dockerfile
Regarding too frequent IDLE notifications mobile clients like k9mail have a massive battery drain.
More info:
https://github.com/k9mail/k-9/issues/1290
https://peterkieser.com/2011/03/25/androids-k-9-mail-battery-life-and-dovecots-push-imap/
P.S. Please correct me if I have to add additional changes. I've read contributing guide, but this change doesn't affect tests and build step.
> Fix battery drain for mobile clients

- target/start-mailserver.sh
- test/config/postfix-main.cf
Commit 912cb5676b9538eb1c799b3c229c7e8dc9c94f40 restricts accounts to begin with lower case a-z
The modified regex now ignores empty lines, lines with one or multiple blanks and lines with comments (#) but allows accounts like 123@domain.tld.
Fixes #567
> Allow accounts which do not start with a-z (fixes #567)

- target/start-mailserver.sh
- test/config/whitelist_clients.local
- test/nc_templates/postgrey_whitelist.txt
- test/tests.bats
Copies whitelist_clients.local from config dir to /etc/postgrey. 
Test is made by communicating directly with postgrey via nc on port 10023 in order to test for the correct client_name instead of localhost. 
Credit for that solution to this blog post: http://www.brandonchecketts.com/archives/manually-testing-postgrey-through-a-telnet-session
> Include whitelist_clients.local in postgrey setup from config folder

- target/start-mailserver.sh
- test/email-templates/smtp-only.txt
- test/tests.bats
When using the container with SMTP_ONLY = 1,  the postfix process within the container fails
on ehlo because there is no valid sasl authentication mechanism available. This happens because sasl has been enabled within postfix/main.cf per default but sasl is not configured.
To fix this _setup_postfix_sasl does not depend anymore on ENABLE_SASLAUTHD and will check in it's logic, whether to enable or disable sasl explicit within postfix/main.cf.
> Fix #526: fatal: no SASL authentication mechanisms

- target/start-mailserver.sh
This letsencrypt docker image [https://github.com/janeczku/rancher-letsencrypt](url) doesn't create the cert.pem required to pass this test.
> Letsencrypt : do not check the optional cert.pem

- .gitmodules
- Dockerfile
- target/start-mailserver.sh
This pr integrates my project https://github.com/alinmear/docker-configomat for dealing with container configurations via ENV Variables. 
With this separate project testing whether substitution is working or not and also updating the logics behind them is much easier then doing this within `start-mailserver.sh` (own travis and bats).
This should also fix the problems with the special character `|` from https://github.com/tomav/docker-mailserver/pull/644#issuecomment-313879711 (@johansmitsnl).
> Integrate docker-configomat for configuration parts of start-mailserver.sh #648

- Dockerfile
> remove /etc/cron.weekly/fstrim since we don't want to fstrim in docker

- Dockerfile
- target/start-mailserver.sh
- test/tests.bats
This should fix #660.
Cron-Job is now written to `/etc/cron.d/freshclam`. On start, the cron job and logrotate files regarding clamav are removed if clamav is disabled. This means that this can not be reversed, but changing the environment should also spawn a new container with the files intact (in case someone wants to reenable clamav)
> Disable logrotate and cron job for updating clamav if clamav is disabled (fixes #660)

- Dockerfile
- Makefile
- setup.sh
- target/fail2ban-wrapper.sh
- target/postfix-wrapper.sh
- target/start-mailserver.sh
- target/supervisor/saslauth.conf
- target/supervisor/supervisor-app.conf
- test/tests.bats
Use the supervisor as the main process. The start-mailserver is started
from the supervisord and then this process triggers others.
Defined some default variable in the Dockerfile. In order for
supervisored to build the command lines the ENV variable need to be set.
Therefore the defaults are defined.
Some processes are not single processes like postfix and fail2ban and
they have a wrapper. The wrapper takes care of proper shutdown and checking
if the process is running or not. Supervisored will restart the wrapping
script if the process is gone.
Increased some delays between tests because sometimes they where to short
for all containers to be running.
> Issue 631 run services with supervisor

- test/config/opendkim/KeyTable
- test/tests.bats
When making a new PR I noticed that there was no test for smtp authentication on the submission port.
While adding it opendkim is complaining about the permission in the KeyTable location. It is set to /tmp/... but this is wrong.
This PR fixes the path and adds a test for smtp authentication on the submission port.
> Also test on the submission port if the login is succesful

- Makefile
- target/start-mailserver.sh
During a stop and start pid files can be left over with wrong information.
Clean them before starting new services.
See #697
> Clean any leftover pid file from a stop

- Dockerfile
- target/postfix/master.cf
- test/tests.bats
Also use the SSL port for clients to deliver emails.
Added tests to verify tls strength and authentication.
See #618
> Listen also on the ssl port 465

- Dockerfile
- target/amavis/conf.d/62-improve_privacy_remove_headers
- target/postfix/main.cf
- target/postfix/master.cf
- target/postfix/sender_header_filter.pcre
- target/start-mailserver.sh
- test/email-templates/send-privacy-email.txt
- test/tests.bats
We should care about our privacy and hide information when we send emails.
See ticket #681 
The PR has tests to ensure the filter is working. Multiple items are added that I think should be filtered. The minimal compatibility level had to be set to 2 in order for pcre to work and not creating errors in the logging.
> Improve the privacy of the client by removing sensitive details

- target/opendmarc/opendmarc.conf
opendmarc checks fail for mail sent over (SMTP AUTH) submission
ports. Adding this directive skips checks for those emails, and
clears the logs of related errors.
See https://github.com/tomav/docker-mailserver/issues/703
> [opendmarc] Skip dmarc checks for email sent over authenticated sockets

- Dockerfile
This should fix #661. There are two changes to `/usr/sbin/invoke-rc.d` which is used for syslog logrotation. A warning that the (systemd) runlevel cannot be determined was commented out and a "policy helper" was deactivated (instead of removing the script `/usr/sbin/policy-rc.d`). Syslog logrotation still works and in manual the daily mail was not sent anymore.
> Prevent syslog logrotate warnings

- target/start-mailserver.sh
I spent quite a while trying to set up an alias in `config/postfix-regexp.cf` like this:
```
/^(?!info|bob)\S+@customer.com/ webmaster@serviceprovider.com
```
I wanted the client to recieve mail for a couple of users @customer.com and everything else to be sent to me so I can deal with maintenence stuff. The negative-lookahead regular expression seemed to be the solution but I couldn't get Postfix to understand it.
It turns out Postfix has 2 regular expression implementations denoted by the prefixes `regexp:` and `pcre:` in config files. Perl-compatibe regular expressions (PCRE) seem to be the main implementation wherever I've used them before, however the Postfix config here uses the basic type by default.
I am currently overriding by putting the following in `config/postfix-main.cf` but …
> Use PCRE for alias regular expressions instead of the basic type

- target/check-for-changes.sh
`-f` option for the `[` (`test`) commend is not valid on string comparison.
> Fix arguments for [ command

- target/postfix/main.cf
Prevents Spammers from collecting existing mail-addresses by probing the mailserver for them.
(http://www.postfix.org/postconf.5.html#disable_vrfy_command)
> disable_vrfy_command

- Makefile
- README.md
- setup.sh
- target/dovecot/dovecot-ldap.conf.ext
- target/postfix/ldap-aliases.cf
- target/postfix/ldap-domains.cf
- target/postfix/ldap-groups.cf
- target/postfix/ldap-users.cf
- target/postfix/main.cf
- test/config/dovecot-lmtp/dovecot-ldap.conf.ext
- test/config/ldap-aliases.cf
- test/config/ldap-groups.cf
- test/config/ldap-users.cf
- test/tests.bats
- calling \"./setup debug fail2ban\" lists all iptable chains whith blocked IPs 
(like: 
Banned in dovecot: 91.200.12.164
Banned in postfix-sasl: 91.200.12.164)
- calling \"./setup debug fail2ban unban xxx.xxx.xxx.xxx [yyy.yyy.yyy.yyy ...]\" unbans/removes those IPs from all jails.
- calling \"./setup debug fail2ban unban\" (without an IP) gives an descriptive error: (You need to specify an IP address. Run "./setup.sh debug fail2ban" to get a list of banned IP addresses.)
> fail2ban handling integrated in setup.sh

- Makefile
- README.md
- target/postfix/main.cf
- target/postfix/master.cf
- target/start-mailserver.sh
- test/tests.bats
Cheaper, earlier and simpler blocking of zombies/spambots.
From http://postfix.cs.utah.edu/POSTSCREEN_README.html :
As a first layer, postscreen(8) blocks connections from zombies and other spambots that are responsible for about 90% of all spam. It is implemented as a single process to make this defense as cheap as possible.
Things we need to consider:
- Do we need a whitelist/backlist file? (http://postfix.cs.utah.edu/postconf.5.html#postscreen_access_list)
- Via introducing an optional config/postfix-access.cidr
- The only permanent whitelisting I could imagine are monitoring services(which might (still?) behave weird/hastely) or blacklisting backup servers(since no traffic should be coming from them anyway)
- Do we need deep inspections? They are desireable, but these tests are …
> Introducing Postscreen

- Dockerfile
- target/postfix/main.cf
- target/postsrsd-wrapper.sh
- target/postsrsd/postsrsd
- target/start-mailserver.sh
- target/supervisor/conf.d/supervisor-app.conf
- test/tests.bats
This PR fixes an issue regarding redirecting emails to an external provider. Previously it ended in a softfail SPFs, because no sender rewriting was applied to the from address. 
For example if you add the following to your config, you should end up with softfails
```
mymail@domain.com user@gmail.com
```
Partly this fixes issue #611 if i understood everything correctly. Also huge thanks to @tuxpowered for pointing into the right direction 👍 
There are no tests atm, but i'm not sure how to test for something like this?
> Fix: Add SRS to fix SPF issues on redirect #611

- target/postfix/main.cf
Added reject_sender_login_mismatch parameter to prevent users from sending email using arbitrary email address. #811
> Added  reject_sender_login_mismatch

- target/dovecot/15-mailboxes.conf
The Junk folder is currently not created by default. Also there is no documentation on how to setup the Junk folder. Imho the Junk folder should be created and subscribed by default as the other folders. #795 #768
> Changed Junk folder to be created and subscribed by default

- Dockerfile
Since it is assumed that the NSA uses rainbowtables to break default-DHE-Parameters, one is encouraged to change those parameters periodically.
See: 
Paper: [Imperfect Forward Secrecy: How Diffie-Hellman Fails in Practice](https://weakdh.org/imperfect-forward-secrecy-ccs15.pdf)
Consideration: [Wie die NSA den Diffie-Hellman Schlüsseltausch knackt](https://www.heinlein-support.de/blog/news/wie-die-nsa-den-diffie-hellman-schluesseltausch-knackt/)(German)
> Diffie-Hellman 2048 Bit Parameters should be changed regularly.

- target/start-mailserver.sh
funny bug.
there was a sed command searching for `bl.spamcop.net$` and we had two occurrences of bl.spamcop.net in the main.cf file. The correct one and one from the postscreen dnsbl list.
Why wasn't this detected with the initial PR of postscreen?
Because there was a trailing space behind bl.spamcop.net, which then got removed with some other PR.. m(
So this should fix #840 
Test passed on my machine
> fixed greedy postgrey sed command

- target/start-mailserver.sh
- test/tests.bats
Update the postmaster_address in the `start-mailserver.sh` script.
At the moment this config is set in the `Dockerfile` at: https://github.com/tomav/docker-mailserver/blob/c36e878d76827fc7062558f1edada05d7ba38880/Dockerfile#L111
But this code is executed only when the docker image is built and not at runtime.
> update postmaster_address in dovecot config according to POSTMASTER_ADDRESS env var

- Dockerfile
on some hosts logrotating may cause emails to get sent out (see #792).
by setting the --quiet option on that action, a single warning is suppressed.
Works on a daily basis in my production environments and in artificial testing environment, where daily cronjobs are executed once an hour.
> fixes issue #792 by setting quiet mode on invoke-rc.d

- target/start-mailserver.sh
Added `/var/lib/dovecot/` to the list of folders that get persisted in `mailstate`. So the creation of `ssl-parameters.dat` has not to be done every restart again. This may only take some dozen seconds, but can be very long on systems with high load.
> Add /var/lib/dovecot to mailstate persistence

- Dockerfile
- README.md
- target/postsrsd-wrapper.sh
This will generate an SRS secret the first time the container runs and store it in state or /etc for future invocations. If the user defines any secrets that will be used instead.
Thanks and keep up the good work!
> Generate SRS secret on first run and store it

- target/bin/addalias
- target/bin/delalias
- target/bin/delmailuser
- target/bin/updatemailuser
- target/start-mailserver.sh
- test/tests.bats
solves #878
- `delmailuser` is now capable of deleting multiple accounts at once, prompting for confirmation to delete the maildir as well. An additional `-y` flag was introduced to assume yes on this question.
I had to modify most of the shell scripts which are modifying the postfix-accounts and postfix-virtual databases due to the modified delmailuser script.
- `updatemailuser` was just deleting and readding the user as a new one. This wasn't possible with the new deletion script anymore.
- `addalias, delalias` was changed to reflect the correct implementation of multiple recipients for one alias (`,` as saparator only, actually that was making it much easier for me, getting the sed commands do what I wanted them to do! ;) )
> Delmailuser

- target/start-mailserver.sh
Added error messages to letsencrypt on startup so when some files are not found we get an output directing us in the right direction.
I think this should also be added to other setup functions soon.
> Log errors of letsencrypt on startup

- Makefile
- target/start-mailserver.sh
- test/config/dovecot-lmtp/userdb
At the moment we only backup ./config/postfix-accounts.cf before testing the setup.sh functionality.
This PR creates a backup of the whole config folder and while cleaning restores it.
Also I removed the dovecot-lmtp/userdb file that is removed by make clean.
> Backup config folder while testing

- setup.sh
If the argument isn't quoted, then you can't run commands like
```
./setup.sh debug login "tail -f /var/log/mail/mail.log"
```
> quotes needed to run multi-word command inside container

- target/bin/postfix-summary
this PR adds the `To`, `Content-Transfer-Encoding` and `Content-Type` headers to the postfix summary mails
> add headers to postfix summary mail

- target/bin/postfix-summary
my last PR #919 unfortunately broke the line breaks in the error case of the postfix summary mail (sorry about that), this commit fixes them
(the `echo -e` interpreted the `\n` as a line break before, but the heredoc doesn't)
> fix line breaks in postfix-summary mail error case

- Dockerfile
- Makefile
- target/dovecot/90-sieve.conf
- target/start-mailserver.sh
- test/config/before.dovecot.sieve
- test/tests.bats
On my way to getting spam handling done. This was part of PR #835 but should be handled as a separate PR I think. 
This introduces the optional global sieve files `after.dovecot.sieve`/`before.dovecot.sieve` which apply to **every** incoming email. They are executed before and after any user specific `{user}.dovecot.sieve` filter would be applied.
Wiki entry will follow once accepted.
- added optional after.dovecot.sieve/before.dovecot.sieve files
- added global filter test
>  Introducing global filters.

- Makefile
- setup.sh
- test/tests.bats
This modification proposes to support the running configured mounted volume for configuration.
This removes the need to pass a path from the command line when the container is running and configured in another way that yours.
> Support for detecting running container mount

- target/postfix/main.cf
setting value as `$myhostname` will make sasl look for users `user@mail.domain.tld` instead of `user@domain.tld`
> fix SASL domain fixes #892

- Makefile
- README.md
- target/postsrsd-wrapper.sh
- test/tests.bats
if the container doesn’t have a proper hostname, postsrsd will fail to start
because SRS_DOMAIN is empty. Make a best effort to figure out the domain name
and provide a way to set one if needed.
> DOMAINNAME can fail to be set in postsrsd-wrapper.sh

- Dockerfile
This fixes the daily mail error when logrotate tries to restart a non existing freshclam daemon because cron name doesn't fit freshclam init script invoked by logrotate
Fix second part of #792
> Fix freshclam cron name

- target/start-mailserver.sh
* Set `SPOOF_PROTECTION=1`
* Create a alias in `postfix-regexp.cf`: `/^test[0-9]@domain.tld/ mail@domain.tld`
* Try to send an email as user mail@domain.tld with sender address `test1@domain.tld`
=> Mail gets rejected with error message:
`postfix/smtps/smtpd[1312]: NOQUEUE: reject: RCPT from xxxxx[xxx.xxx.xxx.xxx]: 553 5.7.1 <test1@domain.tld>: Sender address rejected: not owned by user mail@domain.tld; from=<test1@domain.tld> to=<receiver@example.com> proto=ESMTP helo=<xxxxxx>`
After adding `/etc/postfix/regexp` to `smtpd_sender_login_maps` it worked as expected.
For LDAP this probably has to be fixed in a similar way.
Before I discovered this bug I set a alias for a whole domain in `postfix-virtual.cf`: `@domain.tld mail@domain.tld`. This worked for receiving mails as expected but not …
> Fix allow sending emails from regexp aliases when spoof protection is enabled

- README.md
If I follow the usage guide in the readme I'll get the following error when executing `./setup.sh email add test@domain.tld`:
```
"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.
Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]
Return low-level information on Docker objects
```
Because the setup script tries to talk to the container. 
Fix this by starting it first and restarting it at the end
> Fix Readme usage: Start container before running setup.sh

- target/check-for-changes.sh
- target/start-mailserver.sh
This is work in progress (sorry perhaps I should create this when done, still learning a bit here)
[x] add postfix-aliases.cf to ./config (/tmp/docker-mailserver)
[x] in check-for-changes.sh monitor postfix-aliases.cf in and apply changes to /etc/aliases
[x] in start-mailserver.sh apply postfix-aliases.cf to /etc/aliases
This solution addresses issue #988 .
> Configuration support for /etc/aliases, see issue #988

- README.md
- target/start-mailserver.sh
This should fix #1075.
- Added a section to README describing the .env-file format.
- Show hostname / domain before aborting, so it is easier to understand misconfiguration
> Clear up env format and hostname value

- README.md
- target/start-mailserver.sh
- Setting SSL_TYPE to empty string will allow to use [plain text access](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#plain-text-access).
- Setting SSL_TYPE to unknown value will give a warning about setting SSL by default.
- Updated [README.md SSL_TYPE section](https://github.com/green-anger/docker-mailserver/tree/issue-1083#ssl_type).
- Fixed a small typo in the same section.
> Issue 1083

- README.md
This patch fixes #1099 and removes some misleading quotes in the LDAP configuration. This would have saved me two days of debugging and reverse engineering.
> Issue 1099

- README.md
Per https://stackoverflow.com/a/39080253/2747593, only 1.7 and greater supports `.env` files.
I was on `docker-compose` version 1.6, and my settings in the `.env` file weren't being applied.
> Set minimum docker-compose version to 1.7

- README.md
The YAML spec allows both versions in syntax for lists. But the example shows a list with two spaces - which I also prefer visually. And even if this is not preferred, it would be nice if it was consistent.
> Update indentation in README

- CONTRIBUTING.md
- Dockerfile
- target/check-for-changes.sh
- target/dovecot/10-ssl.conf
- target/start-mailserver.sh
See issue 1175, cron complains that the freshclam entry in cron.d is invalid as it lacks a user. Fixed by adding root as user.
Note that the unit tests were failing before this, they are still failing after this and I don't really know how to test this with a unit test. A good manual test is to let the cron job run once with and without the fix. Without it there are errors in the logs and the cron job does not run.
> 1175: specify user for cron.d freshclam file

- CONTRIBUTING.md
- Dockerfile
- target/check-for-changes.sh
- target/dovecot/10-ssl.conf
- target/start-mailserver.sh
This pull request combines https://github.com/tomav/docker-mailserver/pull/1149 and https://github.com/tomav/docker-mailserver/pull/710. It fixes the outdated Dovecot configuration options and it generates the dh.pem file the first time the server starts, keeping it in the mail state for future use.
Tests failed before so they are most likely going to fail after as well, unfortunately.
> Fix Dovecot SSL parameters and generate dhparams as for Postfix

- .dockerignore
- .gitignore
- Makefile
Hi,
while working on https://github.com/tomav/docker-mailserver/pull/1194 I realised that there are quite a lot of files that are not proberly cleaned up when running the tests locally (and since they are not cleaned up will for example show up in `git status`). This PR attempts to fix this.
> add test artifacts to gitignore and clean target of makefile

- Dockerfile
Best practice suggests not using ENV for this setting as it persists after build. ARG is only set during build.
> Replace ENV with ARG for DEBIAN_FRONTEND

- target/start-mailserver.sh
Change startup script so that it accepts overrides for `master.cf` that start with a number (not only a character). This is required for changes that modify the `127.0.0.1:10025/inet` service, as e.g.:
127.0.0.1:10025/inet/smtpd_proxy_filter=
Very simple edit to `start-mailserver.sh`, chaging the regular expression used to filter `postfix-master.cf`.
> Allow postfix master.cf overrides to start with numbers

- setup.sh
- target/bin/generate-ssl-certificate
Added optional FQDN arguement to setup.sh script which avoids using temporary container hostname for cert names. Also fixed issue with certs being saved outside config volume.
> Fixed self-signed cert generation

- Dockerfile
Hi @tomav, thanks for the good work!
I've found a bug after inspecting the logs in compose:
```
mail                     | Jul 28 09:51:55 mail postfix/smtpd[2658]: warning: cannot load 1024-bit DH parameters from file /etc/postfix/dhparams.pem -- using compiled-in defaults
mail                     | Jul 28 09:51:55 mail postfix/smtpd[2658]: warning: TLS library problem: error:0906D06C:PEM routines:PEM_read_bio:no start line:../crypto/pem/pem_lib.c:686:Expecting: DH PARAMETERS:
```
`cat /etc/postfix/dhparams.pem` was showing an empty file...
Logs from docker exec -it {container_name: mail} /bin/bash:
```
root@mail:~# cat /etc/cron.d/dh2048
@weekly FILE=/tmp/tmp.aFRqiZNPZT ; openssl dhparam -out  2048 > /dev/null 2>&1 && mv -f  /etc/postfix/dhparams.pem
root@mail:~# echo "@weekly …
```
> FIX: escape symbols in cron command

- Dockerfile
Required for `action_mwl` email notifications from fail2ban
> install whois package for use with fail2ban

- Makefile
- README.md
- target/start-mailserver.sh
- test/tests.bats
This will add the networks of all eth* interfaces as trusted, which is necessary if the container is in networks that are outside of the old docker default network (172.16.0.0/12), e.g. 192.168.0.0/16
See https://github.com/tomav/docker-mailserver/issues/1079#issuecomment-499903541 for a more detailed description of the problem that is solved here.
> Add PERMIT_DOCKER=connected-networks

- target/start-mailserver.sh
- test/tests.bats
Fix for https://github.com/tomav/docker-mailserver/issues/1204
> set Nameservers in opendkim.conf at start-up

- Dockerfile
- Makefile
- target/helper_functions.sh
- target/start-mailserver.sh
- test/helper_functions.bats
- test/permit_docker.bats
- test/tests.bats
also showcase timeouts and makefile integration as needed for #1206 
This should also make #1210 obsolete
At first I just wanted to fix the tests but then I ran against the monolith again so I tried this as a playground for the modularization. The extracted tests for this PR now run in under 20s.
> Test PERMIT_DOCKER=connected-networks by sending an email from second network

- target/start-mailserver.sh
Having multiple nameservers set in `/etc/resolv.conf` currently results in a malformed opendkim configuration and opendkim performing a crash loop.
Given the file `/etc/resolv.conf`:
```
nameserver 1.2.3.4
nameserver 2.3.4.5
nameserver 3.4.5.6
```
The following `/etc/opendkim.conf` configuration lines are created on startup (which are malformed):
```
Nameservers 1.2.3.4
2.3.4.5
3.4.5.6
```
This fix merges the multiple lines and delimits them using `,`, just as opendkim requires:
```
Nameservers 1.2.3.4,2.3.4.5,3.4.5.6
```
> Fixed opendkim config on multiple nameservers

- target/start-mailserver.sh
Added `-f` to force `rm` to succeed if there is no file to delete (normal case) with one dir. Minimal change, would have been cleaner to remove the `rm` but as it is I prefer to keep it if I have missed something.
> Fixed bug when dh.pem/dhparam.pem exists with ONE_DIR

- test/tests.bats
The login tests regularly fail and it is not clear why. With assert_output we can hopefully get some clues.
> Use assert_output for better diagnostics of failures

- Dockerfile
Switch repo and fix broken configuration.
> Use Dovecot repo to fix cve-2019-11500 take two

- Makefile
Sometimes anonymous containers remain after cleanup, generalize to remove all docker-mailserver:testing and the ldap container.
> Generalize clean to remove all matching containers

- test/test_helper/common.bash
The exits would prevent the printing code from running. Thus we would get a failed test but no error message.
> Fix missing error output from timeout

- target/start-mailserver.sh
Reorder functions in start-mailserver.sh to apply the overrides after the other changes.
> Moved Postfix overrides last to fix #1143

- target/start-mailserver.sh
Second attempt, set REPORT_RECIPIENT to postmaster for use later. Skipped that before as REPORT_RECIPIENT was intended only for backwards compatibility, but it broke down when combined with the new options.
> Set REPORT_RECIPIENT to postmaster when 0

- CHANGELOG.md
CHANGELOG.md was not updated with the last release. To avoid confusion I added 6.2.0+.
> Added section "6.2.0+" to CHANGELOG.md

- CONTRIBUTING.md
If developers only run make when there is a test failure the clean may not run, so 'make clean all' should be the safe mode to run the tests.
I got several name conflicts for /mail before i discovered that i need to call `make clean` after a failed build / test.
This is one of the errors i got:
```
docker run --rm -d --name mail \
-v "`pwd`/test/config":/tmp/docker-mailserver \
-v "`pwd`/test/test-files":/tmp/docker-mailserver-test:ro \
-v "`pwd`/test/onedir":/var/mail-state \
-e ENABLE_CLAMAV=1 \
-e SPOOF_PROTECTION=1 \
-e ENABLE_SPAMASSASSIN=1 \
-e REPORT_RECIPIENT=user1@localhost.localdomain \
-e REPORT_SENDER=report1@mail.my-domain.com \
-e SA_TAG=-5.0 \
-e SA_TAG2=2.0 \
-e SA_KILL=3.0 \
-e SA_SPAM_SUBJECT="SPAM: " \
-e VIRUSMAILS_DELETE_DELAY=7 \
-e ENABLE_SRS=1 \
-e …
```
> Add a hint to run make clean all

- .travis.yml
- Dockerfile
- Makefile
- hooks/build
- test/mail_with_ldap.bats
Can be retrieved by calling e.g. `docker inspect tvial/docker-mailserver:testing`
Sample output:
```
$ docker inspect -f '{{ range $k, $v := .ContainerConfig.Labels -}}
> {{ $k }}={{ $v }}
> {{ end -}}' tvial/docker-mailserver:testing
maintainer=Thomas VIAL
org.label-schema.description=A fullstack but simple mailserver (smtp, imap, antispam, antivirus, ssl...)
org.label-schema.name=docker-mailserver
org.label-schema.schema-version=1.0
org.label-schema.url=https://github.com/tomav/docker-mailserver
org.label-schema.vcs-ref=7580aec
org.label-schema.vcs-url=https://github.com/tomav/docker-mailserver
org.label-schema.version=v6.1.0-111-g7580aec
```
> Provide version information through labels

- README.md
Old system requirements don't work as ClamAV alone can consume almost 1G.
> Updated system requirements, see #1224

- Makefile
- target/check-for-changes.sh
- target/start-mailserver.sh
- test/mail_special_use_folders.bats
- test/test-files/nc_templates/imap_special_use_folders.txt
- test/tests.bats
Test added. See PR #1297
_According to Dovecot configuration /etc/dovecot/conf.d/15-mailboxes.conf
Drafts, Junk, Trash and Sent folders will be created on the fly (reference documentation: https://wiki.dovecot.org/MailboxSettings)_
> Removing unnecessary maildir folders creation

- Makefile
- config/user-patches.sh
- config/user-patches.sh.dist
- target/start-mailserver.sh
- test/config/user-patches/user-patches.sh
- test/tests.bats
As @erik-wramner suggested in https://github.com/tomav/docker-mailserver/issues/1281 I created this pull request.
Sadly I wasn't able to test with the current tip of master. Error while starting:
`2019-10-07 20:45:23,793 INFO spawned: 'mailserver' with pid 8`
`supervisor: couldn't exec /usr/local/bin/start-mailserver.sh: ENOENT`
`supervisor: child process was not spawned`
This is my first pull request. Feel free to inform me whenever I was doing domething wrong.
> Added optional file user-patches.sh for own patches without recompiling

- test/config/fetchmail.cf
- test/tests.bats
on hosts that belong to wildcard domains pop3.example.com might
actually resolve to pop3.example.com.[mydomain.com] and give a valid ip
the return code of fetchmail then no longer is 11 (dns failure) but
something else (2 for socket error in our case)
to make sure we always get return code 11 we use the domain name
pop3.example.com. that is not allowed to be resolved to a subdomain.
Info @wt-io-it
> fix: fix test setup.sh debug fetchmail on wildcard domains

- setup.sh
- test/tests.bats
When running tests in Gitlab CI they fail because currently docker commands are hardcoded with `-ti` argument. This gives the following errors:
```
not ok 182 checking amavis: VIRUSMAILS_DELETE_DELAY override works as expected
not ok 183 checking amavis: old virusmail is wipped by cron
not ok 184 checking amavis: recent virusmail is not wipped by cron
```
This fix only passes `-ti` if a TTY was detected in setup.sh and skips the `-ti` in the failing tests where it is not necessary.
Info @wt-io-it
> fix: dont use TTY in docker if not present, rem TTY necessity in tests

- setup.sh
As what I want in #1322, New setup.sh could automatically decide which CRI should it use and work normally with podman. 
I will write a new wiki about how to manually install docker-mailserver with podman CLI and systemd tomorrow to make this function have minimum support.
Then I will slowly write a standalone install&update management script for podman and a kubernetes YAML for autodeploy.
> Add podman support to setup.sh

- README.md
These are a couple of things that work but got me losing lots of hours. Let me add them to README:
1. Fix #1330 explaining that plus addressing works out of the box.
2. Explain that DEFAULT_RELAY_HOST will fail to authenticate with RELAY_USER and RELAY_PASSWORD if you forgot the brackets.
@Tecnativa TT20505
> Document plus addressing and DEFAULT_RELAY_HOST format

- README.md
- env-mailserver.dist
- target/start-mailserver.sh
This will allow to forward safely any email from any host, no matter how strict their SPF policy is, by setting `SRS_SENDER_CLASSES=envelope_sender,header_sender`.
@Tecnativa TT20505
> Allow to configure SRS sender classes easily

- target/start-mailserver.sh
Fixes missing executable permissions for sieve-pipe scripts (see #1376).
> Add executable flag for scripts in /usr/lib/dovecot/sieve-pipe

- target/fail2ban/filter.d/dovecot.conf
* Replace deprecated, undocumented fail2ban feature ```(?P<host>S*)``` with
supported host match ```<HOST>```.
* Fixes ```No failure-id group in '(?: pop3-login|ima ...``` fail2ban dovecot filter
error message.
* See: https://github.com/fail2ban/fail2ban/issues/2130
> Fix broken fail2ban dovecot filter; use <HOST>.

- env-mailserver.dist
- target/start-mailserver.sh
By default, spam is quarantined. However, many people want to be able to view missed SPAM. To do this, this pull request adds an option to place the spam in the inbox, after adding the Spamassassin headers, and then allows the user to sort it automatically as desired, for example, by automatically moving it to a specific SPAM folder with a SIEVE rule.
**This does not change the default operation**
> Add an option to place spam in the inbox, and then sort the mail by a sieve rule

- setup.sh
Calling setup.sh from other scripts fails, for example when adding a new mailbox:
the input device is not a TTY
> Allow calling setup.sh from other scripts

- Dockerfile
- README.md
- config/filebeat.docker.yml
- docker-compose.filebeat.yml.dist
- target/start-mailserver.sh
Filebeat configuration is done through _Hints based autodiscover_ (following [Elastic](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html) practice).
Nevertheless, I have decided to change the default behavior (logs from all containers) in order to only log from mailserver (I guess some people can run other containers and do not want to push all the logs to filebeat).
**Filebeat with local ELK container:**
- `docker-compose.elk.yml.dist`: updated with the new filebeat container
**Filebeat forwarding to remote ELK:**
- `docker-compose.filebeat.yml.dist`: new file for those who only need filebeat (remote elk)
- `config/filebeat.docker.yml` to update with ELK server IP
Any references to filebeat previous implementation are removed.
> Filebeat in its own container

- README.md
- env-mailserver.dist
- target/start-mailserver.sh
Setting `inet_protocols = ipv4` is almost a requirement when running behind Docker. Provide a way to make it easy.
@Tecnativa TT22925
> Allow to set comfortably inet_protocols

- target/start-mailserver.sh
I opted for the v320.pre configuration, because it is the newer of the two configs that point to the related plugin. 
I activated the plugin in both clauses to ensure the case when a users only likes to opt in for one of the options.
> activate shortcircuit plugin if requested, fixes #1442

- target/start-mailserver.sh
When running docker-mailserver in [podman](https://podman.io) (which works nicely otherwise), I am getting this warning from amavis in my log:
```
2020-03-24 14:42:39,337 INFO spawned: 'amavis' with pid 1275
2020-03-24 14:42:40,339 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Mar 24 14:42:41 mail amavis[1275]: starting. /usr/sbin/amavisd-new at mail.**** amavisd-new-2.10.1 (20141025), Unicode aware
Mar 24 14:42:42 mail amavis[1275]: Net::Server: Group Not Defined.  Defaulting to EGID '111 111'
Mar 24 14:42:42 mail amavis[1275]: Net::Server: User Not Defined.  Defaulting to EUID '109'
Mar 24 14:42:42 mail amavis[1275]: (!!)FATAL: Config file "/etc/amavis/conf.d/61-dms_auto_generated" is writable, UID 109, EUID 109, EGID 111 111
Mar 24 …
```
> amavis: fix config permission

- Dockerfile
Some packages from the base image are upgradable. For example, that's the case for `libgnutls30` at the moment.
> Upgrade packages

- Dockerfile
`/etc/cron.weekly/fstrim` does not exist, so no need to remove it.
> Cleanup obsolete file removal

- Dockerfile
1. "AllowSupplementaryGroups false" is no longer present in /etc/clamav/clamd.conf, therefore the command does not work anymore.
2. Since Clamd 0.100.0, "AllowSupplementaryGroups" is deprecated. See: https://blog.clamav.net/2018/04/clamav-01000-has-been-released.html
"Deprecation of the AllowSupplementaryGroups parameter statement in clamd, clamav-milter, and freshclam. Use of supplementary is now in effect by default."
> AllowSupplementaryGroups change removed

- README.md
Documentation improvement based on prior stale PR and discussions at https://github.com/tomav/docker-mailserver/pull/1124
- Avoids historical ambiguity of SSL/TLS, if users aren't famliar with these ports, they primarily want to know their purpose and which ones are secure.
- Establishes that STARTTLS *may* be insecure, and how it's configured for `docker-mailserver` on a best effort to be secure and compliant.
- Clarifies that port 25 is not only for receiving external/inbound email, while raising awareness of a common issue for sending outgoing email, with encouragement for submission ports for MUA/MSA to submit email for delivery my the MTA.
- Clearly communicates port 465 as a submission port for implicit TLS, as there is much outdated/conflicting information about it's history. …
> chore: Clarify exposed ports section on README

- target/postfix/main.cf
`smtpd_tls_security_level` has replaced this config parameter. `smtpd_use_tls` has no relevance in the config anymore.
See: http://www.postfix.org/postconf.5.html#smtpd_tls_security_level
> this overrides the obsolete parameters `smtpd_use_tls` and `smtpd_enforce_tls`.
> chore: Remove obsolete postfix parameter `smtpd_use_tls`

- target/postfix/main.cf
Reduce opportunities for a potential CPU exhaustion attack with `NO_RENEGOTIATION`
Related: https://github.com/tomav/docker-mailserver/pull/1474#discussion_r417773285
See https://en.wikipedia.org/wiki/Resource_exhaustion_attack
>  Reduce potential CPU exhaustion attack with `NO_RENEGOTIATION`

- target/dovecot/10-mail.conf
Seen dovecot-sieve is always enabled, setting `maildir_stat_dirs = yes` permits to avoid  `/var/mail/domain.tld/user/.dovecot.sieve` (symlink) to be treated as a directory (default behavior).
According to https://github.com/Mailu/Mailu/issues/143#issuecomment-274596931, there is no noticeable impact when this is enabled.
An advanced user could eventually set `maildir_stat_dirs=no` in `config/dovecot.cf` if sieve is not used at all.
Fix https://github.com/tomav/docker-mailserver/issues/1480.
> Prevent sieve symlink to be evaluated as a directory by dovecot

- Dockerfile
- README.md
- env-mailserver.dist
- target/amavis/conf.d/49-docker-mailserver
- target/dovecot/90-sieve.conf
- target/dovecot/sieve/before.spam.sieve
- target/start-mailserver.sh
- test/mail_spam_bounced.bats
- test/mail_spam_junk_folder.bats
This PR is related to https://github.com/tomav/docker-mailserver/issues/1396
Features:
- Fix `SPAMASSASSIN_SPAM_TO_INBOX` behavior
- `MOVE_SPAM_TO_JUNK=1` permits to move spams to Junk folder using a global sieve rule
- Warning raised when `SPAMASSASSIN_SPAM_TO_INBOX=0`
- Tests
`MOVE_SPAM_TO_JUNK=1` will allow [SpamAssassin Lear](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#how-can-i-make-spamassassin-learn-spam) to work. 
~TODO:~
- ~README update: strong warning about the default behavior of spam bouncing~
fix https://github.com/tomav/docker-mailserver/issues/1396
> Feature: Spam to Junk folder

- target/postfix/main.cf
To prevent announcing software or version to malicious people or scripts, it is advised to hide such information.
This information is provided as part of the Lynis community project. It is related to Lynis control MAIL-8818 and should be considered as-is and without guarantees.
https://cisofy.com/lynis/controls/MAIL-8818/
> CISOfy/lynis MAIL-8818 - Postfix information leakage

- Dockerfile
Freshclam is not run as daemon. Fix #1507
> Fix #1507 - Do not try to reload freshclam daemon after log rotation

- setup.sh
Problem: `setup.sh` fails, if more than one container uses `CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]`
Current container/image name detection: List all containers, grep for "supervisor".
New approach: List container, with label `org.label-schema.name="docker-mailserver"`
> Improve container/image name detection

- target/start-mailserver.sh
Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>
This fixes shell expansion for dovecot variables by adding quotes. I saw this bug while trying to use a ldap bind dn with a space in it.
> Fix dovecot variable with whitespace

- target/start-mailserver.sh
This is a pull request to allow postfix SASL account to contain hashes (#).
> Fix sasl_password generation to allow passwords containing hashes

- target/helper_functions.sh
@MichaelSp made a great PR #1553 supporting acme.json from traefik. 
However, if `acme.json's` `Certificates[x].domain.sans === undefined` python will crash and the keys won't be added to `/etc/letsencrypt/live/"$HOSTNAME"/key|fullchain.pem`.
In my case this (`sans === undefined`) is true for all my certificates in `acme.json`; I just have the `main`-entry.
My logs when I start `docker-mailserver`:
```
[...]
Initializing setup
Checking configuration
Configuring mail server
Traceback (mosat recent call last):
File "<string>", line 1, in <module>
File "<string>", line 1, in <lambda>
KeyError: 'sans'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "<string>", line 1, in <lambda>
KeyError: 'sans'
Traceback (most recent call last):
File "<string>", line 1, in …
```
> fix: extractCertsFromAcmeJson fails if "sans" not in Certificates.domain.main

- README.md
Added as an example SASLAUTHD_LDAP_FILTER. 
I'm going to add full example with docker-openldap to the ldap wiki page. Thanks.
> Add SASLAUTHD_LDAP_FILTER to ldap example

- README.md
- setup.sh
Following #1590, I re-wrote and refactored `setup.sh` to
- make shellcheck happy
- improve the overall readability of the script
- make the script consistent
**This PR obsoletes** #1258.
Looking at #1258, I adopted some changes, namely `set -eu` and the use of default values. This PR has the podman changes already in it and does therefore not need to be rebased. Looking at the use of `set -eu`, I am really not sure whether this is the best solution to be honest, and I would like to hear an opinion on this.
Furthermore, I restructured the script, setting description and default values in the beginning, followed by all functions. I believe this to be more consistent.
I also included the changes to `README.md` to reflect what @fbartels already did in #1258.
Not sure whether I made (one or …
> major refactoring for setup.sh (#1590)

- target/check-for-changes.sh
- target/helper_functions.sh
- target/start-mailserver.sh
- test/config/relay-hosts/postfix-virtual.cf
- test/mail_ssl_letsencrypt.bats
- test/mail_with_relays.bats
- test/tests.bats
I started this branch to enable relaying through virtual account domains (before, only domains found in postfix-accounts.cf and postfix-relaymap.cf were taken into account). I bumped into some bugs along the way so I ended up having to do a bit of fixing and refactoring (see first two commits).
> Populate relayhost_map from virtual accounts (and other fixes)

- .travis.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Dockerfile
- Makefile
- README.md
- setup.sh
- target/check-for-changes.sh
- target/fail2ban-wrapper.sh
- target/helper_functions.sh
- target/postfix-wrapper.sh
- target/postsrsd-wrapper.sh
- target/start-mailserver.sh
- target/supervisor/conf.d/supervisor-app.conf
This PR includes the first half of #1599, i.e. everything that is not `start-mailserver.sh`.
- outsourced badges-links in `README.md` to clean this section up
- refactored `.travis.yml` with Prettier and added **shellcheck capabilities**
- refactored Makefile to make it verbose where it should be and added a **shellcheck target**
- refactored all scripts in `target/` (except `start-mailserver.sh`)
- added **coding style guidelines** to `CONTRIBUTING.md` so everyone can and must adhere to consistent guidelines
- `start-mailserver.sh` had to be touched due to renaming of functions
- added a table of contents to Markdown documents
Bash scripts are now streamlined and follow a certain paradigm where strictness is key.
TravisCI will now check scripts with shellcheck, and throws an error if …
> Changes from #1599 without `start-mailserver.sh`

- setup.sh
This is nothing more than a fix for #1603 regarding the use of "${CRI}" instead of `docker` to make `podmand` work.
> Fix for #1603

- CONTRIBUTING.md
- Makefile
- target/dovecot/scripts/quota-warning.sh
- target/start-mailserver.sh
This one is rather a blue whale. I completely refactored `start-mailserver.sh`. Therefore, it is now included into `shellcheck`. This was indeed a slow decend into madness.
- completely refactored `start-mailserver.sh`
- adjusted Makefile to check this script too
@erik-wramner I accidentally merge-commited all commits from #1601; I will squash them next time. I'm sorry for the inconvenience.
> Complete refactoring for `start-mailserver.sh`

- CODE_OF_CONDUCT.md
- README.md
- env-mailserver.dist
- setup.sh
- target/helper_functions.sh
- target/start-mailserver.sh
This PR adds the possibility to use a network interface of choice. When using Kubernetes with Host Networking, this was an issue as `eth0` was the default and not changeable.
> added option to use non-default network-interface, resolves #1227

- target/start-mailserver.sh
Dovecot uses /etc/dovecot/ssl/dovecot.{pem,key} instead of self-signed certs from ./config because of redundant spaces in `sed` commands
> fix: use self-signed cert for dovecot

- target/start-mailserver.sh
Another small PR in my efforts to get the logs clean. The documentation states that for the postfix and logwatch reports, we should set PFLOGSUMM_TRIGGER and LOGWATCH_INTERVAL to empty (the defaults) to not generate those reports. When doing this, the functions _setup_mail_summary and _setup_logwatch get called and generate the erroneous output:
Error PFLOGSUMM_TRIGGER not found in _setup_mail_summery
Warning LOGWATCH_INTERVAL not found in _setup_logwatch 
This PR corrects the start-mailserver.sh script to not call those function in the case that we are not generating reports. I tested it with a container build and run both with and without the changes and the log lines disappear when the changes are present.
> silence errorneous output when not generating reports

- target/bin/fail2ban
- test/mail_fail2ban.bats
This PR closes #1677
**Notice**: I changed the `test/mail_fail2ban.bats` file **back** to its original state with very very minor adjustments (inserting a comma, adding a whitespace, etc.).
> F2B script unusable - fixes #1677

- README.md
Added docs for missing DOVECOT_* environment variables:
- DOVECOT_BASE
- DOVECOT_DEFAULT_PASS_SCHEME
- DOVECOT_DN
- DOVECOT_DNPASS
- DOVECOT_HOSTS
- DOVECOT_LDAP_VERSION
- DOVECOT_AUTH_BIND
Fixes: #1681
> Create docs for missing DOVECOT vars in README.md

- target/helper-functions.sh
Hi,
[start-mailserver.sh](https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L1113
) checks if private key "privkey.pem" or "key.pem"
but [helper-functions.sh](https://github.com/tomav/docker-mailserver/blob/master/target/helper-functions.sh#L204) monitors only key.pem 
My certbot generates only "privkey.pem" thats why, there could be issues while updating private key.
> Add additional pem file for _monitored_files_checksums

- README.md
- mailserver.env
- target/start-mailserver.sh
Follow up of: #980
Fixes: #1704
- SASLAUTHD_LDAP_TLS_CACERT_FILE => ldap_tls_cacert_file
- SASLAUTHD_LDAP_TLS_CACERT_DIR => ldap_tls_cacert_dir
- SASLAUTHD_LDAP_PASSWORD_ATTR => ldap_password_attr
- SASLAUTHD_LDAP_AUTH_METHOD => ldap_auth_method
- SASLAUTHD_LDAP_MECH => ldap_mech
Note: actually I have to have 2 values for the `userPassword` attribute in my LDAP because sasl will not authenticate using my ssha256 stored password value, this pull-request is my hope to address my current issue.
Documentations used:
- https://opensource.apple.com/source/passwordserver_sasl/passwordserver_sasl-209/cyrus_sasl/saslauthd/LDAP_SASLAUTHD.auto.html
- https://github.com/winlibs/cyrus-sasl/blob/master/saslauthd/LDAP_SASLAUTHD
- https://blog.sys4.de/cyrus-sasl-saslauthdconf-man-page-en.html
- …
> Add more config options to saslauthd.conf

- target/helper-functions.sh
- target/start-mailserver.sh
- test/config/letsencrypt/acme.json
As I wanted to setup TLS with certificates provided by traefik I ran into two small bugs:
The first was a python exception. I have an acme.json containing sections which look like:
```
"httpChallenge": {
"Account": null,
"Certificates": null
}
```
The script didn't test if `Certificates` was `null`.
The second problem was that the environment variable `SSL_DOMAIN` was only used while watching for changes in the acme.json, not during start-up.
Both bugs are fixed with this PR.
> Small fixes for extracting certs from the acme.json file

- Dockerfile
- README.md
- target/postfix/main.cf
- Modify Dockerfile to comment out noisy/errant kernel logging line in /etc/rsyslogd.conf
- Add lines in README.md that prompt users to create an alias that captures messages to postmaster.
- Add commented line in /etc/postfix/main.cf to easily set 'myorigin=$mydomain' if desired.  Then e.g. postmaster emails will be addressed from "postmaster@domain.tld" instead of "postmaster@host.domain.tld".  This may require a regex or an additional or modified virtual alias for postfix to accept mail from such an address.  I have not documented that in these patches.  If people watch mail.log it will be clear.
> Get rid of syslogd warnings about kernel logging.

- config/user-patches.sh.dist
- target/start-mailserver.sh
- test/config/sieve-pipe/pipe_to_tmp
- test/config/user-patches/user-patches.sh
> Fix shebangs

- ENVIRONMENT.md
- target/scripts/helper-functions.sh
- target/scripts/start-mailserver.sh
- target/supervisor/conf.d/supervisor-app.conf
- target/supervisor/supervisord.conf
- test/mail_ssl_letsencrypt.bats
This one is important to me. What happened:
1. I added an environment variable which enables users to set the log-level
2. I re-enabled **color** :D See yourself:
3. Enhanced some output that did not use `_notify` but just `echo`
4. Improved supervisor configuration
5. Got rid of (confusing) `CRIT` messages during startup
**Here is why you should like and approve it**:
---
First of all, the log right now is **all over the place**. See:
``` INI
2021-01-21 00:01:16,377 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-01-21 00:01:16,377 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
2021-01-21 …
```
> Improve logging significantly – color is back!

- .github/workflows/default_on_push.yml
- CONTRIBUTING.md
- README.md
Closes #1759, replaces #1762 and introduces the new tagging convention of the docker images.
As discussed by the project maintainer team this PR brings in the new tagging convention:
| Event           | Ref                                       | Commit SHA | Docker Tags                         |
|--------------|-------------------------------|----------------|-------------------------------|
| `push`          | `refs/heads/master`             | `cf20257`       | `edge`                    |
| `push`          | `refs/heads/stable`              | `cf20257`        | `stable`                                |
| `push tag`    | `refs/tags/1.2.3`                 | `ad132f5`       | `1.2.3`, `1.2`, `1`, `latest`        |
| `push tag`    | `refs/tags/v1.2.3`                 | `ad132f5`       | …
> Change tag convention and allow multiple registries

- CONTRIBUTING.md
- setup.sh
- test/linting/lint.sh
`$_` returns the last argument to the previous command.
Example: `false foo`
` $_` returns "foo"
`$BASH_COMMAND` returns the failing command and argument(s) "false foo"
> Replace $_ in error trap

- ENVIRONMENT.md
When you read the markdown on github, the underscore by default just causes the word to be italic - when you blindly copy that configuration, it won't work, because you don't see the underscore prefix/suffix.
> Escaped the underscore of SCORE

- Makefile
- target/scripts/check-for-changes.sh
- target/scripts/start-mailserver.sh
- test/test-files/email-templates/existing-user3.txt
- test/tests.bats
This allows you to add for example
|userdb_mail=mbox:~/mail:INBOX=~/inbox
to the end of an account to have a different mailbox configuration.
> Support extra user_attributes in accounts configuration

- Dockerfile
- target/scripts/start-mailserver.sh
SASL is now disabled correctly. The `Dockerfile` has been adjusted to not show the `delaying debconf because apt-utils is not installed` error anymore. `function _misc_save_states` was refactored too as it was in an unacceptable state. Especially proud of the inline variable substitutions that got rid of `echo ... | sed ...`.
Fixes #1796
---
PS: I like the new template :D
> Enhancement for function _setup_postfix_sasl fixing #1796 & More

- .github/workflows/default_on_push.yml
- .github/workflows/linting.yml
- .github/workflows/test_merge_requests.yml
In this PR I added the functionality to our CI/CD pipelines to exclude some files to trigger the workflow.
Basically i added the following lines:
```
paths-ignore: 
- '**.md'
- 'LICENSE'
- '.github/**'
```
Imho this change can save up (waiting)time of unnecessary workflow runs as a change or hotfix on the excluded files will **never** impact the image. Furthermore I think it is possible to exclude even more files as they won't affect the image as well but I want your opinion on the topic itself and then the files that can be excluded too to not miss anything important.
The files that could be also excluded:
- `docker-compose.yml`
- `compose.env`
- `mailserver.env`
- `setup.sh`
> Exlude files from triggering workflows

- setup.sh
- target/bin/delmailuser
Mailbox contents should be deleted properly now when using `./setup.sh email del <user@domain.tld>`.
Fixes #1808
> Rewrite of `delmailuser` to enable proper account deletion (again)

- test/tests.bats
Hotfix of this issue that appeared after some refactoring of setup.sh and the open-dkim script: https://github.com/docker-mailserver/docker-mailserver/pull/1812#discussion_r578668242
Also provided via PR as changes to tests are not run in CI if pushed directly on master.
```
```
> fix: dkim help message test

- Dockerfile
Remove unnecessary/dangerous `--fix-missing` option in build process.
From the `apt-get` man page:
`Ignore missing packages; if packages cannot be retrieved or fail the integrity check after retrieval (corrupted package files), hold back those packages and handle the result.`
I cannot imagine a case, where we would want that behavior.
> Remove fix-missing

- target/scripts/start-mailserver.sh
Missed the merge window when addressing [this feedback separately](https://github.com/docker-mailserver/docker-mailserver/pull/1801#discussion_r579870882).
It just standardizes the `sed` substitution delimiter throughout the file to use `|`.
There's an additional comment regarding `SSL_TYPE=''` which may cause unexpected behaviour with internal config if containers are restarted in a manner that persists the config files but `SSL_TYPE` was changed inbetween. I'll be refactoring the support in future for `SSL_TYPE` and will address it then.
Style guide related.
> chore: Use consistent `sed` substitution delimiters in `start-mailserver.sh`

- target/scripts/start-mailserver.sh
While REPORT_RECIPIENT=1, reports were sent to 1@ instead of postmaster@.
It happened because condition has never matched.
Must be some [migration](/docker-mailserver/docker-mailserver/blame/c1a6bd9d3de61429bad067ce72285af7599621c3/target/scripts/start-mailserver.sh#L395) leftovers.
Fixes #1829
> Fix REPORT_RECIPIENT=1 behavior

- target/scripts/startup/fixes-stack.sh
- target/scripts/startup/setup-stack.sh
Provides the necessary hotfixes for the startup problems mentioned in the @docker-mailserver/maintainers team and in #1834.
This may be incomplete. Suggestions are welcome.
Fixes #1843
1. Partial rollback in `_setup_dkim` which may gobble setups of persons not using openDKIM
2. `_fix_var_mail_permissions` should no return normally again and should therefore not introduce failures
Does the `_setup_supervisor` restart supervisor if the loglevel is not `warn`? Did this work before? Why does is now seem like supervisor is restarted endlessly (looking at #1834).
> first (may-be) fixes for v9.0.0 startup problems

- README.md
`setup.sh -h` was replaced with `setup.sh help` somewhere along the line.  Just reflecting change in README
> Fix update docs to use `setup.sh help`

- docker-compose.yml
It's probably intended behaviour, that the container uses the same timezone as the host. If nothing is configured, UTC is used.
Without a proper configured timezone, e.g. log files will have time offset.
Inspired by #1849
> Use time zone from host

- docker-compose.yml
Removing the quotation marks in the docker-compose port section, can lead to unexpected behaviour.
More Information:
- https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports
- https://yaml.org/type/float.html
Fixes #1858 and other similar
> yaml base-60 float warning added

- target/bin/generate-ssl-certificate
If you don't mount the ssl directory or set SSL_CFG_PATH to something else then the directory needs to be created with parents.
> Make directory with parent directories

- setup.sh
- target/bin/addmailuser
- target/bin/delmailuser
Bugfix and small improvement for `setup.sh`
Fixes #1808
- [] I have made corresponding changes to the documentation (README.md or ENVIRONMENT.md or the Wiki)
> fix for #1808

- setup.sh
- EXIT trap removed
- `_unset_vars` function removed
-  ~~`_get_current_directory` function replaced with simpler approach~~
- variable list ordered
- renamed `USING_SELINUX` to `USE_SELINUX` like the rest of the `USE_` stuff.
Partly discussed here: #1885
> setup.sh improved

- docker-compose.yml
It's always best practice, to shutdown services graceful. `docker-compose down/stop` sends [SIGKILL after 10 seconds](https://docs.docker.com/compose/compose-file/compose-file-v3/#stop_grace_period). In some environments, this is not enough time for the services to stop.
`docker-compose` will now wait up to 1 minute before sending SIGKILL, which should be enough time.
> Add stop grace period

- Dockerfile
- ENVIRONMENT.md
- docs/content/config/advanced/auth-ldap.md
- target/postfix/ldap-senders.cf
- target/scripts/startup/setup-stack.sh
- test/mail_with_ldap.bats
- test/test-files/auth/ldap-smtp-auth-spoofed-sender-with-filter-exception.txt
This adds an environment variable `LDAP_QUERY_FILTER_SENDERS` that determines if a user is allowed to use a specific identity to send an email - for example, we're using something like `(|(mail=%s)(mail=noreply@example.com))`, to allow users to send an email if they either have the mail address they want to send as or if they have the mail address noreply@example.com. This applies only if SPOOF_PROTECTION=1.
~~Also, as suggested in #1340, this sets smtpd_sasl_local_domain to an empty string - it seems like without that it won't work, but I couldn't figure out the implications of that, so that might be worth discussing.~~ (that change has been reverted as the issue itself seems to have been fixed in the meantime)
If the environment variable is empty, the old sender …
> Add LDAP_QUERY_FILTER_SENDERS setting for spoof protection with LDAP

- ENVIRONMENT.md
- config/fail2ban-jail.cf
- mailserver.env
- target/fail2ban/jail.local
- target/scripts/start-mailserver.sh
- target/scripts/startup/setup-stack.sh
- test/config/fail2ban-jail.cf
- test/mail_fail2ban.bats
Further work from #1821.
- Introduce `FAIL2BAN_BLOCKTYPE`
**drop**   => drop packet (send NO reply)
reject => reject packet (send ICMP unreachable)
- Block IP for all ports now. The old behavior was to block the IP only for the affected port/service. This can be reverted via `config/fail2ban-jail.cf`
> Fail2Ban block behaviour

- docs/content/config/security/ssl.md
- target/scripts/startup/setup-stack.sh
- changed container name from `mail` to `mailserver` to streamline docs
- some braces around variables in Bash scripts were added
- changed Traefik's certificate section
- removed docs for Traefik v1 - we want everyone to use Traefik v2 from `9.2.0`
- **the wildcard certificate issue** in #1915 was addressed
- proper indentation was added
I have drafted a prerelease for `v9.2.0`. Have a look :)
1. Make sure the adjustments to `SSL_DOMAIN` are correct (by solving #1915)
> Adjusted documentation for service name and Traefik certificate issuance

- ENVIRONMENT.md
- target/dovecot/dovecot-ldap.conf.ext
- target/scripts/startup/setup-stack.sh
- test/mail_with_ldap.bats
According to https://doc.dovecot.org/configuration_manual/authentication/ldap/, the "uris" option has to be used when using LDAPS, while the "hosts" option seems to only work with STARTTLS. So, this PR fixes the problem that docker-mailserver can't be used with LDAPS.
The change is made in a way that allows backwards-compatibility with configurations that assume the "hosts" option to be set by LDAP_SERVER_HOST, in which case it's using "ldap://" as a default protocol if none is specified. The only change for the user is that LDAP_SERVER_HOST now supports specifying a protocol like "ldaps://...".
Fixes #1510
> Use dovecot's LDAP uris option instead of hosts (fixes #1510)

- target/supervisor/conf.d/supervisor-app.conf
Follow up for #1896. Increasing docker-compose stop grace period to 1 minute was pretty pointless, because supervisord also sends a SIGKILL after 10 seconds. This adds a stop grace period to supervisord also.
Fixes # (issue)
> Add supervisord stop grace period

- ENVIRONMENT.md
- docs/content/config/advanced/override-defaults/user-patches.md
- mailserver.env
- target/scripts/start-mailserver.sh
- target/scripts/startup/setup-stack.sh
- test/mail_disabled_clamav_spamassassin.bats
- test/tests.bats
Introduced `AMAVIS_LOGLEVEL` variable to control the log level. This way, one can control the verbositoy of Amavis. This can be of special importance when users post logs (for the first time) as they always post the (huge) Amavis log too. See #1944.
This is a "breaking" change, as the default of `0` (= warning) is new. We can merge this before releasing `10.0.0`. I can test this feature in my setup for a week if necessary,
> introduce variable to control Amavis' loglevel

- docs/content/config/advanced/mail-sieve.md
The sieve client of [Kmail](https://kontact.kde.org/components/kmail.html) works great with docker-mailserver, I propose to add it as sieve client to the documentation.
No code, just a documentation update.
> Add Kmail as sieve client

- docs/content/config/advanced/kubernetes.md
Heya!
I'm really sorry if the formatting is messed up for this. I spent about an hour trying to diagnose why a deployment into my Kubernetes cluster wasn't working. Had a bunch of 'operation not permitted' errors when attempting to start services.
Turns out CRI-O does not allow for chrooting inside a container anymore. It was changed in cri-o/cri-o@63b9f4ec986da267a18f73d4b1ef13282d103e00
I figured I'd update the documentation for anyone that might be having the same issue!
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] If necessary I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally …
> chore(docs): Update Kubernetes CRI-O Capability Description

- docs/content/config/security/ssl.md
We no longer support this method with `setup.sh` from v10 onwards (previously deprecated), `SSL_TYPE=self-signed` remains supported however.
Advice has been revised for users to provide their own self-signed cert or use an external tool with an example provided.
[Direct preview link](https://pullrequest-2021--dms-doc-previews.netlify.app/config/security/ssl/#self-signed-certificates).
Complimentary documentation update for the v10 deprecation of the shell script tool.
I have followed the new advice on a minimal setup, and a simple test on verification working with (run within the same container):
```sh
openssl s_client -CAfile /etc/postfix/ssl/cacert.pem -connect mail.example.test:587 -starttls smtp | grep 'Verification'
Verification: OK
Verification error: self signed certificate in …
```
> docs: SSL - Revise self-signed cert provisioning

- docker-compose.yml
- docs/content/faq.md
If we switch to bind mounts in the sample config, that will simplify backup/restore of DMS.
See also: #1906
This would also make the not 100% correct working script at https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-backups obsolete.
Backup/restore would then just be simple host commands `cp / mv`..
What do you think?
> Use bind mounts in sample config

- Dockerfile
> Similar to the problem that mail in a box had, the included /etc/postgrey/whitelist_clients is outdated by years, the last entry is from 2015. The official current version can be found at http://postgrey.schweikert.ch/pub/postgrey_whitelist_clients
Even the upcoming Debian 11 will not include an updated whitelist, so this should be merged.
Fixes #2040
> Update postgrey whitelist

- target/scripts/startup/fixes-stack.sh
On container start, `/var/run/supervisord.pid` is deleted by https://github.com/docker-mailserver/docker-mailserver/blob/80a0425adeee01f873b506bd9aa63eee2394ad95/target/scripts/startup/fixes-stack.sh#L12
This shouldn't be the case.
> Fix deletion of supervisord.pid

- Dockerfile
Use keyserver that still returns keys with user IDs
keys.gnupg.net doesn't return user IDs (without approval) and therefore gpg
doesn't accept keys from it.
Fixes #2050 
FYI @wt-io-it
> Use keyserver that still returns keys with user IDs

- Dockerfile
The `opendmarc` package in Debian Buster includes an SQL schema to automatically create a MySQL database on installation.  To do this, it has a dependency on `dbconfig-mysql` package which is installed during the build.  However, since `docker-mailserver` does not actually have a MySQL server running, this results in the following errors during the build process:
```
Setting up opendmarc (1.3.2-6+deb10u2) ...
dbconfig-common: writing config to /etc/dbconfig-common/opendmarc.conf
Creating config file /etc/dbconfig-common/opendmarc.conf with new version
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2).
unable to connect to mysql server.
error encountered creating user:
ERROR 2002 (HY000): Can't connect to local MySQL server through …
```
> Install dbconfig-no-thanks package

- Dockerfile
- docs/content/config/advanced/full-text-search.md
this PR updates Docker to install dovecot-fts-xapian.
unfortunately, that package is only available on `buster-backports` so either Docker needs to be updated to pull from backports or the build can use `bullseye-slim` as the base image (which is nearing stable release in July 2021).
currently, this PR introduces `bullseye-slim` which is a rather large change.
I imagine this project will eventually adopt bullseye given its long testing cycle and relative stability. If so, this PR can be merged with that branch.
With that said, I would be happy to use `buster-backports` as well and i have a working branch, if desired. That approach merely requires updating Docker to add to apt a new source pointing to buster backports before installing dovecot and other software.
Lastly, this PR also …
> add dovecot-fts-xapian

- target/supervisor/conf.d/supervisor-app.conf
https://github.com/docker-mailserver/docker-mailserver/pull/2104#discussion_r689431551
> reverted stopwaitsecs for postfix

- docs/content/examples/tutorials/mailserver-behind-proxy.md
Explicitly configure treafik not to terminate TLS for SMTPS
Fixes #
- [] Bug fix (non-breaking change which fixes an issue)
> Explicitly configure treafik not to terminate TLS for submissions

- target/bin/fail2ban
The `fail2ban` wrapper would show `No IPs have been banned` even when IPTables did not work. This is now shown and the script aborts.
Partly helps with #2169
> Update F2B wrapper to show possible errors with IPTables

- docs/mkdocs.yml
- DockerHub was invalid.
- GHCR serves a redirect, might as well update to that too.
> docs(fix): Update external registry links

- setup.sh
- test/linting/.ecrc.json
Cleans up `setup.sh` and makes it possible to use the script in a completely non-interactive way. Added `-R` flag. Moved ENV variables to the top, removed unnecessary functions and renamed functions.
This PR _should_ be the last one added to the `10.2.0` milestone. This PR is not a breaking change. Fixes a regression for SELinux (used `OPTARG` where `OPT` was actually correct).
Follow up on #2179
> make setup.sh completely non-interactive

- .github/workflows/scripts/docs/build-docs.sh
bump mkdocs-material to 7.3.0
it got released today and we now (theoretically) have the option to:
- Added support for sticky navigation tabs
- Added support for section index pages
- Added support for removing generator notice
> docs(deps): bump mkdocs-material to 7.3.0

- docs/content/config/security/ssl.md
This is a follow-up to https://github.com/docker-mailserver/docker-mailserver/pull/2206
The _Let's Encrypt_ section has been heavily revised. It includes the missing normalization for this section from the linked PR, and brings the section content up to date.
It is an initial pass and can probably be refined further. I've not yet fully verified the instructions work, only the `nginx-proxy` + `acme-companion` docker-compose example with staging certs works (_however `docker-mailserver` isn't compatible with this as FQDN directory name is prefixed by `_test_`_).
[Link to the TLS docs preview page for this PR](https://pullrequest-2209--dms-doc-previews.netlify.app/config/security/ssl/).
> docs: `ssl.md` - Revise letsencrypt section

- .github/workflows/linting.yml
This should resolve the issue of the lint workflow not being triggered by PRs opened via another workflow (`contributors.yml`).
This workflow will be triggered after the dependent workflow completes (regardless of status).
Resolves: https://github.com/docker-mailserver/docker-mailserver/pull/2218
> ci: Allow other workflows to trigger linting

- .github/workflows/contributors.yml
- .github/workflows/linting.yml
The lint workflow is not important for this PR, but a fixed requirement to pass for merging.
As this workflow is triggered by `schedule` or `workflow_dispatch`, it will not trigger other events such as `pull_request` for other workflows to respond to. The [earlier attempt was partially successful](https://github.com/docker-mailserver/docker-mailserver/pull/2220), the lint workflow did run, but it incorrectly associated the lint workflow run to the latest commit on `master` branch. 
Since the linting workflow is not important for this type of PR, we can pretend it was "skipped" and set the check status to "success". This is simpler than running the actual Lint workflow redundantly, which would require `workflow_dispatch` event triggering AFAIK to do correctly, but that has additional auth …
> ci: Fix lint check status update

- target/bin/fail2ban
I had the problem, that running the `fail2ban` script took ages to complete, because there were hostnames, that could not be resolved. There is no need for name resolution. This PR disables that.
> Disable name resolution in iptables check

- mailserver.env
docker compose 2.x complains with this error: "key cannot contain a space" or 
```
unexpected character "(" in variable name near "whitelist host after N successful deliveries (N=0 to disable whitelisting)\nPOSTGREY_AUTO_WHITELIST_CLIENTS=5\n\n#
```
when `POSTGREY_TEXT` value is something with spaces.
> Make it compatible with docker compose 2.x

- README.md
Because the container will now exit on startup failure if no accounts exits, we have to update the README's section for beginners. Furthermore, I added another section containing information about not using `docker start / stop` and about the help users can get by running the `setup help` command inside the container.
This issue is related, but only an example: #2232
> Update README to reflect changes of `v10.2.0`

- Makefile
- target/bin/open-dkim
- test/open_dkim.bats
This is extracted from https://github.com/docker-mailserver/docker-mailserver/pull/2245 as it does not need to be part of that PR.
- The internal var `DOMAINNAME` is used elsewhere in the project as a global, as this is a local var it should not use a name that could be mistaken as associated to the more widespread one.
- `opendkim-genkey` options made consistent:
- `--domain` is all lowercase, it shouldn't be uppercase.
- `--directory` should be used instead of the more ambiguous short option `-D`.
> chore: Housekeeping on the 'open-dkim' script

- Makefile
Extracted from [this open PR commit](https://github.com/docker-mailserver/docker-mailserver/pull/2245/commits/8ebbca3f24dea34375a4fe61232b4bce77da2b30) as it's not required for that PR.
@NorseGaud added this as an improvement for the test logs to include time measurements.
---
For the CI there is an a `CI` ENV that is detected so `bats` uses the `TAP` formatter. If you'd like to swap the test number with the fancy tick/cross symbols for pass/fail, we can additionally add `--pretty` (or --formatter pretty).
Version 1.5.0 of `bats` also [released about a week ago](https://github.com/bats-core/bats-core/releases/tag/v1.5.0).
Let me know if you'd like either of those additions added.
> ci(tests): Add timing measurement to output

- docker-compose.yml
- docs/content/config/security/ssl.md
This has been extracted from https://github.com/docker-mailserver/docker-mailserver/pull/2245 as it does not need to be part of that PR.
These changes have been discussed as part of the review from that PR. The additions are a mix of contributions from @NorseGaud and myself.
It's primarily the FQDN section, with a few extra corrections and for the Traefik section some rephrasing. Each change-set is scoped by individual commits.
> docs(ssl): Add an FQDN section

- docker-compose.yml
While I chose to keep the version with a note about it not being required, @casperklein has suggested we [remove the version from the example config entirely](https://github.com/docker-mailserver/docker-mailserver/pull/2268#discussion_r739633649).
> chore: Remove version key from `docker-compose.yml`

- .github/workflows/scripts/docs/build-docs.sh
- docs/content/config/environment.md
- docs/content/config/user-management/accounts.md
- docs/content/examples/tutorials/basic-installation.md
- docs/content/examples/uses-cases/forward-only-mailserver-with-ldap-authentication.md
This is a change originally from @NorseGaud in [his PR commit here](https://github.com/docker-mailserver/docker-mailserver/pull/2245/commits/77036f4510f7d4ba010461fb67d408a429a7d552). To ease review of that PR I'm pulling out anything that doesn't need to be in it.
---
Using `set -ex` will exit the script as soon as a non-zero exit code is returned, such as when the docker image fails building the docs due to `build --strict` catching broken links. This also removes the need for `|| exit` when changing directory.
This seems fine for a small script, but AFAIK an alternative fix is just adding `|| exit` to the end of the `docker run` command too? There appears to be advice [against adopting `-e` carelessly](http://mywiki.wooledge.org/BashFAQ/105), while others [encourage …
> ci(docs): Fail when build aborts from broken links

- target/scripts/startup/misc-stack.sh
A [PR in July 2017](https://github.com/docker-mailserver/docker-mailserver/pull/657) contained a fix for this but was rejected due to other changes proposed:
> Fixing permissions problems for `/var/mail-state/spool-postfix` when `ONE_DIR=1`:
> - `spool-postfix/maildrop` and `spool-postfix/public` folders must be owned by group `postdrop`
> - `spool-postfix/[dev/etc/lib/pid/usr]` permissions were not restrictive enough. They should be owned by the `root` user and `root` group.
I have looked at the source destination and the permissions remain the same. This PR carries over the ownership to the `ONE_DIR` location.
An alternative fix in future might be to use `rsync` which can copy over the contents with permissions and everything else retained. I'm not super familiar with the `ONE_DIR` …
> fix: `ONE_DIR=1` should keep correct permissions for `spool-postfix`

- target/postfix/master.cf
This was all [introduced by the original project author early on](https://github.com/docker-mailserver/docker-mailserver/commit/ef34462e34f2d6a46f8da9dc4c068c2186b8ea54) (April 2015), no explanation for it. Seems safe to remove.
- None of the paths they use as `argv` values exist.
- `uucp` doesn't seem relevant to the project. No justification for it, no issues or PRs in project history or codebase.
- `mailman` is for managing mailing lists, we do have issues requesting support in [May 2020](https://github.com/docker-mailserver/docker-mailserver/issues/1518) and [Nov 2016](https://github.com/docker-mailserver/docker-mailserver/issues/370). Debian 11 Bullseye also [no longer includes a `mailman` package](https://www.debian.org/releases/stable/amd64/release-notes/ch-information.en.html#notew …
> chore: Remove invalid/redundant config in Postfix `master.cf`

- .github/workflows/scripts/docs/build-docs.sh
bump mkdocs-material to 7.3.6
We no have the option to use titles for code blocks:
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-a-title
> docs(deps): bump mkdocs-material to 7.3.6

- target/scripts/startup/setup-stack.sh
Removes the quotation marks around the hostname in opendmarc.conf .
OpenDMARC includes the quotation marks in the hostname, and therefore the hostname no longer matches the header added by OpenDKIM. OpenDMARC then ignores the header and fails the authentication.
> Fix OpenDMARC verification

- target/scripts/startup/misc-stack.sh
See https://github.com/docker-mailserver/docker-mailserver/pull/2292#issuecomment-967044553
Fixes the problem where the debug log is messy in the `misc-stack.sh` section.
> Remove unnecessary `ls` from debug log

- target/scripts/check-for-changes.sh
- target/scripts/startup/setup-stack.sh
This addition is somewhat important for K8s users and _changes nothing_ in terms of functionality. We currently execute the `user-patches.sh` script with a shebang, making it executable beforehand if it wasn't to begin with.
Now, Bash will take the script and execute it. This change has therefore no implications on the actual execution of the `user-patches.sh` script.
**But for Kubernetes** users, this way of executing the script is the most comfortable one because all others are somewhat tiresome or involve unnecessary work! The explanation:
You would mount this script via a `ConfigMap` into the container. These files are by default not executable and one cannot change the permissions. One would need to specify the permissions for this `ConfigMap` but then you'd do this for all files of …
> make Bash start user-patches.sh

- target/scripts/helper-functions.sh
- test/mail_hostname.bats
This has been extracted from https://github.com/docker-mailserver/docker-mailserver/pull/2245 to simplify review.
These changes are the main focus of the original PR where the bulk of the discussion and investigation was oriented around.
Originally reworked by @NorseGaud with heavy refactoring by me afterwards.
---
Commits have been scoped with context via commit messages for ease of reviewing.
Summary of changes:
- Better logical flow, handling and inline documentation.
- Panic when `$HOSTNAME` is misconfigured.
- Heavy inline docs for maintainers to understand and be aware of related functionality.
- `SRS_DOMAINNAME` test should use `--domainname` not ENV `DOMAINNAME` (_reverted this fallback that was added from the [PR that originally introduced …
> refactor: Internal HOSTNAME and DOMAINNAME configuration

- mailserver.env
Tiny change to fix spelling in `mailserver.env`
> Fix tiny typo in mailserver.env

- .github/workflows/scripts/docs/build-docs.sh
- docs/mkdocs.yml
- docs/overrides/base.html
bump mkdocs-material to 8.0.2
Todos:
Main changes:
- Added support for code annotations
- Added support for anchor tracking
- Added support for version warning
- Added copyright partial for easier override
- Removed deprecated content tabs legacy implementation
- Removed deprecated seealso admonition type
- Removed deprecated site_keywords setting (unsupported by MkDocs)
- Removed deprecated prebuilt search index support
- Removed deprecated web app manifest – use customization
- Removed extracopyright variable – use new copyright partial
- Removed Disqus integation – use customization
- Switched to :is() selectors for simple selector lists
- Switched autoprefixer from last 4 years to last 2 years
- Improved CSS overall to match modern standards
- Improved CSS variable semantics for fonts …
> docs(deps): bump mkdocs-material to new major version 8

- .github/workflows/scripts/docs/build-docs.sh
Changelog:
- Added support for #only-light and #only-dark image hash fragments
- Fixed copy-to-clipboard adding blank lines when using line anchors
- Fixed code annotation directionality for right-to-left languages
- Fixed header title positioning for right-to-left languages
- Fixed admonition borders for right-to-left languages (8.0.0 regression)
- Fixed footer navigation link positioning (8.0.0 regression)
- Fixed footer navigation title breaking out of container when too long
- Fixed shrinking arrow in navigation title when too long
> docs(deps): bump mkdocs-material to v8.1.1

- CHANGELOG.md
- target/scripts/check-for-changes.sh
- target/scripts/helper-functions.sh
- test/mail_changedetector.bats
The `DYNAMIC_FILES` var was quote wrapped, treating all filepaths to create checksums for as a single string that would be ignored instead of processed individually.
Removed the quotes, and changed the for loop to an array which accomplishes the same goal.
This was discovered while investigating [#2321](https://github.com/docker-mailserver/docker-mailserver/issues/2321#issuecomment-994491231), but it's unclear if this will fix that issue.
---
This bug was introduced in https://github.com/docker-mailserver/docker-mailserver/pull/2279 with the `v10.3.0` release.
~~We may want to branch that release tag and cherry pick this commit from master to publish a bugfix (_as we've already merged `v11` changes to master, the bugfix branch is the only way to backport it I think?_).~~ (**RESOLVED:** …
> fix: Restore detection of letsencrypt certificate file changes

- .github/workflows/docs-preview-prepare.yml
- .github/workflows/handle_stalled.yml
- .github/workflows/linting.yml
- setup.sh
- target/bin/listmailuser
- target/bin/setquota
- target/scripts/check-for-changes.sh
- target/scripts/helpers/relay.sh
- test/linting/lint.sh
- test/mail_smtponly.bats
- test/permit_docker.bats
- test/tests.bats
Just updated the linter versions and fixed a few errors I found on the way. Not sure why there is no new 2.4.0 EdiitorConfig-Checker Image.
Fixes #
> Updated ShellCheck to `0.8.0` and Hadolint to `2.8.0`

- target/dovecot/60-stats.conf
(Running the latest `:edge` image.)
I accepted the `v10.4` PR too fast and got the paycheck :D I just went over my logs and saw the line
``` TXT
dovecot: auth: Error: stats: open(old-stats-user) failed: No such file or directory
```
so I had a look again. Turns out, the old stats plugin is deprecated and it suffices to disable the new Dovecot stats. The old stats plugin was opt-in (via `mail_plugins = $mail_plugins imap_quota`) but we have **not** configured this anywhere so the old stats were never active. I guess Dovecot gets confused when it encounters the config for the old plugin which is not even enabled.
Nothing serious but nothing that should be in your log either. I would like to see this in `v10.4` so there is no actual (semi-)regression on a stable release tag. Maybe someone …
> Removed Dovecot stats configuration for old statistics plugin

- .github/workflows/docs-preview-prepare.yml
- .github/workflows/docs-production-deploy.yml
The prepare workflow runs in an untrusted context already and thus should not have anything worthwhile to exploit.
However care should still be taken to avoid interpolating expressions into shell scripts directly that is data a user can control the value of. Especially to avoid any maintainer referencing an existing workflow from copying a risky snippet unaware of different security contexts for workflows.
In this case, as per Github Documentation and referenced issue comment, the PR title is user controllable data, which if directly interpolated into the shell script being run (as it previously was), allows for injecting commands to execute.
---
Additionally bumps the checkout action from `2.3` to `2.4` (_I only did this for the docs workflows, all the others still keep the checkout …
> ci(fix): Do not trust user controlled input

- target/scripts/startup/setup-stack.sh
When setting `SUPERVISOR_LOGLEVEL` e.g. to `info`, supervisord will be [restarted](http://supervisord.org/running.html#supervisorctl-actions) (don't get fooled by the term 'reload'):
https://github.com/docker-mailserver/docker-mailserver/blob/701037d3b2909db5b268ae4dbc171d70921600c3/target/scripts/startup/setup-stack.sh#L12-L23
The restart however, can take some time. While this time period, `start-mailserver.sh` continues to run until terminated by supervisord. This can lead to errors, if files are modified (by our numerous sed-operations).
When supervisord is completely restarted, also `start-mailserver.sh` is started again. Files that already have been modified by the first run, will now be reported as errors.
This is how a problematic log looks like (empty lines added for …
> Prevent race condition on supervisorctl reload

- config/dovecot.cf
- docs/content/config/advanced/override-defaults/dovecot.md
https://wiki.dovecot.org seems stale/outdated.  Various links on the dovecot wiki site indicate docs have moved to https://doc.dovecot.org.  Example: https://wiki.dovecot.org/BasicConfiguration
> Update links to dovecot docs

- test/security_tls_cipherlists.bats
The field name to check in JSON output was [recently changed for the cipherlist results](https://github.com/drwetter/testssl.sh/pull/2064), causing tests to fail.
---
This should resolve the current test failure for [an open PR](https://github.com/docker-mailserver/docker-mailserver/pull/2342). Although the change was 3 weeks ago, it's only appearing now I think as releases (or updated builds of `3.1-dev` rather) being published to DockerHub was handled manually, they [now have a paid subscription for automated builds](https://github.com/drwetter/testssl.sh/issues/1939#issuecomment-1003390156) which was announced in the past 12 hours, with new image updates.
It's unclear when the `3.2` release will arrive, but [`3.0` has seen a final / non-rc release back in …
> tests(fix): Align with upstream `testssl` field name change

- test/security_tls_cipherlists.bats
The TLS tests can fail, if `testssl` starts scanning, while the container is not fully started yet:
<details>
<summary>Failed tests</summary>
```
✗ checking tls: cipher list - rsa intermediate [25151]
(from function `assert_success' in file test/test_helper/bats-assert/src/assert.bash, line 114,
from function `compare_cipherlist' in file test/security_tls_cipherlists.bats, line 164,
from function `check_cipherlists' in file test/security_tls_cipherlists.bats, line 176,
from function `check_ports' in file test/security_tls_cipherlists.bats, line 90,
in test file test/security_tls_cipherlists.bats, line 47)
`check_ports 'rsa' 'intermediate'' failed with status 5
[ TASKLOG ]  mail.example.test is up and running
-- command failed --
status : 5
output : jq: error (at …
```
> Make TLS tests more reliable

- docs/content/config/environment.md
- mailserver.env
- target/scripts/start-mailserver.sh
- target/scripts/startup/setup-stack.sh
- test/mail_dnsbl.bats
- test/mail_with_postgrey.bats
This PR makes the usage of the postfix/postscreen DNS block lists optional.
Fixes issues like #1927
> Introduce ENABLE_DNSBL env

- target/bin/delmailuser
- target/bin/sedfile
- target/scripts/start-mailserver.sh
- target/scripts/startup/fixes-stack.sh
When restarting the container (`docker restart mailserver`), depending on someones setup, the following errors may be displayed:
```
rm: cannot remove '/etc/cron.d/clamav-freshclam': No such file or directory
Error: sed -i /^smtpd_recipient_restrictions = / s/, reject_rbl_client zen.spamhaus.org// /etc/postfix/main.cf
Error: sed -i -r -e s|^(MinProtocol).*|\1 = TLSv1| -e s|^(CipherString).*|\1 = DEFAULT@SECLEVEL=1| /usr/lib/ssl/openssl.cnf
Error: sed -i -r s|^(smtpd_tls_chain_files =).*|\1 /etc/dms/tls/key /etc/dms/tls/cert| /etc/postfix/main.cf
Error: sed -i -r -e s|^(ssl_key =).*|\1 </etc/dms/tls/key| -e s|^(ssl_cert =).*|\1 </etc/dms/tls/cert| /etc/dovecot/conf.d/10-ssl.conf
```
These errors are harmless and are only triggered, because the file deletion/modification already took place …
> Fix harmless startup errors

- docs/content/config/environment.md
- mailserver.env
- target/scripts/startup/setup-stack.sh
Follow-up to #2360, but using `/etc/logwatch/conf/logwatch.conf` as config file.
This *might* be considered to be a breaking change if someone relied on the fact that `REPORT_SENDER` wouldn't influence the sender address for logwatch reports. But when I started using this project, I was actually expecting it would.
> add env var `LOGWATCH_SENDER`

- .github/workflows/scripts/docs/build-docs.sh
bump mkdocs-material to v8.1.6 
[Changelog for v8.1.2](https://github.com/squidfunk/mkdocs-material/releases/tag/8.1.2)
[Changelog for v8.1.3](https://github.com/squidfunk/mkdocs-material/releases/tag/8.1.3)
[Changelog for v8.1.4](https://github.com/squidfunk/mkdocs-material/releases/tag/8.1.4)
[Changelog for v8.1.5](https://github.com/squidfunk/mkdocs-material/releases/tag/8.1.5)
[Changelog for v8.1.6](https://github.com/squidfunk/mkdocs-material/releases/tag/8.1.6)
All containing mainly improvements and regression fixes
> docs(deps): bump mkdocs-material to v8.1.6

- docs/content/config/security/fail2ban.md
When glancing through this docs page, I noticed two links weren't properly converted from markdown syntax, the links had a typo (`:` instead of `::`) at the bottom of the document where link definitions are grouped.
> docs: Fail2Ban - Fix links for rootless podman

- docs/content/config/advanced/kubernetes.md
The current image name is incorrect:
`docker pull docker.io/docker-mailserver/docker-mailserver:latest`
```
Error response from daemon: pull access denied for docker-mailserver/docker-mailserver, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
> docs(kubernetes): fix image name in example

- docs/content/config/security/ssl.md
Update of example to be more consistent with the next one
Update of examples
Fixes https://github.com/docker-mailserver/docker-mailserver/issues/2381
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x ] If necessary I have added tests that prove my fix is effective or that my feature works
- [N/A no functional change ] New and existing unit tests pass locally with my changes
>  SSL documentation contains a small bug #2381

- target/scripts/check-for-changes.sh
- target/scripts/helper-functions.sh
- test/mail_changedetector.bats
The new way of executing `sha512sum` should work as well as the old way
but without the clutter and possible problems the usage of subshells +
exec incurs.
Moreover, there was a misconception about array expansion. Using `""`
around an expanding array (`${ARRAY[@]}`) is quite fine (and actually
the preffered way), not because it makes the expansion _one_ string
(this would be `${ARRAY[*]}`), but it makes sure when elements are
expanded, each element has `""` around them so to speak, i.e. there is
no re-splitting of these elements.
This PR is trying to a be step in uncluttering the changedetector process to find out what is causing the resource leak described in #2348.
> improvement: get rid of subshell + `exec` in `helper-functions.sh`

- README.md
- docs/content/config/advanced/podman.md
- mailserver.env
- target/scripts/startup/setup-stack.sh
- test/permit_docker.bats
This PR includes security related documentation to run docker-mailserver with podman in rootless mode. See the linked issue for more details on the security concerns.
Personally I would like to set `PERMIT_DOCKER=none` to the new default in `mailserver.env` because it enforces authentication even from localhost and therefore is more secure, but this would result in a breaking change for users that have authentication-less setups for their localhost. The decision is up to you :)
Fixes #2377
> Rootless Podman security update

- target/scripts/helpers/aliases.sh
- target/scripts/startup/setup-stack.sh
`/etc/postfix/regexp` appeared ~~twice~~ in Postfix's `virtual_alias_maps`. This should be corrected now.
PS: It turns out, without this PR, every time a change is detected, `/etc/postfix/regexp` will be added again. So this PR is indeed somewhat important :D
Fixes #2394
> fix: double occurence of `/etc/postfix/regexp`

- .github/workflows/scripts/docs/build-docs.sh
- docs/content/config/security/understanding-the-ports.md
- docs/mkdocs.yml
This will upgrade mkdocs-material to v8.2.1 which just hit a [new milestone](https://squidfunk.github.io/mkdocs-material/insiders/#5000-aji-panca)
We now can:
- Added native support for Mermaid.js diagrams
- Added native support for tags (with search integration)
- Added support for staying on page when switching versions
> docs(deps): bump mkdocs-material to v8.2.1

- docs/content/config/advanced/podman.md
This is a follow up of #2393, where I accidentally added broken links to the podman documentation.
In addition to this fix, I've added some version hints to the changes introduced in the aforementioned PR to circumvent issues like [this](https://github.com/docker-mailserver/docker-mailserver/issues/2411#issuecomment-1043542552)
> docs(podman): Fix broken links and add version hints

- docs/content/examples/tutorials/docker-build.md
'setup.sh' expects an image named 'mailserver/docker-mailserver:latest' or else it will pull a remote image.
(To some degree whether this change makes sense depends on whether the audience for this page is intended to go on to use the image themselves. If it's for somebody who will use some downstream publishing process perhaps it's not correct.)
> Update 'build' doc

- docs/content/config/setup.sh.md
- target/bin/setup
> setup.sh: Remove obsolete 'debug inspect' command from usage text

- target/scripts/start-mailserver.sh
- test/mail_with_ldap.bats
With the merge of #2428, the default sender address was changed.
Let's take our example config:
https://github.com/docker-mailserver/docker-mailserver/blob/b730942b96aec3ab52699b5d927577f42eef0a45/docker-compose.yml#L7-L8
Before: Reports sender address was mailserver-report@mail.example.com
After: Reports sender address is mailserver-report@example.com
This is wrong IMO.
The subject line of the reports are `Logwatch for mail.example.com (Linux)` and `Postfix summary for mail.example.com`. They correctly state the FQDN for which the reports are. The sender address should therefore also be `mail.example.com`.
`mail.example.com` is not necessary the same host as `example.com`, which is another reason for this change.
This PR uses the FQDN of the mailserver as default sender address.
Fixes #
> Use FQDN as REPORT_SENDER default value.

- test/mail_ssl_manual.bats
This PR speeds up the test, by getting rid of `sleep 15`.
Before: The test waits 15 seconds and then checks for the string `Manual certificates have changed` in the changedetector log file.
After: The changedetector log file is constantly monitored until the string is found. If the string is not found within 15 seconds, the test fails.
The test time is reduced to [~6 seconds](https://github.com/docker-mailserver/docker-mailserver/runs/5608390029?check_suite_focus=true#step:8:103).
> Improve test, get rid of sleep

- target/bin/addalias
- target/bin/addmailuser
- target/bin/addrelayhost
- target/bin/addsaslpassword
- target/bin/delalias
- target/bin/delmailuser
- target/bin/delquota
- target/bin/excluderelaydomain
- target/bin/fail2ban
- target/bin/listalias
- target/bin/listmailuser
- target/bin/postfix-summary
- target/bin/report-pflogsumm-yesterday
- target/bin/restrict-access
- target/bin/setquota
- target/bin/updatemailuser
- target/scripts/helpers/error.sh
- target/scripts/helpers/lock.sh
To maintainers, it is clear what `_errex` is, because we're working with
it frequently. The nameing choice, however, was (IMHO) no good. It is
needlessly short (why abbreviate error) and does not communicate its
functionality very well.
Now, it's very clear and yet not too long.## Type of change
> scripts: renamed function `_errex` -> `_exit_with_error`

- setup.sh
The command `shopt -s inherit_errexit` does not work in Bash < 4.4. This
commit fixes the error.
Fixes #2518
> add compatibility for Bash 4 to setup.sh

- test/tests.bats
The "quota exceeded" test is unreliable and failed too often lately for my taste. Therefore, I'd like to disable it because there is no use in having such a test.
> tests: disabled "quota exceeded" test

- README.md
- target/scripts/startup/setup-stack.sh
Previously, DMS would shut down immediately if no accounts were provided in an IMAP setup. This change drastically reduces the efforts for beginners, giving them two minutes of time before the container shuts down. This has the effect that setup is drastically simplified.
> setup: added grace period for account creation

- target/scripts/check-for-changes.sh
- target/scripts/helpers/ssl.sh
- test/mail_ssl_letsencrypt.bats
- test/test_helper/tls.bash
Small refactor to better support `check-for-changes.sh` functionality.
These changes should allow some additional test coverage to be enabled. This implements _Option B_ I described [in comment for a PR](https://github.com/docker-mailserver/docker-mailserver/pull/2524#issuecomment-1086750378) trying to enable that additional coverage.
- Changes to `ssl.sh` is minimal, effectively lifting the logic out of `_setup_ssl` to separate methods so that `check-for-changes.sh` can use one.
- `check-for-changes.sh` is primarily simplifying the logic by dropping the loop and inner conditional statement (_so some lines only have indentation changes_), calling `_setup_ssl` and `_find_letsencrypt_domain` instead. A separate commit improves relevant maintainer comments.
- Unnecessary to this PR is …
> refactor: letsencrypt implicit location discovery

- setup.sh
- target/bin/setup
- test/tests.bats
When running `setup.sh` without arguments, this is shown:
```
The command '' is invalid.
Use `./setup.sh help` to get an overview of all commands.
```
Then the user typically runs `./setup.sh help` to see the available commands. This PR saves a user this additional step, by assuming 'help', when no argument is given.
> setup.sh/setup: show usage when no argument is given

- Dockerfile
This PR removes not needed ENVs and adds a comment to clarify, why the other ENVs are needed.
These ENVs are not needed, they are handled by `start-mailserver.sh` like all other ENVs in DMS:
- `ONE_DIR=1` 
- `ENABLE_POSTGREY`
- `SASLAUTHD_MECHANISMS`
The remaining ENVs are referenced in `target/supervisor/conf.d/saslauth.conf` and must be present when supervisord starts (tested).
If necessary, their values are adjusted by `start-mailserver.sh` on startup.
> Dockerfile: Remove not needed ENVs and add comment

- config-examples/fail2ban-jail.cf
- docs/content/config/security/fail2ban.md
- docs/content/config/setup.sh.md
- docs/content/faq.md
- target/bin/fail2ban
- target/bin/setup
- target/fail2ban/jail.local
- target/scripts/startup/setup-stack.sh
- test/mail_fail2ban.bats
This PR adds a new "ban" option to the [fail2ban](https://github.com/docker-mailserver/docker-mailserver/blob/master/target/bin/fail2ban) script. This allows to easily block custom IPs with fail2ban:
`./setup.sh failban ban <IP>`
The default bantime is 180 days, but can be adjusted easily like other fail2ban settings.
`setup.sh`: fail2ban was moved from the "debug" section to it's own fail2ban section:
`setup.sh debug fail2ban` --> `setup.sh fail2ban`
While adding the necessary changes to `config-examples/fail2ban-jail.cf`, I've also synced all values there, with our default settings.
A new fail2ban test was added and the existing ones were improved.
> Add ban feature to fail2ban script

- target/scripts/check-for-changes.sh
- target/scripts/helpers/error.sh
- target/supervisor/conf.d/supervisor-app.conf
The supervisord [configuration](http://supervisord.org/configuration.html) for changedetector always restarts the service once it exits:
https://github.com/docker-mailserver/docker-mailserver/blob/3cb5668b6f62258d8c21629c0f5e649085e4f0b6/target/supervisor/conf.d/supervisor-app.conf#L76
In case the changedetector service exits with an [error](https://github.com/docker-mailserver/docker-mailserver/blob/3cb5668b6f62258d8c21629c0f5e649085e4f0b6/target/scripts/check-for-changes.sh#L25), it's restarted. This leads to an endless exit and restart loop.
To prevent this, `autorestart=true` has been removed from the configuration. This lets supervisord only restart the service, when it exits with error code >0.
The function `_exit_with_error` now allows to pass a second argument: the exit code.
In …
> Fix changedetector restart loop

- target/bin/addalias
- target/bin/addmailuser
- target/bin/addrelayhost
- target/bin/addsaslpassword
- target/bin/delalias
- target/bin/delmailuser
- target/bin/delquota
- target/bin/excluderelaydomain
- target/bin/listalias
- target/bin/setquota
- target/bin/updatemailuser
The `DATABASE` ENV fallback was added in [this Dec 2016 PR](https://github.com/docker-mailserver/docker-mailserver/pull/441), no justification was provided.
Likewise for [`USER_DATABASE` in `delquota` and `addquota` files in Apr 2020](https://github.com/docker-mailserver/docker-mailserver/pull/1469) which was probably based on the earlier existing convention used for `DATABASE`.
---
Neither are in usage by our tests or detailed in documentation.
These are being dropped as a [recent PR](https://github.com/docker-mailserver/docker-mailserver/pull/2535) adapted existing scripts where `DATABASE` with an ENV fallback would be conflicting with usage elsewhere unless providing a temporary ENV when calling the command.
Until an actual use-case requires this, it's probably best to drop such …
> chore: Drop `setup.sh` DATABASE fallback ENV

- target/bin/sedfile
- test/sedfile.bats
This PR adjusts the `sedfile` tests to run inside a container. This allows the removal of the workaround inside `sedfile`.
Fixes: https://github.com/docker-mailserver/docker-mailserver/pull/2507#discussion_r835865532
> Run sedfile tests in container

- target/bin/addalias
- target/bin/addmailuser
- target/bin/addrelayhost
- target/bin/delmailuser
- target/bin/open-dkim
- target/bin/setup
- target/scripts/helpers/log.sh
This PR streamlines the color usage of the scripts. Color variables are now globally defined in `log.sh`. I did not use a separate file like `colors.sh`, because some scripts only source `log.sh`
> Use color variables instead of escape codes

- docs/content/config/advanced/podman.md
DOCKER_HOST="unix:///var/run/.."" missing "unix:///"
Improving the documentation
> documentation: `DOCKER_HOST` missing `unix://`

- target/scripts/startup/check-stack.sh
If the loglevel is invalid (for example `DEBUG`) it will print
> [ WARNING ]  Log level 'info' is invalid (falling back to default 'info')
But the correct message would be
> [ WARNING ]  Log level 'DEBUG' is invalid (falling back to default 'info')
Fixes no open issue.
> scripts: loglevel warning message fix

- target/scripts/start-mailserver.sh
- target/scripts/startup/check-stack.sh
- target/scripts/startup/fixes-stack.sh
- target/scripts/startup/misc-stack.sh
- target/scripts/startup/setup-stack.sh
This PR makes `start-mailserver.sh` consistent with the function naming scheme and cleans up the comments that describe each section of the script (with the last PRs touching the script, the comments got a bit messed up).
No functionality change, just script consistency.
> scripts: more consistency in `start-mailserver.sh`

- docs/content/config/advanced/podman.md
documentation: DOCKER_HOST missing unix://
Fixes #
> documentation: DOCKER_HOST missing unix://

- target/scripts/startup/setup-stack.sh
On first start, the check for accounts would emit a warning, but also an
error:
`grep: /tmp/docker-mailserver/postfix-accounts.cf: No such file or directory`
since the `postfix-accounts.cf` file is not yet there. This commit fixes
the issue, so only the warning is logged correctly.
> scripts: fix error message caused by `grep` on first starts

- target/bin/listalias
- target/bin/listdovecotmasteruser
- target/bin/listmailuser
- target/bin/open-dkim
- target/scripts/helpers/accounts.sh
- target/scripts/helpers/aliases.sh
- target/scripts/helpers/relay.sh
- target/scripts/helpers/utils.sh
- target/scripts/startup/setup-stack.sh
We have used various ways to filter out unwanted lines (empty, white-space only, comments) from configs when reading them to iterate through. In some cases, we had not filtered for all kinds of unwanted lines, or did not filter at all (even though we probably should have). 
This PR has normalized that approach to call a helper method instead (added in  https://github.com/docker-mailserver/docker-mailserver/pull/2617), with a common approach to call the filter method applied:
- The changes are mostly converting config file paths into local vars to reference instead. These are staged out into commits for easy review if needed (no commit messages).
- Then normalizes the config file pre-processing step to use the recently added method `_get_valid_lines_from_file()` (renamed in this PR from …
> chore(housekeeping): Normalize how config files filter out unwanted lines

- docker-compose.yml
- test/tests.bats
This PR adds a basic healthcheck for DMS. The container is considered healthy, when postfix is running and listening on port tcp/25.
> Add basic container healthcheck

- target/bin/fail2ban
In case fail2ban is not enabled, running `./setup.sh fail2ban` shows this error:
```bash
./setup.sh fail2ban
2022-06-06 19:45:53,685 fail2ban                [12]: ERROR   Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?
[   INF   ]  No IPs have been banned
```
This PR adds a check and change the output to:
```bash
./setup.sh fail2ban
[  ERROR  ]  Fail2ban not running
[  ERROR  ]  Aborting
```
> Check if fail2ban is running

- target/scripts/check-for-changes.sh
- target/scripts/helpers/utils.sh
- target/scripts/startup/fixes-stack.sh
Container startup and the Change Detector have their own copy of the `chown -R 5000:5000 /var/mail` logic. I replaced the duplicate code with a call to a shared method in `helpers/utils.sh`.
I've added a `TODO` maintenance comment for the method. I've already looked into that concern and will detail it with a follow-up PR (for a breaking change) where we can discuss if removal is appropriate. For now, at least lets keep the shared logic in sync :+1: 
This PR is part of investigating https://github.com/docker-mailserver/docker-mailserver/pull/2256 so that it can be resolved.
> chore: Extract out `/var/mail` ownership workaround

- target/scripts/check-for-changes.sh
- target/scripts/helpers/aliases.sh
- target/scripts/helpers/change-detection.sh
Housekeeping PR mostly, added a few extra configs that should be monitored for changes.
I looked into some conditional guards and why they were needed. Turns out they're not, most of it was introduced from early support of Change Detection service and no longer relevant.
Origin of conditional guards:
- `check-for-changes.sh` originally used relative paths to supported config files to monitor. This and checksum file creation relied on changing the working directory to `/tmp/docker-mailserver`. No longer necessary as we use absolute paths.
- This carried over to associated scripts to only run logic if the directory existed (_such as [here in a Aug 2019 commit](https://github.com/docker-mailserver/docker-mailserver/commit/7f3e5a22e18e091e2eeabaa47a18a854788e7db8)_). We support monitoring …
> chore(`check-for-changes.sh`): Drop redundant guards

- target/bin/open-dkim
- target/scripts/helpers/accounts.sh
- target/scripts/helpers/aliases.sh
- target/scripts/helpers/postfix.sh
- target/scripts/startup/setup-stack.sh
`bin/open-dkim` and `helpers/accounts.sh` + `helpers/aliases.sh` have roughly duplicate code for collecting domains to process. This code is now in sync by updating methods in `helpers/postfix.sh`.
<details>
<summary>Commit messages (first to last) for quick reference</summary>
**chore: Split vhost helper method and use filepath vars**
- Helpers `accounts.sh` and `aliases.sh` can move their vhost code into this helper.
- They share duplicate code with `bin/open-dkim` which will also leverage this vhost helper going forward.
**chore: Sync vhost generation logic into helper**
- Chunky commit, but mostly copy/paste of logic into a common method.
- `bin/open-dkim` additionally wrapped relevant logic in a function call and revised inline docs.
**chore: Include LDAP vhost support**
- Revises …
> refactor: Share a common helper (vhost builder) for sourcing domains

- target/scripts/check-for-changes.sh
- target/scripts/helpers/aliases.sh
This PR is mostly housekeeping for `check-for-changes.sh`, in preparation for further refactoring.
Changes have been staged via individual commits with messages for further context. It may be easier to follow the changes via commit diffs, than as a whole.
- Inline docs for `check-for-changes.sh` have been shuffled around and revised a bit.
- Change processing extracted from the main change detection loop method to their own methods:
- `_get_changed_files()` - I extracted the `grep`+`sed` line to it's own method.
- This was due to the verbosity of inline docs I added. I value being able to under to know quickly at a glance what I'm looking at without having to go refresh on the syntax :sweat_smile: - However if other maintainers feel this is a bad idea it can be reverted, no worries!
- …
> refactor: Revise `check-for-changes.sh`

- target/scripts/check-for-changes.sh
When `/etc/postfix/vhost` is updated from change detection, Amavis did not refresh that source, and thus would not be aware of any new domains, ignoring them for spam/virus checking.
A test could probably be added, my time is focused on prepping PRs with the time I have available right now.
> fix: Amavis should reload config for `/etc/postfix/vhost` updates

- target/scripts/helpers/accounts.sh
> fix: Dovecot Quota dummy accounts for aliases should check for existing users with an exact user key lookup

- CHANGELOG.md
Minor addition [that I missed to highlight](https://github.com/docker-mailserver/docker-mailserver/issues/2657) when putting release notes together.
> chore(CHANGELOG): Include a feature that belongs to an existing release

- .github/workflows/scripts/docs/build-docs.sh
Bug was [reported and fixed upstream roughly a month ago](https://github.com/squidfunk/mkdocs-material/issues/4028#issuecomment-1157448208). It had gone unnoticed with our `v11.1` docs release (_I'll need to rebuild that and update the `gh-pages` branch_).
Fixes #2680
> docs(fix): Update to fix regression causing broken links

- target/scripts/startup/setup-stack.sh
This PR hides the configomat output, for `LOGLEVEL` != `debug/trace`.
This prevents issues like [this](https://github.com/docker-mailserver/docker-mailserver/issues/2692) in the default configuration.
Fixes #2692
> Set configomat output to loglevel debug

- target/bin/fail2ban
This PR simplifies the `fail2ban` script output when it's called without arguments.
There is no need to verify/validate IPv4 addresses with a regex.
This way, it's also compatible with IPv6 addresses, which were previously not caught with the IPv4 regex.
Fixes #2687
> Simplify fail2ban output

- docs/content/config/advanced/full-text-search.md
- docs/content/config/environment.md
- docs/content/faq.md
Everything that was mentioned in the issue and fixing the link to the actual
Fixes #2702
> docs: Improve cron tasks and fix link in documentation

- .gitmodules
- test/setup-cli.bats
- test/tests.bats
This PR updates `bats` submodules. Notably the `bats-assert` and `bats-support` submodules have since been migrated to the `bats-core` organization, while our current remote has been unmaintained since 2016.
- [`bats-core`](https://github.com/bats-core/bats-core) our last release of `1.4.1` (July 2021) updated to [`1.7.0` (May 2022)](https://github.com/bats-core/bats-core/releases/tag/v1.7.0). Some fixes and new `setup_suite()` + `teardown_suite()` options to run once before and after all individual test files (`setup_file()` / `teardown_file()`) are handled.
- [`bats-assert`](https://github.com/bats-core/bats-assert) has had a fair amount of updates. I've opted to update to the current master commit as no official release has been tagged since Nov 2018. There is a [request for a new …
> tests: Update submodules for bats

- docs/content/config/best-practices/dmarc.md
There was a typo in the reference preventing the link from being properly detected.
> docs: Fix DMARC link

- target/bin/addmailuser
- test/setup-cli.bats
- test/test_helper/common.bash
- test/tests.bats
Resolves a `TODO` task with `addmailuser`.
The main change is adding three new methods in `common.bash`, which replace the completion delay in `addmailuser` / `setup email add` command.
Other than that:
- I swapped `sh -c 'addmailuser ...'` to `setup email add ...`.
- Improved three tests in `setup-cli.bats` for `setup email add|update|del` (_logic remains effectively the same still_).
- Rewrote the `TODO` comment for `setup-cli.bats` test on `setup email del` to better clarify the concern, but the test itself was no longer affected due to changes prior to this PR, so I enabled the commented out assertion.
- Removed unnecessary waits. The two `skip` tests in `test/tests.bats` could be enabled again after this PR.
Commit messages provide additional details if helpful.
Presently when adding …
> chore: `addmailuser` - Remove delaying completion until `/var/mail` is ready

- test/mail_fail2ban.bats
- test/mail_hostname.bats
- test/mail_undef_spam_subject.bats
- test/no_container.bats
- test/tests.bats
Local tests can fail depending on environment if Docker is configured with an excessive FD limit.
This was affecting tests using `ENABLE_SRS=1` and `ENABLE_FAIL2BAN=1` due to a common step for daemonization taking considerably longer to complete (8 minutes on Fedora 36), causing the tests to fail due to timeout or unreachable service.
I have chosen kernel defaults (1024 soft, 4096 hard), as opposed to systemd (1024, 512K) which should be fine for tests. The limit is for how many files/streams a process can have open at one time. A process can request to raise the soft limit so long as it's below the hard limit.
I avoided documentation as I don't expect this to be a common issue users would face in real deployments. If an issue is raised about high CPU usage or similar odd activity to …
> tests: Ensure excessive FD limits are avoided

- .github/workflows/test_merge_requests.yml
- Dockerfile
Fixing flaws to make the tests workflow and Dockerfile more cache friendly.
In Sep 2019, a PR introduced the VCS `ARG` directives with [acknowledgement that it invalidates the build cache](https://github.com/docker-mailserver/docker-mailserver/pull/1256#issuecomment-529406724).
Every time the commit SHA changes, due to this placement all layers afterwards are invalidated and must be rebuilt, even though only `LABEL` directive values were being updated (_even without those, `RUN` will implicitly be invalidated due to `ARG` changing as it is cached as part of the build ENV_).
I've shifted all directives related to image config that aren't necessary until the end to a 2nd stage. The additional `FROM` introducing a 2nd stage is not necessary, but provides a basis for later refactoring the …
> ci: Better build caching for CI

- target/scripts/helpers/relay.sh
- target/scripts/startup/setup-stack.sh
- test/mail_smtponly.bats
- test/permit_docker.bats
This PR streamlines the `postconf` usage to not use the `-e` option, as it's the default since Postfix version >=2.8
From the man page: `The -e option is no longer needed with Postfix version 2.8 and later.`
> Remove unnecessary postconf switch '-e' and use single quotes where possible

- Dockerfile
Nothing big.. Just streamlining the `COPY` usage In `Dockerfile`. Some statements used `./`, while some did not.
> Streamline COPY statements in Dockerfile

- docs/content/examples/tutorials/blog-posts.md
Writeup on how to setup docker-mailserver on kubernetes. 
This is just a change to ./docs/content/examples/tutorials/blog-posts.md adding a link to my blog posts about docker mailserver. The link ends up on a page that groups links to several posts on docker mailserver. This allows me add more posts without having to do pull requests on the docker-mailserver project. 
- [X ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
> added link to brakkee.org for setup of docker-mailserver on kubernetes.

- .github/workflows/default_on_push.yml
- .github/workflows/generic_build.yml
- .github/workflows/generic_publish.yml
- .github/workflows/generic_test.yml
- .github/workflows/scheduled_builds.yml
- .github/workflows/test_merge_requests.yml
Mew re-usable workflows are introduced to handle building, testing and publishing the container
image in a uniform and easy way. Now, the `scheduled_builds`, `default_on_push`
and a part of the `test_merge_requests` workflow can use the same code
for building, testing and publishing the container images. This is DRY.
Follow-up for: #2742
> ci: improve GitHub Action CI with re-usable workflows

- target/scripts/helpers/change-detection.sh
- test/mail_smtponly.bats
This PR fixes a bug, where checksum calculation was done/tried, when there were no files to monitor.
Fixes #2775
> Only calculate checksums, when there are files to monitor.

- test/tests.bats
This PR fixes failed health-checks like [this](https://github.com/docker-mailserver/docker-mailserver/actions/runs/3076842772/jobs/4971288987#step:5:227), when the CI is faster than 30 seconds when running the health check (container isn't healthy yet at this point --> first health check is run after 30 seconds):
```
not ok 219 checking container healthcheck in 113ms
#
```
> tests: Wait at least 30 seconds before checking the health state of the container

- .github/workflows/generic_build.yml
- .github/workflows/generic_publish.yml
This is a critical fix for https://github.com/docker-mailserver/docker-mailserver/actions/runs/3095956307/jobs/5011369215 so we can properly publish images again.
Fixes <https://github.com/docker-mailserver/docker-mailserver/actions/runs/3095956307/jobs/5011369215>
> fix: adjusting semver tag of a step in publish workflow

- docs/content/examples/tutorials/docker-build.md
See #2791. Adds a note that we require a recent version of Docker when building.
> docs: add note about Docker version when building

- Dockerfile
- target/scripts/build/packages.sh
This PR adds the ability, to use the latest Dovecot packages from the community repository. For this, the build argument `DOVECOT_COMMUNITY_REPO=1` must be used.
The current version for Dovecot in the debian repository is `2.3.13`. In the community repository it is `2.3.19.1`.
There shouldn't be any problems for existing setups switching to the community repository, as the version gap is only minor. However to be safe, we can wait for the next DMS major release, to make the community repository the default.
> Add ability to build with Dovecot community repository

- Dockerfile
Since version `1.3-lab` of Dockerfile, heredoc syntax is available.
This PR converts the countless `&& \` lines into better readable heredocs.
> Dockerfile: use heredocs

- test/tests.bats
It seams, that Docker does not start a container immediately, after successfully running the `docker run..` command. Therefor the 30 seconds wait time for the health test can be to low. ~Hopefully, adding three more seconds solve that issue.~
Fixes: https://github.com/docker-mailserver/docker-mailserver/actions/runs/3162276455/jobs/5148743130#step:5:227
This fix now waits, until docker itself reports, that the container is not in the starting state anymore.
> tests: Wait until container is not in starting state anymore, before running health check

- test/tests.bats
`test/tests.bats` has been extremely unreliable during the setup stage. This should finally resolve that. Big thanks to @casperklein and @georglauterbach who have helped rule out other causes to narrow it down to this.
Recent changes I introduced to `tests.bats` better surfaced change detection problems more consistently, to the point failure frequency was extremely probable. I investigated and identified the cause :tada: 
Currently when a change detection would be triggered and during processing, a `CRLF` is found and converted to a `LF`, which modifies the `postfix-accounts.cf` file, triggering another change event :grimacing: 
Marked for `v11.2.0` as it's only a change to our tests and should make existing PRs much happier :)
---
There is no need for the first approach used in …
> tests(fix): Avoid introducing CRLF into `postfix-accounts.cf` during setup

- CHANGELOG.md
- target/supervisor/conf.d/supervisor-app.conf
Fetchmail is heavily verbose in `mail.log`. This leads to a lot of log entries on each poll:
<details>
<summary>Details</summary>
```
fetchmail: 6.4.16 querying pop.gmx.net (protocol POP3) at Sun Oct 23 12:31:02 2022: poll started
Trying to connect to 212.227.17.185/995...connected.
fetchmail: Loaded OpenSSL library 0x101010ef newer than headers 0x101010bf, trying to continue.
fetchmail: Server certificate:
fetchmail: Issuer Organization: T-Systems International GmbH
fetchmail: Issuer CommonName: TeleSec ServerPass Extended Validation Class 3 CA
fetchmail: Subject CommonName: mail.gmx.net
fetchmail: Subject Alternative Name: mail.gmx.net
fetchmail: Subject Alternative Name: mail.gmx.de
fetchmail: Subject Alternative Name: smtp.gmx.net
fetchmail: Subject Alternative Name: smtp.gmx.de …
```
> Run fetchmail not in verbose mode

- setup.sh
This bugs me already for a while. "Unchecked error" is triggered on all errors, also on those that are expected. I think it's fine to remove this completely. `setup.sh` is not that large, that we need such a kind of debug function IMO.
```bash
[  ERROR  ]  '/tmp/docker-mailserver/postfix-virtual.cf' does not exist
[  ERROR  ]  Aborting
--- UNCHECKED ERROR
- script    = ./setup.sh
- function  = _run_in_new_container
- command   = ${CRI} run --rm "${USE_TTY}" -v "${CONFIG_PATH}:${DMS_CONFIG}${USE_SELINUX}" "${IMAGE_NAME}" "${@}"
- line      = 147
- exit code = 1
This should not have happened. Please file a bug report.
```
> setup.sh: Remove __err function

- target/bin/listmailuser
Details see [here](https://github.com/docker-mailserver/docker-mailserver/issues/2877).
Before:
```bash
./setup.sh email list
* media@example.com
[ aliases -> facebook@example.com ]
* socialmedia@example.com
[ aliases -> facebook@example.com ]
```
After:
```bash
./setup.sh email list
* media@example.com
* socialmedia@example.com
[ aliases -> facebook@example.com ]
```
Fixes #2877
> Bugfix: './setup.sh email list' does not display aliases correctly

- target/postfix/main.cf
- target/scripts/startup/setup-stack.sh
- test/mail_dnsbl.bats
- test/mail_with_postgrey.bats
Adjusts the DNSBL return codes interpretation. Now, only "valid" return codes, i.e. the ones that indicate spam, are taken into account.
Fixes #2889
> fix: adjust DNSBL return code interpretation

- .github/workflows/contributors.yml
- .github/workflows/generic_build.yml
- .github/workflows/generic_publish.yml
See <https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/>
> ci: update to new output format on GH actions

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/generic_build.yml
- .github/workflows/generic_publish.yml
- .github/workflows/scheduled_builds.yml
- .github/workflows/test_merge_requests.yml
This platform has had a deprecation notice for 6 months. It is not worth continuing to maintain support for.
See https://github.com/docker-mailserver/docker-mailserver/issues/2642 (_deprecation notice tracking issue_) for more details.
Closes #2642
> ci: Drop support for ARM v7 platform

- docs/content/config/environment.md
- mailserver.env
- target/scripts/helpers/relay.sh
- test/tests/serial/mail_special_use_folders.bats
- test/tests/serial/mail_undef_spam_subject.bats
- test/tests/serial/mail_with_mdbox.bats
- test/tests/serial/mail_with_sdbox.bats
As per [deprecation notice from v11.3 release notes](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v11.3.0), and a [related prior PR](https://github.com/docker-mailserver/docker-mailserver/pull/2605); this ENV is to be removed.
It's no longer considered useful, and none of the tests that configured it were actually using it for relaying anything.
> chore: Remove legacy ENV `SASL_PASSWD`

- target/scripts/check-for-changes.sh
- test/helper/common.bash
- test/test_helper/common.bash
- test/tests/serial/mail_changedetector.bats
- test/tests/serial/mail_ssl_letsencrypt.bats
- test/tests/serial/setup-cli.bats
With `reload` a change detection event during local testing can be processed in less than a second according to logs. Previously this was 5+ seconds (_plus additional downtime for Postfix/Dovecot to become available again_).
In the past it was apparently an issue to use `<service> reload` due to a concern with the PID for wrapper scripts that `supervisorctl` managed, thus `supervisorctl <service> restart` had been used. Past discussions with maintainers suggest this is not likely an issue anymore, and `reload` should be fine to switch to now :+1: 
---
**NOTE:** It may not be an issue in the CI, but on _**local systems running tests may risk failure in `setup-cli.bats` from a false positive**_ due to 1 second polling window of the test helper method, and a change event being possible to …
> fix(changedetector): Use service `reload` commands instead of `supervisorctl restart <service>`

- test/helper/common.bash
- test/test_helper/common.bash
Follow-up to a recent PR for improving processing time of a change event: https://github.com/docker-mailserver/docker-mailserver/pull/2947#issuecomment-1363541724
The CI was not as slow as expected, so here is the proper fix (_at least I believe this should be reliable?_):
> Counting and comparing this observation instead is simpler, and more reliable at detecting change events that start and complete very quickly (_within the same second_).
Fixes #2966
Closes #2971
> tests(fix): `wait_until_change_detection_event_completes` to count

- test/helper/setup.bash
- test/tests/serial/test_helper.bats
- Minor change to the common container hostname (_presently only affects parallel set tests, serial has been left alone_). This is preferred going forward as it's a private TLD that won't make external DNS lookups.
- Had an unrelated recurring test failure on a weak internet connection, bumped the sleep to match what is used in previous test cases.
> tests: Use `mail.example.test` as common container hostname

- Dockerfile
- target/fail2ban/fail2ban.d/fixes.local
- target/scripts/build/packages.sh
Bump F2B version to the next major version (v1.0.2). Same as #2903 which got reverted due to release of v11.3.1.
> update: bump Fail2Ban version to v1.0.2

- target/scripts/startup/setup-stack.sh
quota activation make dovecot crashes because of imap_quota**s** absence
regex correction (missing **s**)
> fix: regex in quota activation code

- test/tests/serial/mail_tls_dhparams.bats
- Refactored this test to the new test structure. Logic remains the same, just easier to grok.
- `ONE_DIR` handling was [removed for this feature in Sep 2021](https://github.com/docker-mailserver/docker-mailserver/pull/2192), dropping those redundant test cases.
> tests(refactor): Adjust `mail_tls_dhparams.bats`

- target/bin/restrict-access
- target/scripts/check-for-changes.sh
- target/scripts/helpers/aliases.sh
- target/scripts/helpers/utils.sh
- target/scripts/startup/daemons-stack.sh
- target/scripts/startup/setup-stack.sh
- test/helper/common.bash
- test/test_helper/common.bash
- test/tests/parallel/set1/spam_virus/postgrey_enabled.bats
- test/tests/serial/mail_smtponly.bats
- test/tests/serial/permit_docker.bats
After updating `main.cf`, to avoid an enforced delay from reading the config by postfix tools, we can ensure the modified time is at least 2 seconds in the past as a workaround. This should be ok with our usage AFAIK.
Shaves off 2+ seconds roughly off each container startup, reduces roughly 2+ minutes off tests.
Fixes #2985
> fix: Workaround `postconf` write settling logic

- .github/workflows/test_merge_requests.yml
- .gitignore
- Makefile
- test/tests/serial/no_container.bats
This is no longer serving any value to us. It was made redundant with changes added in Oct 2020.
- The `.gitignore` entries were [added in July 2019](https://github.com/docker-mailserver/docker-mailserver/pull/1196). They are no longer created by our tests.
- A new method to duplicate a base config folder for tests to use was [introduced in Oct 2020](https://github.com/docker-mailserver/docker-mailserver/commit/5fef8a5b780692f37cd5cee58cc948ca3d6f75f3#diff-c5122b538f758ede0753cfb05bc66d01eb445e4ffb97fff9b7140d55d0fa01c2). Part of the [early test extraction efforts](https://github.com/docker-mailserver/docker-mailserver/pull/1613).
- History of the Makefile `backup` target is detailed in a [comment from me in March 2022](https://github.com/docker-mailserver/docker-mailserver/issues/2465#iss …
> chore: Remove the Makefile `backup` target

- README.md
I fixed the link to the readme of the postsrsd repository. I have tried following the link, but it doesn't exist anymore.
> Fix SRS link in README.md

- docs/content/contributing/general.md
- docs/content/contributing/tests.md
- docs/content/index.md
- docs/mkdocs.yml
The title says it all. **If you want to adjust this PR, please just go ahead, you needn't provide a suggestion :)**
> docs: add a dedicated page for tests with more information

- Dockerfile
- target/scripts/start-mailserver.sh
- target/scripts/startup/fixes-stack.sh
- target/scripts/startup/misc-stack.sh
This PR covers changes mostly related to `misc-stack.sh`:
- Some minor refactoring of the conditional handling in the symlink loop (see commit for details).
- Ensures `chown -R` is more explicit about not only setting the user, but also the correct group. Postfix also needed a little adjustment there.
- Moves the related functionality for Amavis to be handled with the rest instead of a separate function call.
- Fixes `misc-stack.sh` rspamd ENV condition to add to `FILES` array when enabled, not disabled. This typo was missed [during initial review](https://github.com/docker-mailserver/docker-mailserver/pull/2902).
Likewise we've had a [similar issue with our `Dockerfile` copying over ClamAV database files](https://github.com/docker-mailserver/docker-mailserver/issues/2942#issuecomment-1383 …
> fix: Ensure state persisted to `/var/mail-state` retains correct group

- Makefile
- test/linting/lint.sh
This bugged me for a long time: we need `sudo` when running `make clean`, which is undesirable as you can image. I implemented a proper solution:
We run a small container (Alpine) and mount the files we need to remove into the container. This has the advantage that users that run Docker with an unprivilged user now don't have to type their sudo-password anymore and users that run Docker by default with password will need to type in the passward, but they need to do this anyways because of the command before.
---
To explain what I did: I introduced an array where I save files in. The `.gitignore` is still read, but the files read in the loop are now saved in the array. I adjust the path, prefixing `/mnt` and removing the `test` prefix from the file path before so the path is correct inside …
> quality-of-life: improve the `clean` recipe (don't require `sudo` anymore)

- target/postfix/sender_header_filter.pcre
This occured to me when looking at my Rspamd logs. Messages I sent were given a penalty (0.5) for not using the correct case (uppercase).
> postfix header filter: correct the casing for Mime vs. MIME

- test/tests/parallel/set2/tls_cipherlists.bats
This improvement is from [investigating the performance of `testssl.sh` containers](https://github.com/drwetter/testssl.sh/issues/2299#issuecomment-1409545691). The test goes from ~300 sec locally to ~200 sec.
Using `--openssl` uses the native `openssl` package within the image instead of the older `1.0.2` bundled from `testssl.sh`.
The test is only testing cipher suite compatibility is what we expect it to be, thus we do not need to run `testssl.sh` with a broader range of ciphers.
> tests: Reduce time taken by a third for testing cipher suites

- target/dovecot/90-quota.conf
Docker-Mailserver has dovecot listen on port 65265 for any address. When using host networking, that isn't necessarily desirable. Fix existing indentation.
Fairly confident.
And a test.
Not sure it's worth it.
The docs don't mention the port. All existing code already uses localhost.
Not sure it's worth it.
> fix: Only listen on `127.0.0.1` for the Dovecot `quota-status` service

- .github/workflows/generic_test.yml
1. BATS will actaully correctly determine that it is running in a CI environment, so we can omit the `CI` variable (not needed at all) (see a run in a fork if mine: <https://github.com/georglauterbach/docker-mailserver/actions/runs/4103019817/jobs/7076744395>)
2. When a current test is failing, all other parallel jobs are stopped by GH actions due to their fail-fast approach. While this is nice for many use cases, it's not in our case - so I disabled it. Now, all tests are running to completion.
> ci: remove CI ENV & disable fail-fast

- .github/workflows/generic_test.yml
As the test workflow does not use the `docker-container` buildx driver (_our build and publish workflows do_), it uses the Docker Engine bundled BuildKit version (_BuildKit release over 2 years old_) which until the recent v23 release (Feb 2023) does not support attestations. Github should have v23 available in runners sometime this month.
This driver difference is causing the current CI failures for test workflow runs:
- `docker/build-push-action` v4 will only [add the `--provenance` option to buildx command, if explicitly configured in the action](https://github.com/docker/build-push-action/pull/784/files). By not adding a value we can avoid causing this failure happening in buildx.
- The option is only valid in buildx `0.10.0` when there is a version of BuildKit that supports it. The …
> ci(fix): Temporarily avoid specifying `provenance`

- .github/ISSUE_TEMPLATE/bug_report.yml
Users (and I) are not sure how a field is formatted. The `render: Markdown` puts everything in a \`\`\`markdown block, which is not what I anticipated. So I removed that. Now , users can use Markdown formatting in almost all fields properly.
Fixes review feedback from #3078.
> improve bug report template

- target/scripts/startup/setup-stack.sh
This PR fixes a regression introduced with #3016, where the postfix setting `smtpd_milters ` changed the order of the values 
from `smtpd_milters = $dkim_milter $dmarc_milter`
to `smtpd_milters = $dmarc_milter $dkim_milter`.
The changed order led to this kind of DMARC failures:
<details>
<summary>Details</summary>
```
Jan 31 21:00:05 mail postfix/postscreen[22649]: CONNECT from [209.85.128.51]:53204 to [172.19.0.2]:25
Jan 31 21:00:11 mail postfix/postscreen[22649]: PASS NEW [209.85.128.51]:53204
Jan 31 21:00:11 mail postfix/smtpd[22650]: connect from mail-wm1-f51.google.com[209.85.128.51]
Jan 31 21:00:11 mail postfix/smtpd[22650]: Anonymous TLS connection established from mail-wm1-f51.google.com[209.85.128.51]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 …
```
> fix: order of DKIM/DMARC milters matters

- target/scripts/startup/setup-stack.sh
I came across this when looking at Rspamd logs. Logwatch does not set the "Envelope From" header properly and the return path is also wrong (it uses `root@mail.<DOMAINNAME>`).
With the new addition, the correct header is set as specified in `LOGWATCH_SENDER`.
> fix: add information to Logwatch's mailer so `Envelope From` is properly set

- README.md
- docs/content/config/advanced/optional-config.md
- docs/content/config/security/rspamd.md
- target/postfix/main.cf
- target/scripts/build/packages.sh
- target/scripts/helpers/setup-rspamd.sh
- target/scripts/startup/setup-stack.sh
- test/config/override-configs/rspamd-commands
- test/config/rspamd-modules.conf
- test/helper/sending.bash
- test/tests/parallel/set1/spam_virus/rspamd.bats
Users should be able to do some easy adjustments with our help. With this addition, they can mount a file `rspamd-modules.conf` and our setup will evaluate it. You can read the documentation for this when looking at the docs preview for this PR :)
> rspamd: add feature for adjusting options with a file parsed by DMS

- target/postfix/main.cf
- test/test-files/auth/ldap-smtp-auth-spoofed-sender-with-filter-exception.txt
- test/test-files/email-templates/postscreen.txt
- test/tests/parallel/set1/spam_virus/fail2ban.bats
- test/tests/parallel/set1/spam_virus/postscreen.bats
- test/tests/parallel/set3/mta/smtp_delivery.bats
- test/tests/serial/mail_with_imap.bats
- test/tests/serial/mail_with_ldap.bats
- test/tests/serial/tests.bats
Fixes #2895
1) Remove `smtpd_sasl_auth_enable` parameter from postfix configuration file. It disabled by default: [docs](http://www.postfix.org/postconf.5.html#smtpd_sasl_auth_enable)
2) Tests: use openssl for smtp-auth and make sure that auth on 25 port is disabled
Improvement (non-breaking change that does improve existing functionality)
> config: disable SMTP authentication on port 25

- target/supervisor/conf.d/supervisor-app.conf
`postfix start-fg` was not properly responding to signals received to stop. This caused `supervisorctl restart postfix` and `supervisor stop postfix` to not work as expected (_stopping the Postfix master process, before attempting to start the service again_).
Supervisor does not support custom commands for restarting or stopping a service, relying only on managing the process via  a signal. In the past we used a wrapper script to TRAP the signals and trigger commands that way.
However there is a feature which allows us to proxy signals to a different process by referencing a PID file. As Postfix master process creates a pid file when started, we can avoid a wrapper script and the `supervisorctl` functionality works as intended :+1:
---
Fixes #3116 
This is a fix to a change scheduled for …
> fix: Postfix service should proxy signals received

- .github/workflows/generic_vulnerability-scan.yml
Fix for https://github.com/docker-mailserver/docker-mailserver/pull/3106 as a recent run of the Action failed.
If permissions are specified at the workflow level, any that are not explicitly set [become `none` and jobs cannot request that to change](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs).
Permissions are therefore scoped to the job itself (_[Github Actions docs for the step requiring the permission](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository)_).
> ci(fix): Only apply permissions at the job level

- docs/content/config/advanced/kubernetes.md
- docs/content/config/environment.md
- mailserver.env
- target/postfix/main.cf
- target/postfix/master.cf
- target/scripts/startup/setup.d/security/spoofing.sh
Make `SPOOF_PROTECTION=1` the default and improve Postfix configuration to eliminate the currently shown warning.
Reviewing commit-by-commit advised.
Fixes #3117
> config/ENV: improve Postfix config for spoof protection

- target/scripts/startup/setup.d/mail_state.sh
After changing the group, special bits are lost, but they should be set for the directories `/var/spool/postfix/{maildrop,public}`, otherwise you see the following error:
```txt
postfix/postdrop[17400]: warning: mail_queue_enter: create file maildrop/729504.17400: Permission denied
```
The web page <https://linux.m2osw.com/snapwebsites-postfixpostdrop18189-warning-mailqueueenter-create-file-maildrop25937318189-permission> provides the solution to restoring the correct permissions.
---
This is a blocker for v12.0.0.
> bugfix: special bits for maildrop and public directory

- Dockerfile
- docs/content/config/environment.md
- docs/content/config/security/rspamd.md
- target/dovecot/90-sieve.conf
- target/dovecot/sieve-global/after/spam_to_junk.sieve
- target/dovecot/sieve/before/60-spam.sieve
- target/scripts/start-mailserver.sh
- target/scripts/startup/setup.d/dovecot.sh
- target/scripts/startup/setup.d/security/misc.sh
- target/scripts/startup/setup.d/security/rspamd.sh
- target/scripts/startup/variables-stack.sh
- test/config/rspamd/postfix-accounts.cf
- test/config/rspamd/user-patches.sh
- test/test-files/email-templates/rspamd-pass.txt
- test/test-files/email-templates/rspamd-spam-header.txt
- test/test-files/email-templates/rspamd-spam.txt
- test/test-files/email-templates/rspamd-virus.txt
- test/test-files/nc_templates/rspamd_imap_move_to_inbox.txt
- test/test-files/nc_templates/rspamd_imap_move_to_junk.txt
- test/tests/parallel/set1/dovecot/dovecot_sieve.bats
- test/tests/parallel/set1/spam_virus/rspamd.bats
Add new features to our Rspamd integration:
1. With `MOVE_SPAM_TO_JUNK=1`, we will now move messages marked with the `X-Spam: Yes` header to the "Junk" folder
2. With `RSPAMD_LEARN=1`, we enable
1. auto-learning for the Bayes filter
2. when a user moves messages from or to the "Junk" folder, Rspamd will learn them as ham or spam (for the Bayes filter as well)
I tried to separate commits as cleanly as possible to make reviews easier.
Closes #3145
Closes #3156
> Rspamd: more features

- .github/workflows/docs-production-deploy.yml
Add another step to the docs-production-deploy workflow to update a `latest` symlink on `gh-pages` that points to the latest documentation version. 
Begins to fix #3173
Ancillary PR that updates `versions.json` on `gh-pages` branch: #3182
If this looks like a good way of maintaining a `latest` version, I can open a PR with link changes from edge to latest where I think they are warranted.
I've made sure it works on my fork.
> Add update to `latest` symlink on `gh-pages` to docs-production-deploy workflow

- docs/content/faq.md
Add a new FAQ about email deliverability. There have been two issues filed about this in the last 2 days (#3180 and #3189). I suspect there have been many more. It might be helpful to have an FAQ to link to?
> docs: Add FAQ entry for troubleshooting delivery

- docs/content/contributing/tests.md
Move `make build` instruction from paragraph into list 
Clarifies confusion in #3191
> docs: move `make build` instruction from paragraph into list

- target/scripts/startup/setup.d/dovecot.sh
Fix for:
```
[   INF   ]  Welcome to docker-mailserver 11.3.1
[   INF   ]  Checking configuration
[   INF   ]  Configuring mail server
chmod: cannot access '/usr/lib/dovecot/sieve-filter/*': No such file or directory
chmod: cannot access '/usr/lib/dovecot/sieve-pipe/*': No such file or directory  
```
> Fix: only chmod when there are files

- target/dovecot/10-master.conf
- target/dovecot/chroot.inc
- target/postsrsd/postsrsd
Removed `chroot` jail for Dovecot & PostSRSd.
Related: #3160 (see <https://github.com/docker-mailserver/docker-mailserver/pull/3160#issuecomment-1465326589>)
See also: <https://github.com/orgs/docker-mailserver/discussions/3172#discussioncomment-5276395>
See also: <https://github.com/docker-mailserver/docker-mailserver/pull/3146#issuecomment-1490189454>
Fixes #3174
> config: remove `chroot` for Dovecot & PostSRSd

- target/postfix/main.cf
- target/scripts/startup/setup.d/dmarc_dkim_spf.sh
Basically <https://github.com/docker-mailserver/docker-mailserver/pull/3246#discussion_r1162156066>.
Looking at <https://github.com/docker-mailserver/docker-mailserver/actions/runs/4699505235/jobs/8333061595?pr=3261>, we can see that `postconf` is complaining:
```txt
postconf: warning: /etc/postfix/main.cf: unused parameter: policyd-spf_time_limit=3600
```
This PR resolves the matter and puts all the code that integrates policyd-spf in one place.
---
The log says `'Disabling policyd-spf'`, when actually doing nothing, but this is okay, since
1. the default value is `1`
2. we will change the default after v12.1.0 to 0 anyway and therefore, the log messages
> scripts: get all `policyd-spf` setup in one place

- target/scripts/helpers/database/manage/postfix-accounts.sh
- target/scripts/helpers/database/manage/postfix-virtual.sh
We do not support aliases that are accounts at the same time. This commit provides a guard that checks the condition.
@bibiak1 made us aware of the fact that we allow creating aliases as users (and vice versa). I think we do not support this, and at least to me, it does not make a lot of sense.
Fixes #3262
Closes #3259
> scripts: disallow alias = account

- target/scripts/startup/setup.d/postfix.sh
Noticed that something was wrong when in our tests i got the following additional output:
```
sed: -e expression #1, char 111: invalid reference \1 on `s' command's RHS
```
Info @wt-io-it
> postfix.sh: add missing -E for extended regexes in smtpd_sender_restrictions

- target/scripts/startup/setup.d/postfix.sh
``mailserver  | sed: -e expression #1, char 302: invalid reference \1 on `s' command's RHS``
The sed command has a syntax error preventing a reference from being created. There's also an errant "=" that would output.
This fixes the issue and allows SRS_EXCLUDE_DOMAINS to be set in the postsrsd configuration.
> scripts: fix setting `SRS_EXCLUDE_DOMAINS` during startup

- target/scripts/helpers/accounts.sh
- target/scripts/helpers/error.sh
- target/scripts/helpers/utils.sh
- target/scripts/start-mailserver.sh
- target/scripts/startup/check-stack.sh
- target/scripts/startup/daemons-stack.sh
- target/scripts/startup/setup-stack.sh
- target/scripts/startup/setup.d/dovecot.sh
- target/scripts/startup/setup.d/networking.sh
> In case the user requested an immediate exit, he ensure he is not in a subshell
This PR makes the decision obsolete, if the function is called from a subshell or not.
Inspired from: https://cravencode.com/post/essentials/exit-shell-script-from-subshell/
History:
- https://github.com/docker-mailserver/docker-mailserver/pull/3155
- https://github.com/docker-mailserver/docker-mailserver/issues/3140
- https://github.com/docker-mailserver/docker-mailserver/issues/3133
> scripts: improve shutdown function by making PANIC_STRATEGY obsolete

- .github/ISSUE_TEMPLATE/bug_report.yml
The extra checks for reading the code of conduct are now in one place; also removed a double-check on searching the docs and the issue tracker.
> ci: simplify `bug_report.yml`

- target/scripts/startup/setup.d/dmarc_dkim_spf.sh
Our CI test logs have lots of:
```
/usr/local/bin/setup.d/dmarc_dkim_spf.sh: line 106: EOF: command not found
```
Also discussed in https://github.com/docker-mailserver/docker-mailserver/pull/3263/files#r1167336949 and fixed in #3261
>Note checks only complete with #3267 in place
>Note checks only complete with #3267 in place
Info @wt-io-it
> scripts: remove superfluous `EOF` in `dmarc_dkim_spf.sh`

- docs/content/config/advanced/optional-config.md
- docs/content/config/security/rspamd.md
- target/scripts/helpers/utils.sh
- target/scripts/startup/setup.d/security/rspamd.sh
- test/tests/parallel/set1/spam_virus/rspamd.bats
- test/tests/parallel/set3/scripts/helper_functions.bats
1. added checks whether OpenDKIM/OpenDMARC/policyd-spf/Postgrey are enabled
2. added functions to check if VAR is 0/1 or an int
3. added more checks to Rspamd setup (mainly functions introduced in 2.)
4. added canonical directory for users to place files in
Related to #3249
Closes #3266
> Rspamd: script stabilization pt. 1

- target/scripts/helpers/dns.sh
- target/scripts/helpers/error.sh
- target/scripts/helpers/log.sh
- target/scripts/helpers/utils.sh
For an upcoming PR, these changes are required, because the script that is using the helpers uses `set -eE`. This leads to situations where errors are not properly handled in our helpers (yet; I plan on changing that in the future).
Fixes issues of an upcoming PR that I do not want to include in the upcoming PR because I am a nice maintainer and I try my best to separate concerns with PRs :D 😆
The `return 0` statements at the end of some functions seem superflous, but they are not, because the previos command (even when run inside an `if`-clause) set the return value to non-zero, which is not what we want.
> scripts: apply fixes to helpers when using `set -eE`

- docs/content/config/advanced/optional-config.md
- docs/content/faq.md
Removed entry about Rancher in the FAQ and added/improved docs/links for special (mount) directories.
> docs: update FAQ entries

- .github/workflows/contributors.yml
Related to earlier PR: https://github.com/docker-mailserver/docker-mailserver/pull/2224
- [`action-delete-branch`](https://github.com/dawidd6/action-delete-branch) is archived (unmaintained).
- [`action-create-branch`](https://github.com/peterjgrainger/action-create-branch) has poor documentation and looks unmaintained.
- [`add-contributors`](https://github.com/BobAnkh/add-contributors) doesn't seem to be related to the previous contributors project we were using, I'm not entirely fond of it's documentation but have not cared to seek out alternatives. The action forces updates to the remote, the local write option is for the CLI/dev mode only, unavailable to the action.
- Introduced [`create-pull-request`](https://github.com/peter-evans/create-pull-request) to replace the branch actions …
> ci: revised the contributor workflow

- docs/content/config/security/fail2ban.md
- target/bin/fail2ban
- target/bin/setup
Add 'log' command to show fail2ban's log file.
> fail2ban: add 'log' command

- docs/content/config/security/rspamd.md
See <https://github.com/docker-mailserver/docker-mailserver/issues/3323#issuecomment-1543636636>.
> docs: clear up confusion about Rspamd's `override.d` directory

- docs/content/config/best-practices/dkim_dmarc_spf.md
- target/scripts/startup/setup.d/security/rspamd.sh
See #3326 & #3328
Improves docs on Rspamd's DKIM script usage for multiple domains. Also mutes the output of `rmdir` and only shows the error afterwards (see #3328).
Fixes #3326
> docs: improve Rspamd docs about DKIM signing of multiple domains

- target/rspamd/local.d/antivirus.conf
- target/scripts/startup/setup.d/security/misc.sh
- target/scripts/startup/setup.d/security/rspamd.sh
- test/tests/parallel/set1/spam_virus/rspamd_full.bats
- test/tests/parallel/set1/spam_virus/rspamd_partly.bats
Addes sanity check for ClamAV size & adjusted MaxScanSize. The second part is of special importance! See <https://askubuntu.com/a/1448525>, which explains that the maximum scan size is important as well. We previously just set the maximum file size, which actually is pretty insecure as we silently not scan mile bigger than `MaxScanSize`. This is corrected now.
> scripts: improve `CLAMAV_MESSAGE_SIZE_LIMIT` usage

- docs/content/config/environment.md
- target/scripts/startup/setup.d/security/rspamd.sh
- test/test-files/nc_templates/rspamd_imap_move_to_inbox.txt
- test/test-files/nc_templates/rspamd_imap_move_to_junk.txt
- test/tests/parallel/set1/spam_virus/rspamd_full.bats
When moving a mail from the Junk folder to the Trash folder, the mail
previously classified as ham due to the wildcard match of `*`. Because
the syntax does not allow for negation, we can only change the behavior
in a way that mails are learned as ham when they are moved into `INBOX`
from `Junk`. This is reasonable though.
Fixes #3333
> Rspamd: adjust learning of ham

- docs/mkdocs.yml
>A "view source" button can be shown next to the "edit this page" button, both of which must now be explicitly enabled.
Source: https://squidfunk.github.io/mkdocs-material/upgrade/#contentaction
Fixes #
> docs: Restore missing edit button

- target/rspamd/local.d/actions.conf
- target/rspamd/local.d/antivirus.conf
See #3320. Adds (really not well documented) parameters to Rspamd configuration so ClamAV will not complain anymore because of short scan times.
Fixes #3320
> config: adjust `antivirus.conf` for Rspamd

- target/scripts/startup/setup.d/security/misc.sh
ClamAV stops scanning files larger than or equal to 2GiB add a warning for that.
When checking the 4000M limit for CLAMAV_MESSAGE_SIZE_LIMIT in https://github.com/docker-mailserver/docker-mailserver/pull/3332#discussion_r1193388669 i discovered that ClamAV stops scanning at a much lower limit.
Fixes #
Info @wt-io-it
> ClamAV: add a warning for the internal message size limit

- target/dovecot/10-mail.conf
- target/dovecot/auth-master.inc
- target/dovecot/auth-passwdfile.inc
- target/scripts/helpers/accounts.sh
- target/scripts/startup/setup.d/dovecot.sh
- test/tests/parallel/set1/dovecot/dovecot_sieve.bats
Funnily enough, strictly speaking this is not actually a breaking change. The Sieve scripts are already moved by us from `/tmp/docker-mailserver` to the correct location on startup, and the same goes for the Dovecot userdb file. But that is irrelevant, as the next version we are going to release is a major.. I woudl definitely mention it separately on the release page and in the changelog.
I consider this PR as high priority, as <<https://doc.dovecot.org/configuration_manual/home_directories_for_virtual_users/> points out: "Home directory shouldn’t be the same as mail directory with mbox or Maildir formats (but with dbox/obox it’s fine). It’s possible to do that, but you might run into trouble with it sooner or later."
I took care that mdbox/sdbox formats are untouched.
Fixes #3296
> Dovecot: make home dir distinct from mail dir

- target/scripts/helpers/database/db.sh
Previously it was assumed the sed operation was applying the sed expressions as a sequence, but it did not seem to filter entries being looked up correctly. Instead any line that matched either sed expression pattern was output (_value without matching key, values split by the delimiter_), then grep would match any of that causing false-positives.
Resolved by piping the first sed expression into the next.
Fixes: https://github.com/docker-mailserver/docker-mailserver/issues/3358
> fix: DB helper should properly filter entries

- docs/content/usage.md
Especially newcomers tend to confuse the DMS FQDN for something that is inherently linked to the mails that DMS serves. This PR sheds some light on the misbelief.
Mentioned in #3289
> docs: add note about DMS FQDN

- .github/ISSUE_TEMPLATE/bug_report.yml
Simplify the bug report form further by dropping / merging form sections. Partially inspired [`uptime-kuma`](https://github.com/louislam/uptime-kuma) report.
---
Presently the bug report form seems to have plenty of redundant content that maintainers don't leverage as context for responding or triaging any differently. They were originally intended to save us time but I don't recall that happening, sometimes information by the reporter was still communicated at a later stage.
In my experience, it's just additional noise for us and minor friction to the reporter. When the debug docs page is improved, we can probably simplify the "Preliminary Checks" section too (_or migrate common gotchas to still be visible on the bug report page as markdown comment placeholder in the "What Happened?" …
> ci: Simplify GH bug report template

- target/scripts/start-mailserver.sh
When running DMS with `SMTP_ONLY=1` and `MOVE_SPAM_TO_JUNK=1` (default), the following errors occur:
```
mailserver  | [   INF   ]  Welcome to docker-mailserver 12.1.0
mailserver  | [   INF   ]  Checking configuration
mailserver  | [   INF   ]  Configuring mail server
mailserver  | /usr/local/bin/setup.d/security/misc.sh: line 255: /usr/lib/dovecot/sieve-global/after/spam_to_junk.sieve: No such file or directory
mailserver  | error: script not found.
mailserver  | sievec: Fatal: failed to compile sieve script '/usr/lib/dovecot/sieve-global/after/spam_to_junk.sieve'
mailserver  | chown: cannot access '/usr/lib/dovecot/sieve-global/after/spam_to_junk.sieve': No such file or directory
mailserver  | chown: cannot access '/usr/lib/dovecot/sieve-global/after/spam_to_junk.svbin': No such file or …
```
> Don't register _setup_spam_to_junk() when SMTP_ONLY=1

- target/scripts/startup/setup.d/dmarc_dkim_spf.sh
Upon each start the  `smtpd_milters` and `non_smtpd_milters` would be extended with the following:
```
smtpd_milters =   $dmarc_milter $dkim_milter
non_smtpd_milters = $dkim_milter
```
In my case they became long enough that mail delivery stopped. I think this was because of the extra headers that are added by these steps. (which in turn would cause the mail to be dropped)
Fixes #
> Fix issue with concatenating $dmarc_milter and $dkim_milter in main.cf

- .github/ISSUE_TEMPLATE/bug_report.yml
Some users are reporting bugs with the `latest` tag instead of the actual DMS version, discourage this.
> chore: Discourage `latest` in bug report version field

- docs/content/config/advanced/ipv6.md
For added clarity, a user requested we document the example config snippets instead of only linking external references to them.
Some content has been shuffled around and revised, the [`nginx-proxy` comment link removed](https://github.com/nginx-proxy/nginx-proxy/issues/133#issuecomment-1368745843) (_replaced with simpler `networks` syntax, and same as typical user-defined network creation, reduced to a small tip on `default` overriding_), content tabs for presentation all within a single example admonition.
Resolves: #3422 
Direct preview link to updated section: https://pullrequest-3436--dms-doc-previews.netlify.app/config/advanced/ipv6/#enable-proper-ipv6-support
> docs: IPv6 config examples with content tabs

- target/bin/rspamd-dkim
- target/rspamd/local.d/options.inc
See <https://github.com/docker-mailserver/docker-mailserver/issues/3433#issuecomment-1646532264>.
Inbound emails should not be signed by Rspamd. Moreover, messages delivered from local addresses should not be signed either for the reasons mentioned in the comment above.
CC @Codelica
Fixes #3433
> rspamd: fix DKIM signing for inbound emails

- docs/content/config/security/fail2ban.md
- target/bin/fail2ban
- target/bin/setup
This PR adds a new option to the `setup.sh fail2ban` script to show a more detailed view on the status of all fail2ban jails using fail2ban's native `status <jail>` command. Effectively, the options just runs exactly that command for all jails already existing in the `JAILS` variable and outputs the result.
I wanted to have an option between just running the setup `fail2ban` sub-command without options that just returns the banned IPs and getting all details using `setup fail2ban log`. 
This might be a bit redundant to other options, but since it is a small change that breaks nothing, I figured I could move it back here, since its usage is probably very intuitive to any fail2ban user.
> feat(setup): Add `fail2ban` sub-command `status <JAIL>`

- target/bin/rspamd-dkim
- target/rspamd/local.d/options.inc
Follow up of #3439; includes changes of #3452. Added `192.168.0.0/16` to local networks and enabled `allow_username_mismatch` (see <https://github.com/docker-mailserver/docker-mailserver/issues/3433#issuecomment-1650613426>).
Fixes #3454 #3433 (again)
> Rspamd: local network addition and user name mismatch

- docs/content/config/security/understanding-the-ports.md
- docs/content/faq.md
In the same spirit as #3464, this PR fixes a documentation issue (in the FAQ page, and in "Understanding the Ports"), about using port 25 for mail clients, which is unsupported since #3006.
> Docs: Drop mention of port 25 support for authenticated submission

- .github/ISSUE_TEMPLATE/question.yml
Recently there has been low effort reports (_bypassing the dedicated form_) through this alternative free-form field, which is intended for addressing other concerns related to the project - **not troubleshooting user problems**.
When a user does not want to put the effort in of a full bug report (_and following our debug docs tips that it refers them to_), they should be using the Github Discussions page which provides the same free-form input, but should not require attention of project devs (contributors / maintainers).
---
The markdown rendered field above the "Description" input field didn't seem too relevant for this template. I've opted for a markdown comment (so it won't render if kept) into the input field with hopes that'll be more visible to the readers attention.
I'm usually …
> ci: `question.yml` - Clarify that the issue tracker is not for personal support

- .github/ISSUE_TEMPLATE/question.yml
The [recent change to this template](https://github.com/docker-mailserver/docker-mailserver/pull/3498) was invalid, as `value` should have been nested under the `attributes` object.
> ci: Fix `question.yml` template - `value` should be an attribute

- test/tests/parallel/set2/tls_cipherlists.bats
`3.1dev` branch has been [renamed to `3.2`](https://github.com/drwetter/testssl.sh/issues/2376). DockerHub has the [`3.2` tag published](https://hub.docker.com/r/drwetter/testssl.sh/tags).
> tests: TLS cipher suites - Update `testssl.sh` tag to `3.2`

- target/scripts/helpers/postfix.sh
- target/scripts/helpers/utils.sh
While working on improving the function `_add_to_or_update_postfix_main()`, I noticed a problem we had before in other occasions.
`SED_STRING="/${NEW_VALUE}/!`
This is not really fail safe, when `$NEW_VALUE` is a substring of an existing value.
Now I simplified the whole function, by replacing `sed` with `postconf`.
Fixes #3484
>  scripts: add wrapper to update Postfix configuration safely (follow up)

- docs/content/config/best-practices/dkim_dmarc_spf.md
- target/bin/open-dkim
- target/bin/rspamd-dkim
- test/tests/parallel/set1/spam_virus/rspamd_dkim.bats
- test/tests/parallel/set3/scripts/setup_cli.bats
- test/tests/serial/open_dkim.bats
I originally raised this change as desired back in a [March 2021 discussion](https://github.com/docker-mailserver/docker-mailserver/issues/1854#issuecomment-800679841) (_and again by me recently in [April 2023](https://github.com/docker-mailserver/docker-mailserver/pull/3231#pullrequestreview-1377342412) and [Aug 2023](https://github.com/docker-mailserver/docker-mailserver/issues/3491#issuecomment-1685412235)_), detailing why we should be set the default to 2048 (_revert rather, as the change from `2048` to `4096` wasn't justified well but got through review_).
Additional history for how the default became 4096 is detailed in:
- https://github.com/docker-mailserver/docker-mailserver/pull/2620 (June 2022)
- https://github.com/docker-mailserver/docker-mailserver/pull/3060 (Feb 2023)
I …
> chore: Change `setup config dkim` default key size to `2048` (`open-dkim`)

- CHANGELOG.md
- docs/content/config/advanced/auth-ldap.md
- docs/content/config/environment.md
- docs/content/examples/use-cases/forward-only-mailserver-with-ldap-authentication.md
- mailserver.env
- target/scripts/startup/variables-stack.sh
Before we forget and release v13 😅 
- Deprecation startup script check is kept for `ENABLE_LDAP=1` but adjusted to emit an error instead. It can be dropped in a future release. Just a precaution for those who mistakenly update (_possibly via automation_) without checking the release notes, an error log is somewhat helpful, although it could alternatively panic?
- Docs updated to remove the `ENABLE_LDAP=1` usage
- ENV docs updated to reference a maintained LDAP image.
- Changelog includes the breaking change, and slight revision to prior release mention of deprecation.
> chore: Adapt `ENABLE_LDAP=1` to `ACCOUNT_PROVISIONER=LDAP`

- .github/workflows/scripts/docs/build-docs.sh
- Bump to release `9.2.x`
- Image now has `MAJOR.MINOR` tag support to pull latest `PATCH` versions.
- [Changelog](https://squidfunk.github.io/mkdocs-material/changelog/)
> docs: Update docs builder image

- docs/content/config/advanced/ipv6.md
Fix the example for Docker Compose to configure an IPv6 network.
This was unfortunately slightly incorrect due to a mistake in the official Docker docs being propagated, which has been fixed upstream with docker/docs#18119.
The subnet must be specified as part of `ipam.config`.
Refer to the official Compose Spec for more details:
* https://docs.docker.com/compose/compose-file/06-networks/#ipam
> docs: fix ipv6 example for Compose

- target/bin/open-dkim
With `ENABLE_OPENDKIM=1` and `ENABLE_RSPAMD=1` it's currently not possible to create DKIM Keys
Fixes #
> fix: Open-DKIM key generation broken

- test/tests/parallel/set3/container_configuration/process_check_restart.bats
This was missed during the original review of https://github.com/docker-mailserver/docker-mailserver/pull/3010
On a linux host, processes running within a container have been visible via commands like `pgrep`. This is does not appear to be the case with WSL2 + Docker Desktop (Windows), resulting in test failure.
The command should have been run from within the container regardless.
> tests(fix): Run `pgrep` within the actual container

- test/tests/parallel/set3/mta/lmtp_ip.bats
Instead of exit status of `124` (_signifies timeout_), it should fail with `1` (failure) like the others. Handled via using `_run_in_container_bash()` (_`timeout` failure `124` does not propagate, and is treated as `1` instead_).
In this case we are waiting on the status of the mail being sent, the pattern provided to `grep` is too specific and results in a timeout. Instead since we only expect the one log entry, match any status and assert the expected pattern afterwards.
This provides a more helpful failure output that informs us that mail was at least processed by Postfix, but the sent status is not what we expected.
```
✗ [ENV] (POSTFIX_DAGENT) delivers mail to existing account [60327]
(from function `assert_success' in file test/test_helper/bats-assert/src/assert_success.bash, line …
```
> tests(fix): `lmtp_ip.bats` improve partial failure output

- docs/content/config/security/rspamd.md
- target/scripts/start-mailserver.sh
- target/scripts/startup/setup.d/log.sh
- target/scripts/startup/setup.d/security/rspamd.sh
- target/supervisor/conf.d/supervisor-app.conf
- test/helper/common.bash
~~In order to allow users to more easily go through log files, I added `most` to the set of packages we install. This adds +122kB in size, which I think is negligible.~~
~~Moreover, I added a section to the Rspamd documentation about where to find the corresponding log files.~~
I adjusted this PR to only include changes to logrotate and to the Rspamd log. In detail, I improved `_setup_logrotate` by simplifying it and making it more readable. Moreover, I adjusted the Rspamd log file location and added a logrotate config for the Rspamd log file.
I will provide a follow-up PR that includes changes about adding and removing packages, as discussed [here](https://github.com/docker-mailserver/docker-mailserver/pull/3576#discussion_r1353455195).
Associated: #3570
> refactor: `logrotate` setup + rspamd log path + tests log helper fallback path

- target/scripts/build/packages.sh
- target/scripts/helpers/utils.sh
- target/scripts/startup/setup.d/security/rspamd.sh
- test/tests/parallel/set3/scripts/helper_functions.bats
This PR does 2 things (and I was too lazy to provide two different PRs for these small changes):
1. Adjust `packages.sh` to install `most` and `nano` and remove `ed`, adding a dedicated set up packages for debugging (first commit)
2. Adjust the Rspamd setup script to make it even more robust (commit 2 and 4)
Follow up of #3576
> chore: Add debug group (`packages.sh`) + more resilient rspamd setup

- docs/content/config/advanced/maintenance/update-and-cleanup.md
Follow-up to earlier revision for v13 docs: https://github.com/docker-mailserver/docker-mailserver/pull/3539
I was concerned about the update functionality, `watchtower` docs are a tad vague on that (_[related upstream issue](https://github.com/containrrr/watchtower/issues/1802)_). We already use multi-tag semver approach, so it should work well with our image, but I've chosen to clarify this in our docs.
Watchtower notifications support thus wouldn't be useful for newer releases beyond the semver tag used. I was curious if it would substitute our own functionality for that. [`whats-up-docker`](https://github.com/fmartinou/whats-up-docker) is a similar project that could accomplish that generically for images. I've not adjusted docs here to reference release monitoring / notification only …
> docs: Revise `watchtower` page

- target/bin/rspamd-dkim
- target/scripts/startup/setup.d/security/rspamd.sh
- test/tests/parallel/set1/spam_virus/rspamd_dkim.bats
Instead of using `/etc/rspamd/override.d/dkim_signing.conf`, we will now be using `/tmp/docker-mailserver/rspamd/override.d/dkim_signing.conf`. The new location is persisted (and linked again during startup) and hence better suited.
Fixes #3593
> bugfix: change Rspamd DKIM default config location

- target/bin/addalias
Small documentation improvement as there are different common mechanisms for this kind of action.
> docs(bin/setup): Add an example for an alias with multiple recipients

- CHANGELOG.md
- docs/content/config/security/rspamd.md
- target/bin/rspamd-dkim
- target/scripts/check-for-changes.sh
- target/scripts/helpers/change-detection.sh
- target/scripts/helpers/index.sh
- target/scripts/helpers/rspamd.sh
- target/scripts/startup/setup.d/security/rspamd.sh
- test/tests/parallel/set1/spam_virus/rspamd_dkim.bats
- test/tests/parallel/set1/spam_virus/rspamd_full.bats
I was made aware of the fact that linking the Rspamd custom directory is not a good design choice. Hence, I revised this, and added improvements along the way. Reviewing commit-by-commit is strongly advised as I paid attention to making the commit history easy to review. It boils down to
1. remove the linking of the `override.d` directory and just use `cp`; this also simplifies other scripts (e.g. DKIM)
2. integration into the changedetector service
3. added a `--force` option for the Rspamd DKIM management
4. provided a dedicated helper script for common ENV variables (used in setup, DKIM & changedetection) and applying `custom-commands.conf` (used in setup & changedetection)
> misc: final Rspamd adjustments for v13

- v12.1/config/best-practices/dkim_dmarc_spf/index.html
There is invalid value "4" of adkim at line 1821 in GitHub docs.
https://github.com/docker-mailserver/docker-mailserver/blob/1d14c72445bf5643b16f6c620e3dbd44ede6562b/v12.1/config/best-practices/dkim_dmarc_spf/index.html#L1818-L1825
I have changed `adkim=4` to `adkim=r`
> docs: Fix typo "adkim=4" at DMARC section

- docs/content/config/advanced/optional-config.md
The directory on disk is written in all-lowercase, so documentation should match.
> Fix rspamd directory

- docs/content/config/advanced/auth-lua.md
- docs/content/examples/use-cases/auth-lua.md
- docs/mkdocs.yml
- target/scripts/build/packages.sh
This PR adds [Lua support for Dovecot](https://doc.dovecot.org/admin_manual/lua/) and documentation with an example usage for authentication. Lua authentication can be used to make Dovecot (and Postfix through Dovecot) authenticate against a web server or against anything else that can be used in Lua.
As discussed in #3575, a new `xapian` situation should be avoided. This PR relies on a standard Dovecot deb package that requires minimum change and maintenance as long as Dovecot deb packages are used. The documentation has a warning that there is minimal support for Lua, and that Lua support will be removed if it does not align with the development of DMS anymore for some reason.
Another warning in the documentation tells users that Lua authentication is an advanced topic, and that they …
> docs: Add Dovecot Lua auth guide + required package

- docs/content/config/environment.md
- mailserver.env
Make this easier to find when brosing the default environment. Adjust documentation to properly mark the actual default value.
> docs: Clarify default for ENV `FETCHMAIL_PARALLEL`

- docs/content/config/advanced/kubernetes.md
- target/scripts/startup/setup.d/mail_state.sh
1. Adjusts the K8s documentation, which requires `allowPrivilegeEscalation: true` as it turns out
2. Adjusts permsissions on `/var/spool/postfix/{maildrop,public}`. This is more tricky, but #3619 provides good insights. In short, we do not seem to require SUID/SGID/sticky bits on these directories as the binaries that place files in these directories already have the proper SGID bits set on them.
Fixes #3619
CC @innotecsol
> fix: Drop special bits from Postfix `maildrop/` and `public/` directory permissions

- target/bin/rspamd-dkim
- target/scripts/helpers/rspamd.sh
- target/scripts/startup/setup.d/security/rspamd.sh
The newly added function `__rspamd__check_dkim_permissions` performs a check on DKIM private key files. This is useful to prevent issues like #3621 in the future. The function is deliberately kept simple and may not catch every single misconfiguration in terms of permissions and ownership, but it should be quite accurate.
Please note that the Rspamd setup does NOT change at all, and the checks will not abort the setup in case they fail. A simple warning is emmited.
Reviewing commit-by-commit is advised.
Fixes #3621
> Rspamd: add check for DKIM private key files' permissions

- docs/content/examples/tutorials/crowdsec.md
- docs/mkdocs.yml
I added a page explaining how to use [crowdsec](https://www.crowdsec.net/) with docker-mailserver.
The page is not a complete tutorial on how to install and configure crowdsec but covers the docker-mailserver logs parsing by crowdsec.
I added the page under `examples/tutorials`
> docs: Example - Integrating Crowdsec

- test/linting/lint.sh
This internal container path of the image has been allowed as an exception for `git` to avoid a safety check, that would otherwise  cause [EC to fail detection for `git`](https://github.com/editorconfig-checker/editorconfig-checker/issues/268#issuecomment-1826200253), triggering fallback logic.
This shouldn't have any real impact on our CI, which [already has an explicit ignore for `.git/`](https://github.com/docker-mailserver/docker-mailserver/blob/2a716cf4a4e0eec9ec12d99fcc6e9c5e625a63f8/test/linting/.ecrc.json#L6). Just a change to better align with upstream documentation and include some context via comments for maintainers 👍
> ci: Linter EC should use `/check` as the mount path

- .github/workflows/default_on_push.yml
Previously, we did not run the workflow on push on `master` when a release happened because the push on master is guarded by a check on which files were changed.
With this change, I added `VERSION` to the list of files to consider when updating `:edge`.
Superseeds #3659
> bug fix: push `:edge` when `VERSION` is updated as well

- CHANGELOG.md
- docs/content/config/environment.md
- mailserver.env
- target/rspamd/local.d/settings.conf
- target/scripts/startup/setup.d/security/rspamd.sh
- test/tests/parallel/set1/spam_virus/rspamd_full.bats
This patch release fixes two bugs that Rspamd users encounter on `v13.0.0`:
1. The check for correct permission on the private key when signing e-mails with DKIM was flawed. The result was that a false warning was emitted.
2. When `RSPAMD_CHECK_AUTHENTICATED=0`, DKIM signing for outbound e-mail was disabled, which is undesirable.
Fixes #3665
> hotfix: solve #3665

- .github/workflows/default_on_push.yml
- .github/workflows/generic_publish.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- docs/content/examples/tutorials/docker-build.md
- target/scripts/build/packages.sh
- target/scripts/start-mailserver.sh
- target/scripts/update-check.sh
We have had 3 concerns encountered related to this feature in the past.
**Resolved by:**
- CI will now provide the `VERSION` as an image ENV (`DMS_RELEASE`) in the `Dockerfile` to build. No need to manually update `VERSION` (_well, until a future release warrants removing it_).
- Future releases will now check the GH Releases page instead of current `master` branch `VERSION` file.
**Past concerns addressed:**
1. `:edge` should not care about the update process, these concerns should not have been raised:
- https://github.com/docker-mailserver/docker-mailserver/pull/3659
- https://github.com/docker-mailserver/docker-mailserver/pull/3662#pullrequestreview-1749456998
2. A release was made [without bumping `VERSION` accordingly](https://github.com/docker-mailserver/docker-mailserver/issues/295 …
> fix: `update-check.sh` should query GH Releases

- CHANGELOG.md
- docs/content/config/debugging.md
While we do have a FAQ entry, adding a reference to the troubleshooting / debugging docs page might be helpful.
This isn't too uncommon to see issues raised for ([recent one](https://github.com/docker-mailserver/docker-mailserver/issues/3679)), and this issue compliments the existing entry above it (_opposite direction, sending mail outbound_).
> docs: Troubleshooting - Bare domain misconfiguration

- CHANGELOG.md
- target/scripts/start-mailserver.sh
This PR adds a warning, when update-check is enabled, but no stable release image is used.
Related: #3666
> Add warning, when update-check is enabled, but no stable release image is used

- CHANGELOG.md
- docs/content/config/security/rspamd.md
- target/scripts/build/packages.sh
scripts: Install rspamd from official repository  instead of debian backports on arm64 architecture
Since arm64 binary packages are available on the official respository, this may be used for arm64 architecture in favor of debian backports which contain considerably older version.
Fixes #3374
> scripts: Install arm64 rspamd from official repository 

- CHANGELOG.md
- target/scripts/update-check.sh
Currently, the `read` command fails with exit code 1. That is not an issue, the script continues running.
The problem is, that the delimiter (`-d ''`) is set to a null byte. However, the heredoc does not contain a null byte to terminate.
So this PR changes the delimiter to `#`, which I also added at the end of the heredoc.
As mentioned, that is currently not an issue. It's just not "clean", having a successful command that signals failure via the exit code. This could be a problem in the future, if we decide to introduce `set -e` widely.
PS: `-d ''` is equivalent to `-d $'\0'`.
>-d delim          continue until the first character of DELIM is read, rather than newline
> update-check: fix 'read' exit status

- target/scripts/startup/setup.d/postfix.sh
> fix: only set `virtual_mailbox_maps` to texthash when not using LDAP

- .github/workflows/linting.yml
- CHANGELOG.md
It seemed like the [linting workflow might have been possible to ignore the required check](https://github.com/docker-mailserver/docker-mailserver/pull/3705#issuecomment-1861945746), but [that was not the case](https://github.com/docker-mailserver/docker-mailserver/pull/3704#issuecomment-1861966192).
New attempt is to allow maintainers to activate the linting workflow via `workflow_dispatch` trigger. This can be accessed via the Actions tab with a dropdown on the workflow to select what branch to run it on.
Without this a different event must occur to trigger the workflow, which is inconvenient for automated PRs.
> ci: Allow lint workflow to be manually triggered

- CHANGELOG.md
- target/scripts/startup/setup.d/dovecot.sh
Fixes https://github.com/docker-mailserver/docker-mailserver/issues/3706
> Fix sed error, when ENABLE_QUOTAS=0 is set

- CHANGELOG.md
- docs/content/config/debugging.md
Services may be temporarily down, such as when restarted when certificates are updated due to the `check-for-changes.sh` service.
This is another known source of intermittent delivery failures.
> docs: Debugging - Delivery failure from service downtime

- CHANGELOG.md
- Dockerfile
- target/rspamd/local.d/actions.conf
- target/rspamd/scores.d/policies_group.conf
This PR adjusts Rspamd's symbol scores to better align with [RFC7489](https://www.rfc-editor.org/rfc/rfc7489#page-24), see #3690.
Closes #3690
> Rspamd: add custom symbol scores for SPF, DKIM & DMARC

- CHANGELOG.md
- target/postfix/main.cf
- target/scripts/startup/setup.d/postfix.sh
- test/tests/parallel/set3/mta/smtp_delivery.bats
This was always configured disabled at runtime, better to just set explicitly in `main.cf` unless config diverges when Dovecot is enabled to opt-out of this feature.
The related test now ensures that we're refuting against the expected output returned. The refute alone would still pass if the command wasn't returning the correct output to check against.
This feature still does not appear to have compatibility with Dovecot. References:
- Postfix `SMTPUTF8` docs (_has a limitations section, it can advertise support but it is not complete_): https://www.postfix.org/SMTPUTF8_README.html
- Original PR: https://github.com/docker-mailserver/docker-mailserver/pull/1223
- Original issue (_with comment stating this requires milter support too, not just dovecot_): …
> chore: Disable `smtputf8` support in config directly

- CHANGELOG.md
- test/tests/parallel/set1/spam_virus/clamav.bats
- test/tests/parallel/set3/scripts/setup_cli.bats
- test/tests/serial/tests.bats
>grep
>       -c, --count
>             Suppress normal output; instead print a count of matching lines for each input file.
> tests: Replace `wc -l` with `grep -c`

- .gitattributes
- CHANGELOG.md
- These files should always use LF for line endings.
- `Dockerfile` does not like building with HereDoc `RUN` scripts that expect LF.
---
Cloned on Windows, but ran Docker build from WSL2 which failed as Windows checkout used CRLF:
```
=> [stage-base 2/6] COPY target/bin/sedfile /usr/local/bin/sedfile                                                                                                                                               0.0s
=> ERROR [stage-base 3/6] RUN <<EOF (chmod +x /usr/local/bin/sedfile...)                                                                                                                                         0.4s
------
> [stage-base 3/6] RUN <<EOF (chmod +x /usr/local/bin/sedfile...):
0.372 chmod: cannot access '/usr/local/bin/sedfile'$'\r': No …
```
> ci: `.gitattributes` - Ensure `eol=lf` for shell scripts

- target/scripts/startup/setup.d/security/misc.sh
This is a more explicit reminder for any future contributors that get thrown off by the usage of `sed` here and may be inclined to change it.
Add a link to [reference a comment](https://github.com/docker-mailserver/docker-mailserver/pull/3767#issuecomment-1885989591) where it's already been explored what the alternative `sed` invocations available are.
---
Feel free to reject, but seems worthwhile to document? 🤷‍♂️
> chore: Add maintenance comment for `sed` usage

- CHANGELOG.md
- test/tests/parallel/set3/container_configuration/process_check_restart.bats
General improvements as noted below, makes the test more robust for any future additions.
**Revisions:**
- Removed some outdated comments about wrappers / timings that are no longer relevant.
- `pgrep` check now uses `--full` which was [initially required for MTA-STS support to pass the test](https://github.com/docker-mailserver/docker-mailserver/pull/3592#pullrequestreview-1814634068), whilst now it is more useful for matching postfix/amavis better.
- `pkill` now kills the process and asserts against the oldest matched process PID from `pgrep`. This should be the process that spawned any relevant children. Matching against the PID is better for targeting what we're interested in, since the process path is not always consistent (_`/usr/sbin/amavi` vs `/usr/sbin/amavisd-new`_).
- Added …
> tests: Revise `process_check_restart.bats`

- CHANGELOG.md
- target/bin/open-dkim
dkim key directories and files in /tmp/docker-mailserver/opendkim/keys/ are now created (chowned) with the same user / group as /tmp/docker-mailserver/opendkim/keys/. this means invoking `./setup.sh dkim domain example.com` no longer creates files as root:root when invoking inside a directory not owned by root.
Fixes #
Not 100% sure could also be just an improvement.
> fix: Ensure `setup dkim` generates DKIM keys with ownership matching the parent directory

- target/postfix/main.cf
This is just a minor addition inlined to the config for maintainers to be aware of.
Perhaps there would be a better way to approach documenting stuff like this, but while closing through my tabs I figured this was a useful comment to reference related to the setting if it's ever being changed or needs to be better understood (_linked issue is a common failure that can be encountered related to this restriction_).
---
Feel free to reject or discuss a better approach (_perhaps a single issue link that collects such information, or a markdown document for technical insights related to maintaining configs_ 🤷‍♂️ )
> docs: Add maintenance comment for `main.cf:reject_unknown_sender_domain`

- target/scripts/startup/setup-stack.sh
Applies the suggested fix from reporter: https://github.com/docker-mailserver/docker-mailserver/issues/3800#issuecomment-1905369367
- The UID / GID shifted during a new release.
- Until [DKIM handling is refactored in a new major release](https://github.com/docker-mailserver/docker-mailserver/issues/3630#issuecomment-1903401956), this fix ensures the content maintains the expected `_rspamd` ownership.
Fixes #3800
---
OpenDKIM recently had a [contribution for ownership adjustment](https://github.com/docker-mailserver/docker-mailserver/pull/3783), although that was for the user benefit with config volume files, not an issue with DMS support.
Ownership issues in `/tmp/docker-mailserver` shouldn't matter or need to be fixed for DMS, but the present rspamd DKIM support has a rather relaxed / …
> fix: Ensure correct ownership for the Rspamd DKIM directory

- CHANGELOG.md
Several issues have been raised where this was not an obvious breaking change to the reader. Additional context on impact relevance has been included.
I have updated the [corresponding Github releases entry](https://github.com/docker-mailserver/docker-mailserver/releases/tag/v13.0.0).
Related reports:
- https://github.com/docker-mailserver/docker-mailserver/issues/3546#issuecomment-1902569889
- https://github.com/docker-mailserver/docker-mailserver/issues/3809#issuecomment-1905910738
- https://github.com/docker-mailserver/docker-mailserver/issues/3814#issuecomment-1906228605
> chore: Raise awareness of v13 breaking change better (Proxy Protocol)

- docs/content/assets/css/customizations.css
- docs/mkdocs.yml
This is the easiest to maintain workaround now available. Upstream continues to reject the value such a feature for accessibility.
**Approaches evaluated:**
- Previous CSS workaround has become a maintenance burden to adapt (_becomes very verbose to support deploy/preview/dev environments_).
- An unofficial approach via redirect template as a workaround has a bad UX (_at least when tested locally_) as it loads a placeholder page for the sole purpose of redirecting via a separate HTML document, just to display an icon 🙄 
- A similar approach to the current CSS was available, but requires to be a paid sponsor of the project until they reach $20k monthly funding milestone. That is $7k away and I doubt anyone here is interested in $15/month perpetually for a fix.
- The final alternative …
> docs(fix): New external link icon workaround for mkdocs-material 9.5.5

- CHANGELOG.md
- target/scripts/helpers/accounts.sh
- target/scripts/helpers/aliases.sh
- target/scripts/helpers/utils.sh
- target/scripts/startup/setup.d/postfix.sh
- test/helper/setup.bash
- test/tests/parallel/set3/scripts/helper_functions.bats
This PR is to address a [parsing concern with `postfix-master.cf`](https://github.com/docker-mailserver/docker-mailserver/issues/3546#issuecomment-1905896062) (_no final newline ignores last line of file_), which happens to be the only config we loop through with `read` to process individual lines from but wasn't using the common helper method.
New helper methods added replace very old corrections (_that we had only for `postfix-accounts.cf`_):
- [`sed -i -e '$a\' /tmp/postfix/accounts.cf`](https://github.com/docker-mailserver/docker-mailserver/commit/63a7be0e975b39b72fe666a61517e32d32b98f55) (_2015, [associated issue](https://github.com/docker-mailserver/docker-mailserver/issues/13)_)
- [`sed -i 's/\r//g' /tmp/docker-mailserver/postfix-accounts.cf`](https://github.com/docker-mailserver/do …
> fix: Ensure configs are sanitized for parsing

- target/postfix/master.cf
Came across this docs page which seems relevant to a separate cleanup service we have configured for submission(s) services.
I figured a little documentation on that might be helpful if ever relevant for maintenance.
> docs: Add context to `sender-cleanup` in Postfix `master.cf`

- CHANGELOG.md
- target/scripts/helpers/rspamd.sh
Rspamd-related variables are declared with `readonly` in the corresponding helper. To avoid warnings in the log, we guard on whether they have already been declared.
Fixes an issues raised in #3827
> Rspamd: only declare Rspamd variables when not already declared

- .github/workflows/docs-preview-deploy.yml
Unverified, but should match what the v4 docs expect.
This action is handles initial setup of the deployment workflow (_for doc previews to Netlify_).
**Reference:**
- https://github.com/actions/download-artifact/issues/3#issuecomment-1894005257
- https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
- https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories
---
The 1st part that builds docs for PRs without trust for security reasons (_as [documented in the original PR for this workflow](https://github.com/docker-mailserver/docker-mailserver/pull/1988)_) uploads the artifact to be deployed as shown here:
https://github.com/docker-mailserver/docker-mailserver/blob/9ac11021e1c33d87ec …
> ci: `docs-preview-deploy.yml` - Use official v4 `download-artifact`

- README.md
Slight formatting changes:
- Docker badge colour was not consistent with blue shade.
- About paragraph adapted to use some bullet points, additionally linking to project creator profile.
- Docs + Issues sections merged and converted to admonitions (_or as Github calls them [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts), feature [since Dec 2023](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/)_).
Happy to revert if there's any disagreement, seemed more appropriate.
> ![image](https://github.com/docker-mailserver/docker-mailserver/assets/5098581/33c280ba-e8af-42bb-8cde-9919f44c70be)
> …
> docs: Minor revisions to `README.md`

- CHANGELOG.md
Part of the breaking changes for v14 with Debian 12 package upgrade, this config change was released in 1.4.2, while we previously had 1.4.0. Thus upstream would seem to treat it as a bugfix 👍 (_but we should probably still mention this, hence the addition to changelog for awareness_)
Can we also get confirmation from @georglauterbach on what the [dmarc equivalent behaviour in rspamd](https://www.rspamd.com/doc/modules/dmarc.html) has been configured for with DMS? (_regardless of explicitly / implicitly_). We should probably have this in sync.
Fixes #3828
> docs: Add Debian 12 breaking change for `opendmarc` package

- target/scripts/startup/setup-stack.sh
Only fix the permissions on the Rspamd DKIM directory when the directory actually exists. I just updated my deployment and saw
```txt
chown: cannot access '/tmp/docker-mailserver/rspamd/dkim': No such file or directory
```
This PR fixes the issue above.
Changelog entry not required IMO.
> Rspamd scripts: only correct permissions when directory exists

- target/scripts/build/packages.sh
As the filename includes the version / tag, we cannot rely on the latest URL to be stable.
This additionally bumps `jaq` from `v1.2.0` to [`v1.3.0`](https://github.com/01mf02/jaq/releases/tag/v1.3.0).
---
I performed a build locally with `make build` and while it didn't fail on the build, I was watching the log output and noticed a curl 404 line, which turned out to be:
```
7.203 [  TRACE  ]  Installing jaq
7.848 curl: (22) The requested URL returned error: 404
```
The build AFAIK failed for other reasons (Debian package repos being unavailable, which is common experience lately for me), so I'm not sure if the `jaq` curl failure above would normally be caught (_**EDIT:** Had a successful build, it wasn't caught as a failure_):
<details>
<summary>Debian package build log failure …
> fix: `packages.sh` - Download `jaq` via release `tag` not `latest`

- CHANGELOG.md
- target/rspamd/local.d/options.inc
For rspamd, when setting `sign_local = true;` in `dkim_signing.conf`, I expect that normal internal IP addresses are "local" by default. Looking at `options.inc`, however, you can see that a comma is missing between the last two IP blocks. So the intention is clearly there, but it does not work.
This PR adds the comma. Mails sent from an IP in 192.168.*.* are now signed on my system, which did not work before.
> fix(rspamd): Add missing comma to `local_networks` setting

- docs/content/config/security/ssl.md
- mailserver.env
> docs: fix 404 in mailserver.env and default to RSA 2048 for TLS certs

- docs/content/examples/tutorials/mailserver-behind-proxy.md
Based on the rather long discussion at https://github.com/docker-mailserver/docker-mailserver/issues/3866
The existing docs are a bit dated:
- Postfix has support for PROXY protocol v2 now (Since Postfix 3.5).
- Incorrect information at the end regarding an IMAPS port conflicting with SMTP related services `amavis` / `postscreen`.
- Dovecot override config was a bit lacking (_earlier services, no need for timeout, trusted network setting using invalid syntax `,`_)
**Added:**
- More technical insights and caveats for those it'd benefit.
- Includes a security section about forgery risk and monitoring gotchas (Roundcube + Fail2Ban) with advice to resolve.
- Small section on verifying working configuration.
- Dovecot + Postfix config for enabling PROXY protocol support + warning and …
> docs: Complete rewrite of PROXY protocol guide

- CHANGELOG.md
- target/scripts/startup/setup.d/mail_state.sh
After `setup.d/mail_state.sh` moves files/dirs from the container itself to `/var/mail-state`, they retains their SELinux security context labels, which are bound to the current container. When using named volumes, this leads to the files/dirs becoming inaccessible.
This PR lets the setup script apply the security context from the mail-state directory after moving, so they are still accessible when a new container is created that re-uses a named volume. The result is that the moved files will have the same security context as if they were created by the script.
This also explains the issue only occurs with the mail-state volume. In the other volumes only new files are created, instead of files being moved.
Fixes #3887
> fix: Apply SELinux security context after moving to mail-state

- CHANGELOG.md
- target/supervisor/conf.d/supervisor-app.conf
Executing `supervisor restart fetchmail` causes:
```
Feb 20 17:12:45 mail fetchmail[2543]: /root/.netrc: cannot open file for reading: Permission denied
```
Fetchmail checks the wrong location to see if `.netrc` exists. That's because $HOME is set to `/root`. fetchmail does not have permission to access `/root`.
http://supervisord.org/subprocess.html#subprocess-environment
> No shell is executed by supervisord when it runs a subprocess, so environment variables such as USER, PATH, HOME, SHELL, LOGNAME, etc. are not changed from their defaults or otherwise reassigned. This is particularly important to note when you are running a program from a supervisord run as root with a user= stanza in the configuration
> fix: fetchmail environment variables

- docs/content/config/environment.md
- docs/content/usage.md
- Fix typo in `docs/content/usage.md`
- Correct broken README link for SRS in `docs/content/config/environment.md`
> Fix typo and broken README link

- CHANGELOG.md
- docs/content/config/security/rspamd.md
- target/rspamd/scores.d/policies_group.conf
I updated the symbol weights according to my new insights in https://github.com/docker-mailserver/docker-mailserver/issues/3690 to fix a bug pointed out by @2GetApp and to improve the logic itself.
Previously, I reasoned about combinations of symbols that cannot exist, e.g., SPF allow, DKIM allow, DMARC reject. Removing these symbols and then reasoning about the rest is more appropriate.
Moreover, I added `DMARC_POLICY_NA` and `DMARC_POLICY_SOFTFAIL` to the whole calculation.
The issue description of https://github.com/docker-mailserver/docker-mailserver/issues/3690 I updated. I also added the Rust code I
used to do and verify the calculations.
Please review commit by commit.
Successor of: #3726
Fixes #3690
> Rspamd: improve SPF, DKIM and DMARC Symbol Weights

- CHANGELOG.md
- target/scripts/startup/setup.d/security/misc.sh
Fix for:
`[  ERROR  ]  No difference after call to 'sed' in 'sedfile' (sed -i s|rotate 4$|rotate 4| /etc/logrotate.d/fail2ban)`
> Fail2ban logrotate interval/count: substitute only when necessary

- docs/content/config/security/ssl.md
[I recently answered a discussion](https://github.com/orgs/docker-mailserver/discussions/3917#discussioncomment-8661690) regarding our docs directing users to a Certbot automation link. Figured it'd be worth including a reference to that in our docs.
> docs(TLS): Reference systemd timer example (`cerbot renew`)

- CHANGELOG.md
- docs/content/config/environment.md
- target/dovecot/90-sieve.conf
- target/scripts/startup/setup.d/security/misc.sh
- test/config/junk-mailbox/user-patches.sh
- test/tests/parallel/set1/spam_virus/rspamd_full.bats
- test/tests/parallel/set1/spam_virus/spam_junk_folder.bats
If `MOVE_SPAM_TO_JUNK=1`, spam messages now will be moved to one mailbox with `\Junk` special-use attribute. If there is no such mailbox, messages will be moved to 'Junk' mailbox, as earlier.
This change simplifies configuration in case Junk mailbox needs to be renamed.
Fixes #3918
> fix: Move spam to mailbox associated to the `\Junk` special-use attribute (#3918)

- docs/content/config/advanced/mail-forwarding/gmail-smtp.md
- docs/mkdocs.yml
deployed docs example
---
I used Gmail as the relay host and succeeded after several attempts. Based on this experience, I would like to contribute to the docs on how to quickly connect to Gmail SMTP.
Currently, the part about integrating with the Gmail SMTP server cannot be found in the guide.
Therefore, I created guidelines such as how to use two-step authentication to use Gmail SMTP, what values ​​should be entered in the host and port, and how to change the sender address.
Here is the link if this docs will be deployed.  <a href="https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/mail-forwarding/gmail-smtp">Gmail SMTP</a>
> docs: add Gmail SMTP Guide in email forwarding for documentation

- docs/content/usage.md
reading through the docs while setting up dms I found this typo
> docs: Fix typo on usage page

- compose.yaml
This should not be relevant to users of `docker compose` which is the primary demographic.
However, I know that we have users with other compose clients that parse `compose.yaml` where it may still be a gotcha, so feel free to reject this PR 👍 
---
`docker compose` (v2) [uses the v3 version of `go-yaml`](https://github.com/docker/compose/blob/4ae2e0ec551d5707da2639fb7e1783cc1a21892e/go.mod#L56C2-L56C18) for parsing YAML where **this gotcha will not occur**. This package [intentionally avoids base-60 syntax](https://github.com/go-yaml/yaml?tab=readme-ov-file#compatibility) that we have raised awareness in our example `compose.yaml`. The Go rewrite of `docker compose` did not exist back when we added this AFAIK, and the earlier Python based version of Docker Compose was more prevalent (now …
> chore: Remove base-60 port quote warning from example `compose.yaml`

- CHANGELOG.md
- target/scripts/helpers/accounts.sh
When the accounts helper was updated to adjust the users home dir via https://github.com/docker-mailserver/docker-mailserver/pull/3335 , it did not sync this change with the dummy alias accounts workaround. As we configure the dummy accounts to reference the real user account home location, this should have been in sync.
Fixes #3990
> fix(`accounts.sh`): Sync user home location for alias workaround

- docs/content/faq.md
I referenced this in [a recent PR](https://github.com/docker-mailserver/docker-mailserver/pull/3880#issue-2128015153). Might as well add this to our generic tips page for better visibility.
> docs(FAQ): Add advice for restricting login by IP

- CHANGELOG.md
- Dockerfile
- target/logwatch/ignore.conf
When using the dovecot-fts-xapian plugin as described in the "Full-Text Search" article of the projects' documentation, the daily logwatch emails get cluttered with output from the indexing of emails. 
This pull request adds an ignore.conf to the logwatch configuration with a regular expression to filter out the corresponding messages.
> chore(logwatch): Add `ignore.conf` to ignore logs from Dovecot `index-worker`

- CHANGELOG.md
- target/bin/debug-fetchmail
- target/bin/debug-getmail
- target/bin/getmail-cron
- target/scripts/startup/setup.d/getmail.sh
- target/scripts/startup/setup.d/mail_state.sh
- Log an error when the expected service state directory doesn't exist.
- The location `/var/lib/getmail/` doesn't seem like it should have been introduced. Drop it in favor of `/tmp/docker-mailserver/getmail`. It appears to be for storing remote mail that was retrieved if not configured to send to Dovecot like our docs advise. This location was never valid anyway (_as referenced issue covers_).
- Additional getmail insights are covered in a later comment of mine below.
- ~~Fetchmail debug command force enabled the feature to avoid requiring the ENV. Probably before a release when we moved the `setup` CLI into the container itself. Since the feature setup script called already gates on the feature ENV toggle and outputs a debug log when disabled... don't implicitly enable the feature.~~ …
> fix: `/var/mail-state` should not symlink non-existing directories

- docs/content/config/advanced/kubernetes.md
If not using `externalTrafficPolicy: Local` in service declaration, all incoming requests will most likely be branded as proxied by the `externalIp` by which the mail services are accessed; this is undesired. As a side effect, any `externalIp` will eventually get banned by Fail2Ban, which helped my diagnosis this misconfiguration.
I have no idea how well this enforced parameter plays along with "PROXY protocol" configuration.
> docs(k8s): Advise `externalTrafficPolicy: Local` if no PROXY protocol configured

- CHANGELOG.md
- target/logwatch/ignore.conf
Update logwatch ignore.conf to exclude Xapian messages about pending documents since it adds unnecessary noise to the logwatch summary emails.
- [ X ] Improvement (non-breaking change that does improve existing functionality)
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ X ] If necessary, I have added tests that prove my fix is effective or that my feature works
- [ X ] New and existing unit tests pass locally with my changes
- [ X ] **I have added information about changes made in this PR to `CHANGELOG.md`**
> Update logwatch ignore.conf to exclude Xapian messages about pending documents

- docs/content/examples/tutorials/mailserver-behind-proxy.md
Port 25 is managed by the Postfix service `postscreen`. By default it expects and exclusive lock. When more than one SMTP inbound service is running (_an additional PROXY protocol port_), this is a problem that can be resolved by configuring `postscreen` to use `proxy:` table for cache access instead.
Credit and thanks to @pdehne for troubleshooting a configuration I missed, and sharing the solution: https://github.com/docker-mailserver/docker-mailserver/issues/4058#issuecomment-2159610114
Fixes #4058
> docs: Document fix for PROXY protocol with `postscreen`

- .github/dependabot.yml
Due to the recent changes in the organizational structure (teams), Dependabot [currently does not find the team because the name changed](https://github.com/docker-mailserver/docker-mailserver/pull/4086#issuecomment-2186511147). I deem it appropriate to remove the assignment altogether because currently the @docker-mailserver/core-maintainers teams consists of only one person, and active maintainers will merge the MR anyway.
> CI: Remove reviewer assignment from Dependabot config

- CHANGELOG.md
- Dockerfile
- target/scripts/build/compile.sh
[Reported](https://github.com/docker-mailserver/docker-mailserver/issues/4052#issuecomment-2197237232) with [cause identified as a regression](https://github.com/docker-mailserver/docker-mailserver/issues/4052#issuecomment-2203935503) upstream.
Upstream doesn't seem to maintain a changelog and the release just states "bug fixes", [`1.7.13` was released in May 2024](https://github.com/grosjo/fts-xapian/issues/163#issuecomment-2201553781).
Updating to this release contains a fix to a regression that introduced a bug with indexing.
> fix: Update `dovecot-fts-xapian` to `1.7.13`

- docs/content/examples/tutorials/dovecot-solr.md
The `image` field is used for the default tag, if it's not specified Compose will infer one in addition to any extra `tags` provided.
Better to use `image` for the tag assignment, and a clear `pull_policy` to prevent trying to pull a remote image of the same name.
> docs: Update `compose.yaml` for `dovecot-solr` guide

- docs/content/config/security/ssl.md
- Caddy admonition - Missing `[` for annotating a link.
- Traefik - `docker-compose` => "Docker Compose"
> docs: TLS typo fix

- docs/content/examples/tutorials/docker-build.md
`DOVECOT_COMMUNITY_REPO` default changed from `1` to `0` with v14:
https://github.com/docker-mailserver/docker-mailserver/blob/4778f15fdaf5e94aee364396166fdc2821066c46/Dockerfile#L7
> docs: `docker-build.md` - Update `DOVECOT_COMMUNITY_REPO` default

- test/tests/serial/mail_with_oauth2.bats
The test case will not be able to run until Debian provides a release of curl from 2024. Better visibility and references documented for maintenance.
> tests: Update `curl` note for XOAUTH2 support

- CHANGELOG.md
- target/postfix/sender_header_filter.pcre
Microsoft added a way to "react" to emails which is turned into
> [Image] <Name> liked this message.
No MUA except Microsoft's latest ones displays these properly and they are not providing significant value to an Email-exchange.
> chore: Prevent Microsoft MUAs from sending reactions

- demo-setups/fetchmail-compose.yaml
- demo-setups/relay-compose.yaml
**NOTE:** This PR description below was added by @polarathene 
Add some of the self-contained `compose.yaml` examples that @polarathene has provided in past issues to support troubleshooting and demonstrate a feature working completely locally.
These are not intended to mirror production deployments, they sometimes take a different approach not suited for real deployments to better support quick setup
- Using non-persistent configs instead of volumes.
- Skipping proper DNS records, postfix security checks, and TLS when it can be avoided.
- Often oriented to using `swaks` as the mail client within a container and staying within the same docker network, rather than interacting with a host mail client. Hence the original issue context for related CLI commands/information.
Our users often …
> docs: Add minimal `compose.yaml` examples that demonstrate specific features

- CHANGELOG.md
- docs/content/config/environment.md
This raises awareness of a compatibility issue found when troubleshooting: https://github.com/docker-mailserver/docker-mailserver/issues/4098#issuecomment-2257201025
I've not looked into it further but the actual `docker` user / group usage is a bit unclear (_horrible choice given the project, not an easy thing to search for_). This feature at least seems to work even when the UID fails, but that may be due to `/var/mail` sticky-bit with group and the `chown`, since the `docker` user will still have their GID adjusted. For reference I did document coverage on the `docker` / `5000` user assignment and usage a while back: https://github.com/docker-mailserver/docker-mailserver/issues/3557
Just updating documentation, so the mentioned error log item would still be present if the adjustment …
> docs: Add caveat for ENV `DMS_VMAIL_UID` value compatibility

- CHANGELOG.md
- target/scripts/startup/setup.d/postfix.sh
Regression fix. A good example of why I loathe such logic with shell scripts 😩 
---
`stderr` is filtered by `grep` to discard unwanted (expected) log noise when appending the override `postfix-main.cf` content (_updated settings did not replace earlier defined instances_).
[That `grep` filter introduced a regression into DMS v14 release](https://github.com/docker-mailserver/docker-mailserver/pull/3880), since any other `stderr` content not being excluded was now blended into `stdout` and redirected with the original `stdout` output for the `postconf -n` command.
The fix is to ensure the `grep` output is redirect to `stderr` to avoid that mishap.
Fixes #4145
> fix: Prevent `stderr` being written to `/etc/postfix/main.cf`

- CHANGELOG.md
- target/scripts/start-mailserver.sh
I noticed a difference in log output when troubleshooting a recent issue. Depending on if `ENABLE_AMAVIS` was on/off, earlier logs in this file did not appear. The `touch` doesn't seem relevant as logs from starting up daemons were already present, but in this case only slightly delayed amavis logs were displayed.
Syntax of the `tail` command was slightly off, seems to require a `+` in front of the number given to `-n` 👍
> fix: Ensure main log file is tailed from the start

- CHANGELOG.md
- target/scripts/start-mailserver.sh
- Add some comments.
- `shopt -s inherit_errexit` does not seem to serve a function without `set -e` beeing used. Therefor it can be safely removed?
> chore: Add comments to `start-mailserver.sh` and stop using `inherit_errexit`

- docs/content/config/security/ssl.md
Fix typo in docker volume pathname to make example renew code to work.
Fixes #
> fix: typo in volume pathname

- CHANGELOG.md
The actual change meant for this PR was accidentally [committed directly](https://github.com/docker-mailserver/docker-mailserver/commit/4e85f799fc39365d87bbe7bc7b9151dae7f31a31) by me via `github.dev`. This PR adds the changelog along with commit reference.
Fixes: #4173
> fix: Dovecot LDAP config should exist

- README.md
Fix currently dead link for quota documentation
from: https://docker-mailserver.github.io/docker-mailserver/latest/config/account-management/overview/#quotas
to:  https://docker-mailserver.github.io/docker-mailserver/latest/config/user-management/#quotas
> fix: fix incorrect link in README.md

- target/scripts/startup/setup.d/postfix.sh
Since [I've covered this topic a few times in the past](https://github.com/docker-mailserver/docker-mailserver/issues/4178#issuecomment-2375489302), it's probably best to add a maintainer comment where LMTP is configured.
- The linked issue was proposing to change to LDA (_which would not have solved their concern_), while it was not known that DMS originally used LDA in 2016.
- This comment will act as a safe guard to caution any future PR reviews where such a change is proposed again.
A changelog entry seems unnecessary, so none added.
> chore: Add maintenance note for LMTP

- CHANGELOG.md
- target/scripts/helpers/accounts.sh
- test/config/postfix-virtual.cf
- test/tests/parallel/set3/mta/account_management.bats
Fixes #4170 and test coverage of #2640.
This is my first PR, let me know if I missed something. And regarding the CHANGELOG, would the following line be ok?
```
Fixes
- Dovecot:
- Fix dummy account creation (PR number)
```
> fix: Avoid alias being used as regex during dovecot dummy account userdb detection

- .github/workflows/docs-preview-deploy.yml
- .github/workflows/docs-preview-prepare.yml
Use metadata from Github event context instead of sourcing it from the prior workflow as a file to append to `GITHUB_ENV`.
> ci(pr-docs): Acquire metadata from context

- .github/workflows/docs-preview-deploy.yml
- .github/workflows/docs-preview-prepare.yml
- .github/workflows/scripts/docs/build-docs.sh
Refactored and better documented our CI workflows for generating documentation previews.
This PR needs to be merged before a follow-up which proposes to move away from the current `pull_request` + `workflow_run` approach that presently is not compatible with PRs from forks.
- If you would like to block and provide a review but lack time to do so within the next 24 hours, let me know otherwise I'm not expecting much feedback here and will merge without approval.
- I have ensured this change works as intended by testing via a separate repo of my own.
---
**TL;DR:** Overall, it's mostly shuffling stuff around, added comments and minor improvements. I wanted to keep the noise of these changes separate from the follow-up PR which will get a proper review process.
**Overview of changes:**
- …
> ci(docs-preview): Refactor workflows

- CHANGELOG.md
- docs/content/config/environment.md
- target/scripts/startup/variables-stack.sh
- target/supervisor/conf.d/saslauth.conf
`SASLAUTHD_MECHANISMS` only has test coverage for `ldap` and `rimap`, which were discussed during the original implementation of the feature.
The other mechanisms were added for the sake of it, but likely don't make much sense with DMS.
- Potentially `pam` would as it appears to be the way to leverage databases like `mysql` for authentication.
- `mysql` has not been a valid value for well over a decade. It's likely never worked in DMS.
Generally `SASLAUTHD` related support is not necessary for users. It was contributed as an alternative SASL auth method for Postfix to use when DMS has Dovecot disabled that would normally be delegated for SASL authentication.
Users interested in MySQL or similar DB access could configure for such directly with Postfix and Dovecot (or just Dovecot due to …
> fix: SASLAuth - Drop services for `mysql`, `shadow`, `pam` auth mechanisms

- CHANGELOG.md
- target/scripts/build/packages.sh
- target/scripts/startup/setup.d/security/rspamd.sh
- Bump to [`jaq` v2 release](https://github.com/01mf02/jaq/releases/tag/v2.0.0), artifact naming convention changed.
- Tidied up the changelog a little bit unrelated to this update.
- Fixed a typo with an `rspamd.sh` comment + minor revision to the comment.
> chore: Update `jaq` to `2.0.0`

- .github/ISSUE_TEMPLATE/bug_report.yml
This input has not provided much value to us since it's introduction, removing as redundant.
> ci(`bug_report.yml`): Drop the feedback input field

- docs/content/config/environment.md
Following message is displayed after clicking the old link: 
The old wiki has been closed
Our primary documentation is now at https://doc.dovecot.org, please update your links.
> docs: Environment - Update Dovecot docs URL

- docs/content/config/security/ssl.md
Suggested recently by this discussion feedback: https://github.com/orgs/docker-mailserver/discussions/4304#discussioncomment-11736709
As the TLS examples for other services default to public CA with LetsEncrypt, the Caddy example was configuring TLS to use self-signed certificates instead. This PR makes it consistent with the other service examples and revises some commentary.
Direct preview link: https://pullrequest-4305--dms-doc-previews.netlify.app/config/security/ssl/#caddy
> docs: TLS (Caddy) - Revise advice on `tls internal`

- docs/content/examples/use-cases/bind-smtp-network-interface.md
Added info how to setup docker to use the same interface for outgoing traffic. Problem was that I was using single VPS for sites and mailserver. I got the additional IP address but all outgoing traffic from mailserver was going through the original IP. This network config makes the container use specified IP for outgoing traffic too. 
Problem manifested as the mail-tester.com saw the original VPS IP address and failed on rDNS checks even when setup with suggestions from this part of page.
Fixes #
- [] My code follows the style guidelines of this project
> docs: `bind-smtp-network-interface.md` - Add bridge network config advice

- demo-setups/relay-compose.yaml
Prefer using a network alias on the desired container which all containers in the same network can route through vs `links` mapping which is less flexible (_two containers cannot have `links` that map between each other_).
Other changes are just shifting a config snippet above the account config snippets and minor revisions to commentary.
> chore: `demo-setups/relay-compose.yaml` should use network alias

- Dockerfile
- target/scripts/start-mailserver.sh
- target/scripts/startup/setup.d/dovecot.sh
I noticed the `postmaster_address` line looked odd in the Dockerfile, and that we actually run it properly in our startup scripts (_it's been in scripts [for over 5 years](https://github.com/docker-mailserver/docker-mailserver/blame/189e5376cc91af4f8a6b1e0db7b8f20e53a932a1/target/scripts/start-mailserver.sh#L542)_). That motivated this PR.
The protocol line was likewise migrated to be grouped with the related script lines with some minor revision.
The other 3 lines from the Dockerfile were all LDA specific which we haven't used since prior to DMS v2 (2016?), actually no I think we switched from Courier to Dovecot for v2, and then there was a switch from LDA to LMTP when around when LDAP support was contributed (_2016H2 or 2017 IIRC, **EDIT:** [LDA to LMTP in Oct …
> chore: Migrate dovecot config from Dockerfile

- .github/workflows/scripts/docs/build-docs.sh
Upgrade our CI docs container to the recent [`9.6` series](https://github.com/squidfunk/mkdocs-material/releases/tag/9.6.0) which fixes a navigation link bug (_see linked release notes_).
> ci: Upgrade `mkdocs-material` to 9.6

- docs/content/config/best-practices/dkim_dmarc_spf.md
- docs/content/config/debugging.md
- docs/content/contributing/general.md
Spotted a bad ref link (_specifically the [MD052 rule](https://github.com/DavidAnson/markdownlint/blob/main/doc/md052.md), we use ["full" ref links](https://github.com/DavidAnson/markdownlint/issues/918)_), used a linter to search for any others and fixed those too.
```console
$ docker run --rm -t -v ./docs:/docs:Z,ro ghcr.io/igorshubovych/markdownlint-cli:latest \
--disable default --enable MD052 --json '/docs/**/*.md' \
| jq -r '.[] | "\(.fileName):\(.lineNumber) => \(.errorContext)"'
content/config/best-practices/dkim_dmarc_spf.md:57 => [email account setup][docs-accounts-add]
content/config/debugging.md:114 => [port forwarding driver][docs-rootless-portdriver]
```
Using linters on markdown aren't entirely reliable for our docs due to non-standard mkdocs syntax, notably [admonitions …
> docs: Fix broken ref links

- CHANGELOG.md
- target/bin/delmailuser
- Delete the mailbox data only if the user provides explicit confirmation.
- Make it more clear to the user, when the mailbox data is deleted or not.
Fixes #4338
> Make deletion of mailbox data opt-in

- docs/content/config/security/rspamd.md
I initially wanted to just fix a typo on the ARC section, then rewrote that section and got carried away tidying up the docs for this page 😅 
[Spotted a possible issue](https://github.com/rspamd/rspamd/issues/5341) for upstream to resolve in the process 🎉 (_nothing concerning, just unexpected_)
**NOTE:** I'm now referring to our existing anti-spam services as "Legacy", I'm not sure if that's accurate/fitting, let me know if there's a better alternative if that's not ok.
---
Apologies again for the verbose diff and single commit. I'm trying to get quite a bit of docs updates through for DMS v15 release and keep getting distracted 😮‍💨
> docs: Revise Rspamd page

- target/scripts/startup/setup.d/mail_state.sh
- target/scripts/startup/variables-stack.sh
Removes `__declare_readonly` again which was introduced in #4323.
Fixes https://github.com/docker-mailserver/docker-mailserver/pull/4323#issuecomment-2660618801
> fix: revert `__declare_readonly` overcomplication

- CHANGELOG.md
- target/scripts/start-mailserver.sh
- target/scripts/startup/setup-stack.sh
- target/scripts/startup/setup.d/log.sh
- target/scripts/startup/setup.d/security/misc.sh
This is an [interim fix](https://github.com/docker-mailserver/docker-mailserver/pull/4370#issuecomment-2661678014) for DMS v15 until a [proper fix](https://github.com/docker-mailserver/docker-mailserver/pull/4370#issuecomment-2661762043) can more confidently be implemented.
Changes:
- Migrates what was [originally contributed in Oct 2019](https://github.com/docker-mailserver/docker-mailserver/commit/37e0082cd7998924564c542cc24e5ac72c7ef6c2) to `setup-stack.sh` for container restart support.
- Ensures permissions of `/var/log/mail/` and it's contents are corrected if a volume mount differs.
History for these changes is messy (_as documented in the "proper fix" link_), but looks like it shouldn't really be necessary going forward (_new permissions fix may be relevant to avoid the …
> fix: Ensure `/var/log/mail` permissions + ownership are correct

- docs/content/config/security/rspamd.md
https://github.com/docker-mailserver/docker-mailserver/pull/4360 had a typo with the new ref link.
> docs(rspamd): Fix Web UI link

- target/postfix/main.cf
- target/scripts/startup/setup.d/postfix.sh
I've noticed that `/etc/postfix/main.cf` has these checks prepended twice, as the Postfix parameter we update also has the `sed` call match our own `dms_` prefix variant (_introduced in_ https://github.com/docker-mailserver/docker-mailserver/pull/3127).
**No known bugs, nor should this fix change anything** other than removing the duplicates prepended to `smtpd_sender_restrictions`, only `dms_smtpd_sender_restrictions` will be configured with these restrictions.
---
To configure how the sender addresses of mail is restricted, DMS has a few similar settings due to:
- `smtpd_sender_restrictions = $dms_smtpd_sender_restrictions` (`main.cf`)
- `-o smtpd_sender_restrictions=$mua_sender_restrictions` (`master.cf`)
That translates to the following:
- `smtpd_sender_restrictions` is now only from …
> fix: `setup email restrict` configs should only prepend once

- CHANGELOG.md
- target/scripts/startup/setup-stack.sh
To prevent SSD wear from logs, I mount `/var/log/mail/` to tmpfs in my setup. I collect logs from standard output using Loki.
As a result, the `/var/log/mail` directory is empty whenever the container restarts. Attempting to change permissions on this directory using shell expansion leads to errors like:
```
chmod: missing operand after ‘640’
Try 'chmod --help' for more information.
```
Using `find` avoids running `chmod` if there is nothing to modify, preventing these errors. It's also more convenient than shell expansion, which can cause errors like "too many arguments".
> fix: Support `chmod` on `/var/log/mail/*` when dir is empty

- CHANGELOG.md
- target/scripts/build/packages.sh
`step` isn't used for anything yet, so no rush for this PR, but it won't introduce any breakage into DMS v15 😅 
---
Changes:
- `jaq` should probably live in `/usr/local/bin` with other third-party sourced binaries.
- `swaks` install properly with just `tar`, no `mv` + `rm` needed.
- Added Smallstep `step` CLI. This serves similar purpose to `openssl` commands, but is generally nicer for usage with generation and inspection of certs/keys. I've talked up using in DMS a few times in the past for our TLS helper and unifying DKIM support (_instead of separate OpenDKIM/Rspamd generators_).
- Including `step` for both AMD64 / ARM64 archs needs the alternate naming convention that it's published to GH releases with.
- Added commentary about the `tar` usage. The ownership is a common one, …
> chore: Revise utility install scripts + add Smallstep `step` CLI

- target/scripts/startup/setup.d/postfix.sh
For DMS v15.0.1 we recently merged https://github.com/docker-mailserver/docker-mailserver/pull/4379 and @ap-wtioit thankfully [spotted a bug](https://github.com/docker-mailserver/docker-mailserver/issues/4398) before release 💪 
This was my fault, and we should have a better test case to detect this on our end via CI... however I'm too strapped for time right now to tackle that 😭 
Fixes: #4398
> fix: `postfix-receive-access.cf` should prepend to `smtpd_recipient_restrictions`

- docs/content/config/security/fail2ban.md
Added instructions to edit env to enable fail2ban
Docs are missing a hint on how to actually enable fail2ban
Fixes #
Added hint.
> docs: Fail2Ban - Add example with required ENV to enable

- target/scripts/start-mailserver.sh
Spotted from logs of https://github.com/docker-mailserver/docker-mailserver/issues/4416#issuecomment-2727269499
- Our test suite doesn't have coverage for restart support, so this went unnoticed and wasn't caught in review (https://github.com/docker-mailserver/docker-mailserver/pull/4323#issuecomment-2629559254).
- While the other restart supported method we call is part of `setup-stack.sh`, the other call lives at `setup.d/mail_state.sh`, thus we need to source it to be able to call it.
> fix: `start-mailserver.sh` requires `mail_state.sh` to be sourced on restarts

- CHANGELOG.md
- target/postfix/sender_header_filter.pcre
- test/tests/parallel/set3/container_configuration/hostname.bats
Due to an oversight, one of the header filters has potentially modified the message body, leading to broken cryptographic signatures.
Switch to the Message-Id instead of the Content-Type header, which is usually only present in the global header.
Reported-by: Cole Young <cole@young.sh>
Fixes: 009237cc ("chore: Prevent Microsoft MUAs from sending reactions (#4120)")
> fix: ensure message content is not modified by header filter

- mailserver.env
Fix broken README link for SRS. Same as in #3906 but for `mailserver.env`.
> Fix broken README link for SRS

- CHANGELOG.md
- target/bin/open-dkim
- target/scripts/helpers/error.sh
- target/scripts/helpers/log.sh
- target/scripts/helpers/utils.sh
- target/scripts/startup/setup.d/dmarc_dkim_spf.sh
- test/helper/common.bash
- test/helper/setup.bash
- test/tests/serial/open_dkim.bats
Up to you if you'd like to include this in DMS `15.0` or DMS `15.1`. As this is only a change for a setup CLI command, it's not something I'd consider breaking, and functionality wise it should be roughly the same. Tests also seem to indicate all is well 👍 
---
I recently did some refactoring on this command while going over unifying our DKIM feature support.
- Adds a `main()` method similar to other setup CLI commands.
- Help text more aligned with equivalent rspamd DKIM setup CLI command.
- DRY some repetition such as hard-coded paths to use variables.
- OpenDKIM config files are created / initialized early on now with `_create_opendkim_configs()`. `while` loop only needs to append entries, so is easier to grok.
- `_create_dkim_key()` to scope just the logic (_and additional notes_) to …
> refactor: setup CLI `open-dkim`

- docs/content/contributing/tests.md
We don't work on the test suite that much these days, for the benefit of any future contributors/maintainers, referencing [my recent comment on `TEST_TMP_CONFIG`](https://github.com/docker-mailserver/docker-mailserver/pull/4359#issuecomment-2817591085) may be helpful to grok the functionality.
> docs: Contributing (tests) - Link to guidance for `TEST_TMP_CONFIG`

- CHANGELOG.md
- docs/content/config/environment.md
- target/scripts/check-for-changes.sh
- target/scripts/startup/variables-stack.sh
Makes the ``check-for-changes.sh`` execution interval configurable (see issue for details).
Picked a default value of ``20`` because
* it roughly halfs the idle load 
* it's still reactive enough when changes occur
Fixes #4414
> feat: Configurable poll rate for `check-for-changes.sh`

- docs/content/config/security/ssl.md
- test/tests/parallel/set2/tls_cipherlists.bats
The `testssl` project [moved to an organization](https://github.com/testssl/testssl.sh/commit/b708026151bba8d3bb06c35b5117eb9a50419929). Images are now also [published to GHCR](https://github.com/testssl/testssl.sh/pkgs/container/testssl.sh) so we'll use that image going forward.
Probably not worth adding noise to the changelog for this minor change 😅
> tests: Reference the new `testssl` image location

- CHANGELOG.md
- docs/content/config/environment.md
- target/bin/listmailuser
- target/scripts/startup/variables-stack.sh
This addresses https://github.com/orgs/docker-mailserver/discussions/4452#discussioncomment-12918479
It should provide a better UX than a bunch of unhelpful errors like the user experienced.
> fix: `setup email list` should only work with `ACCOUNT_PROVISIONER=FILE`

- CHANGELOG.md
- mailserver.env
I tried using `pam`, `shadow`, `mysql` setting for the ENV `SASLAUTHD_MECHANISMS` but I didn't get it to work. After not finding anything in the documentation, I came across #4259.
It seems the options in the ENV file were not removed. 😃
> docs: `mailserver.env` - Remove unsupported SASL auth mechanisms

- CHANGELOG.md
- docs/content/config/environment.md
- target/scripts/startup/variables-stack.sh
- test/tests/parallel/set3/container_configuration/env_vars_from_files.bats
Fixes #3457.
Allows setting any environment variable via the content of a file, this is especially useful to carry Docker secrets in. This fix takes inspiration from a few similar approaches, namely Bitnami container images (e.g., [OpenLDAP](https://github.com/bitnami/containers/blob/02bcf4b54c8af61c18d5cb557b21dba317e36b48/bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh#L99-L117)) and [Grafana](https://github.com/grafana/grafana/blob/be426858529d9742808cc8ad4ed226379fb770da/packaging/docker/run.sh#L49-L61).
I have marked this as a breaking change since it would change the behavior of setups providing `<VAR>__FILE` env vars where `<VAR>` is an existing configuration variable. However, you may consider that to be negligible.
I've noticed a few Fail2ban tests …
> feat: Enable reading env vars from files

- docs/content/examples/tutorials/mailserver-behind-proxy.md
When the entrypoints for traefik are defined there are named mail-*(smtp,...), but it the dms labels when it comes to using these entry point in the TLS section just smtp is used, and for TLS it is used smtp-submissions witch is an invalid entrypoint
I tried recreating the setup for DMS using traefik as a reverse proxy, but instead of writing the entrypoints in the docker compose file, i used the toml version to do this. Following the docs and translating the cli commands into the toml I got this:
```tml
...............
entryPoints:
mail-smtp:
address: ":25"
mail-submission:
address: ":587"
mail-submissions:
address: ":465"
mail-iamp:
address: ":143"
mail-imaps:
address: ":993"
mail-pop3:
address: ":110"
mail-pop3s:
address: ":995"
mail-managesieve:
address: ":4190"
...............
``` …
> docs: PROXY protocol advice for Traefik should reference correct entrypoints

- CHANGELOG.md
- target/scripts/startup/setup-stack.sh
This is similar to a [recent fix for the DMS state volume](https://github.com/docker-mailserver/docker-mailserver/pull/4420), where a non-root user needs access but the host directory mounted has mistakenly been too aggressive with permissions for the directory (_one known example is [AWS ECS (EC2) using EBS volumes](https://github.com/docker-mailserver/docker-mailserver/issues/4419#issuecomment-2731430310)_).
It appears that Rspamd support with DKIM at least [expects this due to running operations as the `_rspamd` user](https://github.com/docker-mailserver/docker-mailserver/issues/4485#issuecomment-2902642469) to read content from the DMS config volume. In future this concern shouldn't be the case, as the root user during setup could make internal copies that anything running as …
> fix: Ensure DMS config volume can be accessed by non-root users

- CHANGELOG.md
- target/scripts/build/packages.sh
This workaround can be dropped :)
The [original issue report](https://github.com/docker-mailserver/docker-mailserver/issues/2023#issuecomment-855326403) workaround we presently use, and the [verified alternative workaround](https://github.com/docker-mailserver/docker-mailserver/pull/2468#issuecomment-1232428884) (_via buildx arg_) are no longer appear required since upstream commits (_[1](https://salsa.debian.org/postfix-team/postfix-dev/-/commit/77850ee129745608d8e27c40e39462d693894c14) + [2](https://salsa.debian.org/postfix-team/postfix-dev/-/commit/a1d904dc162dfb810fc5b44b0f3efc45b07c12f8)_) in late 2021 have patched the logic in the [Debian Postfix package post-install script](https://salsa.debian.org/postfix-team/postfix-dev/-/blob/aaaa72f00c4bc856300822185ee6ea2b865dcc3d/debian/postf …
> fix: `packages.sh` - Remove Postfix hostname workaround

- CHANGELOG.md
- docs/content/config/environment.md
- mailserver.env
Changed the description of OVERRIDE_HOSTNAME environment variable, to raise awareness of unforeseen side effects.
The current documentation of `OVERRIDE_HOSTNAME` in `mailserver.env` doesnt reflect the fact that setting this can lead to unforeseen problems. See explanation at the bottom of this comment https://github.com/docker-mailserver/docker-mailserver/issues/4484#issuecomment-2908101121
When setting up DMS the first time i thought it would be better to set it to make sure all internal services use the correct hostname. When in reality its better not to set this unless you need to.
While at it i reformated the text so it looks more like the rest of the comments in the file. Now with no trailing whitespaces.
I dont think this is necessary since the documentation already tells to only …
> docs: Revise docs for the `OVERRIDE_HOSTNAME` ENV

- docs/content/examples/tutorials/mailserver-behind-proxy.md
Better align with Helm chart changes: https://github.com/docker-mailserver/docker-mailserver-helm/pull/174
`-proxied` => `-proxyprotocol`
> docs: Adjust PROXY Protocol port names

- CHANGELOG.md
- target/bin/open-dkim
Use numerical uid and gid for chown as they should always work even when the uid and gid have no names in /etc/...
in case the owner user does not exist in the image we get the following error:
```
open-dkim: Creating DKIM private key '/tmp/docker-mailserver/opendkim/keys/subdomain.example.com/mail.private'
chown: invalid user: 'UNKNOWN:UNKNOWN'
```
Info @wt-io-it
> fix: open-dkim - Use numerical uid and gid for chown

- CHANGELOG.md
- docs/content/config/best-practices/dkim_dmarc_spf.md
This PR improves the DKIM setup docs by correcting the config path that the helper script uses, and it removes the mentioned need for additional config volume mount. 
Fixes #4521
> docs: Fix path in dkim helper script (rspamd)

- docs/content/examples/tutorials/mailserver-behind-proxy.md
Small improvement to move the postscreen cache advice to `user-patches.sh` instead of `postfix-main.cf`. Related to https://github.com/docker-mailserver/docker-mailserver-helm/pull/187
> docs: Proxy Protocol share `postscreen_cache_map`

- target/scripts/startup/setup.d/fetchmail.sh
This is just a follow-up PR to [address an improvement](https://github.com/docker-mailserver/docker-mailserver/pull/4586#pullrequestreview-3302718302) about the inline documentation of our scripts.
[Our docs page for Fetchmail](https://docker-mailserver.github.io/docker-mailserver/v15.1/config/advanced/mail-fetchmail/) doesn't make mention of the parallel / IMAP IDLE related feature presently either (_this is only [briefly covered in our ENV docs for `FETCHMAIL_PARALLEL`](https://docker-mailserver.github.io/docker-mailserver/v15.1/config/environment/#fetchmail_parallel)_). I'll add a TODO note about getting that updated at some point too 😅
> chore: Revise inline docs for Fetchmail
